function result = mh_atlas_build_binary_atlas(specPath, varargin)
% Build a binary MNI-space atlas from a declarative ROI JSON spec.

parser = inputParser;
parser.addRequired('specPath', @(x) ischar(x) || isstring(x));
parser.addParameter('Force', true, @(x) islogical(x) || isnumeric(x));
parser.addParameter('Cleanup', true, @(x) islogical(x) || isnumeric(x));
parser.parse(specPath, varargin{:});
opts = parser.Results;
opts.Force = logical(opts.Force);
opts.Cleanup = logical(opts.Cleanup);

spec = mh_atlas_load_spec(specPath);

ensure_dir(spec.output_dir);
ensure_dir(fullfile(spec.output_dir, 'lh'));
ensure_dir(fullfile(spec.output_dir, 'rh'));

tempDir = fullfile(spec.output_dir, '.build_tmp');
ensure_dir(tempDir);

records = struct([]);
for i = 1:numel(spec.rois)
    roi = spec.rois(i);
    for sideCell = {'L', 'R'}
        side = sideCell{1};
        record = mh_atlas_build_roi_mask(spec, roi, side, tempDir, opts);
        records = append_record(records, record); %#ok<AGROW>
    end
end

manifestPaths = mh_atlas_write_manifest(spec, records);
qc = mh_atlas_write_qc(spec, records);
readmePath = write_atlas_readme(spec, records, qc);

if opts.Cleanup && isfolder(tempDir)
    rmdir(tempDir, 's');
end

result = struct();
result.spec = spec;
result.records = records;
result.qc = qc;
result.manifestCsv = manifestPaths.csv;
result.manifestJson = manifestPaths.json;
result.qcCsv = fullfile(spec.output_dir, 'roi_qc.csv');
result.readme = readmePath;
result.outputDir = spec.output_dir;

fprintf('Built atlas: %s\n', spec.atlas_name);
fprintf('Output: %s\n', spec.output_dir);
fprintf('ROIs: %d records\n', numel(records));
end

function records = append_record(records, record)
if isempty(records)
    records = record;
else
    records(end+1) = record;
end
end

function ensure_dir(path)
if ~isfolder(path)
    mkdir(path);
end
end

function readmePath = write_atlas_readme(spec, records, qc)
readmePath = fullfile(spec.output_dir, 'README.md');
fid = fopen(readmePath, 'w');
if fid < 0
    error('mh_atlas_build_binary_atlas:ReadmeOpenFailed', ...
        'Cannot write README: %s', readmePath);
end
cleaner = onCleanup(@() fclose(fid));

fprintf(fid, '# %s\n\n', spec.atlas_name);
fprintf(fid, 'Generated by `mh_atlas_build_binary_atlas` on %s.\n\n', datestr(now, 31));
fprintf(fid, 'Space: `%s`\n\n', spec.space);
fprintf(fid, 'Reference image: `%s`\n\n', spec.reference_image);
fprintf(fid, 'This atlas contains binary masks for seed-target tractography. ');
fprintf(fid, 'Each ROI is defined by `roi_manifest.csv` and checked in `roi_qc.csv`.\n\n');

fprintf(fid, '## ROI Summary\n\n');
fprintf(fid, '| ROI | Side | Role | Category | Operation | Threshold | Output |\n');
fprintf(fid, '|---|---|---|---|---|---:|---|\n');
for i = 1:numel(records)
    rec = records(i);
    fprintf(fid, '| `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` |\n', ...
        rec.roi_name, rec.side, rec.role, rec.category, rec.operation, ...
        rec.threshold, relative_to(spec.output_dir, rec.output_file));
end

if nargin >= 3 && ~isempty(qc)
    emptyCount = sum([qc.empty_mask]);
    sideFail = sum(~[qc.side_ok]);
    fprintf(fid, '\n## QC Summary\n\n');
    fprintf(fid, '- ROI-side records: %d\n', numel(qc));
    fprintf(fid, '- Empty masks: %d\n', emptyCount);
    fprintf(fid, '- Side-check failures: %d\n', sideFail);
end
end

function rel = relative_to(root, path)
root = char(string(root));
path = char(string(path));
if startsWith(path, [root, filesep])
    rel = path(numel(root)+2:end);
else
    rel = path;
end
end
