% Static regression check that B0 is treated as a formal normalization modality.

repoDir = fileparts(mfilename('fullpath'));
normalizeText = fileread(fullfile(repoDir, 'ea_normalize.m'));
applyText = fileread(fullfile(repoDir, 'ext_libs', 'ANTs', 'ea_ants_apply_transforms.m'));
fetcherText = fileread(fullfile(repoDir, 'helpers', 'BIDSFetcher.m'));

requiredSnippets = { ...
    'runOptions = options;', ...
    'preopFields = fieldnames(options.subj.coreg.anat.preop);', ...
    'input{preopFile} = options.subj.coreg.anat.preop.(preopFields{preopFile});', ...
    'output{preopFile} = options.subj.norm.anat.preop.(preopFields{preopFile});', ...
    'normAnat.(session{i}).(modality{j}) = strrep(anat, obj.anchorSpace, templateSpace);'};

combinedText = [normalizeText, newline, applyText, newline, fetcherText];
for i = 1:numel(requiredSnippets)
    assert(contains(combinedText, requiredSnippets{i}), ...
        'Missing formal B0 normalization snippet: %s', requiredSnippets{i});
end

forbiddenSnippets = { ...
    'ea_exclude_b0_from_normalization', ...
    'Excluding pseudo B0 volume from normalization inputs', ...
    'coregAnat.preop = rmfield(coregAnat.preop, fields(2:end));'};

for i = 1:numel(forbiddenSnippets)
    assert(~contains(combinedText, forbiddenSnippets{i}), ...
        'Formal B0 normalization should not use snippet: %s', forbiddenSnippets{i});
end

fprintf('Formal B0 normalization static check passed.\n');
