function exports = ...
        mh_viz_export_pdq39_fiber_coefficient_pdfs(outputDirectory, varargin)
% Export coefficient-colored PDQ-39 fiber PDFs without visible figures.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, 'outputDirectory', @(value) ischar(value) || ...
    (isstring(value) && isscalar(value)));
addParameter(parser, 'PublicationRoot', ...
    ['/Volumes/VAL/STNSNr/summary/spot/normative_fiber/', ...
    'dual_frequency_four_model_v1'], ...
    @(value) ischar(value) || (isstring(value) && isscalar(value)));
addParameter(parser, 'ScaleId', 'pdq39_score', ...
    @(value) ischar(value) || (isstring(value) && isscalar(value)));
addParameter(parser, 'Views', mh_viz_default_fiber_views(), ...
    @(value) isstruct(value) && isscalar(value));
addParameter(parser, 'FilePrefix', 'pdq39_fiber_coefficient', ...
    @(value) ischar(value) || (isstring(value) && isscalar(value)));
addParameter(parser, 'Resolution', 600, ...
    @(value) isnumeric(value) && isscalar(value) && ...
    isfinite(value) && value > 0);
parse(parser, outputDirectory, varargin{:});

outputDirectory = char(string(parser.Results.outputDirectory));
if isempty(strtrim(outputDirectory))
    error([mfilename, ':MissingOutputDirectory'], ...
        'outputDirectory must be nonempty.');
end
if isfolder(outputDirectory) || isfile(outputDirectory)
    error([mfilename, ':OutputExists'], ...
        'Refusing to replace an existing output path: %s', outputDirectory);
end
[outputParent, ~, ~] = fileparts(outputDirectory);
if isempty(outputParent)
    outputParent = pwd;
end
if ~isfolder(outputParent)
    mkdir(outputParent);
end
stageDirectory = tempname(outputParent);
mkdir(stageDirectory);

publicationRoot = char(string(parser.Results.PublicationRoot));
scaleId = char(string(parser.Results.ScaleId));
views = parser.Results.Views;
filePrefix = char(string(parser.Results.FilePrefix));
resolution = double(parser.Results.Resolution);
roles = {'reference', 'addon'};
modelFamilies = {'reference_fiber', 'addon_fiber'};
atlasRoiIndices = [2, 1];
fiberStyle = mh_viz_default_fiber_scene_spec();
expectedExportCount = local_expected_export_count(views, roles);
exports = repmat(struct('model_role', '', 'view_index', 0, ...
    'view', struct(), 'pdf_path', ''), 0, 1);
roleRecords = repmat(struct( ...
    'role', '', ...
    'model_family', '', ...
    'input_path', '', ...
    'input_request_hash', '', ...
    'selected_tau_v_per_m', [], ...
    'selected_coverage_subjects_min', [], ...
    'candidate_fiber_count', 0, ...
    'rendered_fiber_count', 0, ...
    'coefficient_min', 0, ...
    'coefficient_max', 0, ...
    'symmetric_color_limit', 0, ...
    'colorbar_label', ''), numel(roles), 1);

for roleIndex = 1:numel(roles)
    role = roles{roleIndex};
    prepared = mh_viz_prepare_scene_example_input( ...
        publicationRoot, modelFamilies{roleIndex}, 'ScaleId', scaleId);
    colorbarLabel = sprintf( ...
        'Benefit-oriented partial Spearman ρ with %s', ...
        prepared.scale_display_name);

    spec = struct();
    spec.FiberCoefficientMat = prepared.input_path;
    spec.FiberColorbarLabel = colorbarLabel;
    spec.AtlasName = 'Custom_STNSNr';
    spec.ShowAtlasWireframe = true;
    spec.AtlasRoiIndices = atlasRoiIndices(roleIndex);
    spec.AtlasEdgeAlpha = 0.15;
    spec.CoefficientFiberAlpha = fiberStyle.CoefficientFiberAlpha;
    spec.CoefficientFiberLineWidth = fiberStyle.CoefficientFiberLineWidth;
    spec.FiberColorbarTextColor = fiberStyle.FiberColorbarTextColor;
    spec.ShowFiberLegend = false;
    spec.BackgroundColor = fiberStyle.BackgroundColor;
    spec.AddRASTriad = fiberStyle.AddRASTriad;
    spec.ShowAnatomySlices = fiberStyle.ShowAnatomySlices;
    spec.AnatomyNifti = fiberStyle.AnatomyNifti;
    spec.AnatomySlicePlane = fiberStyle.AnatomySlicePlane;
    spec.AnatomySliceCoordinateMm = ...
        fiberStyle.AnatomySliceCoordinateMm;
    spec.AnatomySliceTransparencyPercent = ...
        fiberStyle.AnatomySliceTransparencyPercent;
    spec.AddToolbarToggles = false;
    spec.ViewStruct = views.(role){1};
    spec.FigureVisible = 'off';
    spec.FigureBackend = 'matlab';
    spec.StrictHeadless = true;
    spec.OutputFig = '';
    spec.OutputImage = '';
    spec.OutputPdf = '';
    spec.OutputSpin = '';
    spec.CloseAfterExport = false;

    figuresBefore = findall(groot, 'Type', 'figure');
    scene = mh_viz_make_sweet_sour_scene(spec);
    newFigures = setdiff(findall(groot, 'Type', 'figure'), figuresBefore);
    figureCleanup = onCleanup(@() local_delete_figures(newFigures));
    local_assert_hidden(newFigures);
    local_assert_coefficient_scene( ...
        scene, prepared, fiberStyle, colorbarLabel, role);

    roleExports = mh_viz_export_scene_views( ...
        scene, stageDirectory, role, ...
        'Views', views, ...
        'FilePrefix', filePrefix, ...
        'BackgroundColor', fiberStyle.BackgroundColor, ...
        'Resolution', resolution, ...
        'IncludeAnatomySlices', true, ...
        'RequireRASLabels', false);
    exports = [exports; roleExports(:)]; %#ok<AGROW>

    metadata = scene.objects.fiberCoefficientMetadata;
    roleRecords(roleIndex).role = role;
    roleRecords(roleIndex).model_family = modelFamilies{roleIndex};
    roleRecords(roleIndex).input_path = prepared.input_path;
    roleRecords(roleIndex).input_request_hash = prepared.request_hash;
    roleRecords(roleIndex).selected_tau_v_per_m = prepared.selected_tau;
    roleRecords(roleIndex).selected_coverage_subjects_min = ...
        prepared.selected_coverage;
    roleRecords(roleIndex).candidate_fiber_count = ...
        metadata.candidate_fiber_count;
    roleRecords(roleIndex).rendered_fiber_count = ...
        metadata.rendered_fiber_count;
    roleRecords(roleIndex).coefficient_min = metadata.score_min;
    roleRecords(roleIndex).coefficient_max = metadata.score_max;
    roleRecords(roleIndex).symmetric_color_limit = ...
        metadata.score_color_limit;
    roleRecords(roleIndex).colorbar_label = colorbarLabel;

    local_delete_figures(newFigures);
    clear figureCleanup;
end

if numel(exports) ~= expectedExportCount
    error([mfilename, ':IncompleteExport'], ...
        ['Strict-headless export produced %d PDFs, but the configured ', ...
        'role views require %d.'], numel(exports), expectedExportCount);
end

outputRecords = repmat(struct( ...
    'model_role', '', 'view_index', 0, 'relative_path', '', ...
    'sha256', '', 'size_bytes', 0, 'view', struct()), numel(exports), 1);
for index = 1:numel(exports)
    [~, name, extension] = fileparts(exports(index).pdf_path);
    relativePath = [name, extension];
    outputRecords(index).model_role = exports(index).model_role;
    outputRecords(index).view_index = exports(index).view_index;
    outputRecords(index).relative_path = relativePath;
    outputRecords(index).sha256 = local_file_sha256(exports(index).pdf_path);
    info = dir(exports(index).pdf_path);
    outputRecords(index).size_bytes = info.bytes;
    outputRecords(index).view = exports(index).view;
end

manifest = struct();
manifest.schema_version = 'pdq39_coefficient_fiber_3d_export_v2';
manifest.status = 'complete';
manifest.scale_id = scaleId;
manifest.publication_root = publicationRoot;
manifest.created_at_utc = char(datetime( ...
    'now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX'));
manifest.strict_headless = true;
manifest.figure_visible = 'off';
manifest.figure_backend = 'matlab';
manifest.style = struct( ...
    'render_scope', 'all_candidate_fibers', ...
    'coefficient_source', 'full_sample_benefit_oriented_fiber_scores', ...
    'colormap', 'vik', ...
    'colormap_samples', 256, ...
    'color_range', 'symmetric_zero_centered_per_model', ...
    'fiber_alpha', fiberStyle.CoefficientFiberAlpha, ...
    'fiber_line_width_points', fiberStyle.CoefficientFiberLineWidth, ...
    'fiber_sampling', 'none', ...
    'point_sampling', 'none', ...
    'count_legend', false, ...
    'right_colorbar', true, ...
    'colorbar_text_color', '#FFFFFF', ...
    'background_color', '#000000', ...
    'ras_triad_default_enabled', false, ...
    'atlas_edge_alpha', 0.15, ...
    'anatomy_colormap', 'grayscale_truecolor', ...
    'anatomy_atlas_raster_dpi', resolution, ...
    'font_name', 'Arial');
manifest.anatomy = struct( ...
    'source', fiberStyle.AnatomyNifti, ...
    'plane', fiberStyle.AnatomySlicePlane, ...
    'coordinate_mm', fiberStyle.AnatomySliceCoordinateMm, ...
    'transparency_percent', ...
        fiberStyle.AnatomySliceTransparencyPercent, ...
    'face_alpha', fiberStyle.AnatomySliceTransparencyPercent / 100, ...
    'included_in_export', true);
manifest.configured_output_count = expectedExportCount;
manifest.roles = roleRecords;
manifest.outputs = outputRecords;
local_write_json(fullfile(stageDirectory, 'export_manifest.json'), manifest);

[published, message] = movefile(stageDirectory, outputDirectory);
if ~published
    error([mfilename, ':PublishFailed'], ...
        'Could not publish the staged export: %s', message);
end
for index = 1:numel(exports)
    [~, name, extension] = fileparts(exports(index).pdf_path);
    exports(index).pdf_path = fullfile(outputDirectory, [name, extension]);
end
end

function expected = local_expected_export_count(views, roles)
expected = 0;
for index = 1:numel(roles)
    role = roles{index};
    if ~isfield(views, role) || ~iscell(views.(role)) || ...
            isempty(views.(role))
        error([mfilename, ':MissingRoleViews'], ...
            'Views.%s must be a nonempty cell array.', role);
    end
    expected = expected + numel(views.(role));
end
end

function local_assert_coefficient_scene( ...
        scene, prepared, fiberStyle, colorbarLabel, role)
if ~isfield(scene.objects, 'fiberCoefficientMetadata')
    error([mfilename, ':MissingMetadata'], ...
        'The %s scene lacks coefficient fiber metadata.', role);
end
metadata = scene.objects.fiberCoefficientMetadata;
if metadata.candidate_fiber_count ~= prepared.details.candidate_fiber_count || ...
        metadata.rendered_fiber_count ~= metadata.candidate_fiber_count
    error([mfilename, ':IncompleteCandidateRender'], ...
        'The %s scene did not render every candidate fiber.', role);
end
handle = scene.objects.fiberCoefficient;
if ~isgraphics(handle, 'patch') || ...
        size(get(handle, 'Faces'), 2) ~= 2 || ...
        ~strcmpi(get(handle, 'FaceColor'), 'none') || ...
        ~strcmpi(get(handle, 'EdgeColor'), 'flat') || ...
        abs(double(get(handle, 'EdgeAlpha')) - ...
        fiberStyle.CoefficientFiberAlpha) > 1e-12 || ...
        abs(double(get(handle, 'LineWidth')) - ...
        fiberStyle.CoefficientFiberLineWidth) > 1e-12
    error([mfilename, ':FiberStyleMismatch'], ...
        'The %s coefficient path does not match the formal style.', role);
end
if ~isempty(findall(scene.figure, ...
        'Type', 'Legend', 'Tag', 'mh_viz_fiber_legend'))
    error([mfilename, ':UnexpectedCountLegend'], ...
        'The %s coefficient scene must not contain a count legend.', role);
end
colorbarHandle = scene.objects.colorbar;
if ~isgraphics(colorbarHandle, 'colorbar') || ...
        ~strcmp(char(string(colorbarHandle.Label.String)), colorbarLabel) || ...
        ~isequal(double(colorbarHandle.Color), ...
        fiberStyle.FiberColorbarTextColor) || ...
        ~isequal(double(colorbarHandle.Label.Color), ...
        fiberStyle.FiberColorbarTextColor) || ...
        any(abs(double(colorbarHandle.Limits) - ...
        [-metadata.score_color_limit, metadata.score_color_limit]) > 1e-12)
    error([mfilename, ':ColorbarMismatch'], ...
        'The %s coefficient colorbar does not match the model range.', role);
end
if ~isempty(findall(scene.figure, ...
        'Type', 'axes', 'Tag', 'EA_RAS_TRIAD_AXES'))
    error([mfilename, ':UnexpectedRasTriad'], ...
        'The %s default coefficient export must omit the RAS triad.', role);
end
end

function local_assert_hidden(figures)
figures = figures(isgraphics(figures, 'figure'));
if isempty(figures)
    error([mfilename, ':MissingFigure'], ...
        'Scene construction did not create a MATLAB figure.');
end
for index = 1:numel(figures)
    if strcmpi(get(figures(index), 'Visible'), 'on')
        error([mfilename, ':VisibleFigure'], ...
            'Strict-headless export created a visible MATLAB figure.');
    end
end
end

function digest = local_file_sha256(pathValue)
command = sprintf('/usr/bin/shasum -a 256 %s', ...
    mh_fiber_shell_quote(char(string(pathValue))));
[status, output] = system(command);
if status ~= 0
    error([mfilename, ':HashFailed'], ...
        'Could not compute SHA-256 for %s: %s', pathValue, output);
end
token = regexp(strtrim(output), '^[0-9a-f]{64}', 'match', 'once');
if isempty(token)
    error([mfilename, ':BadHashOutput'], ...
        'Could not parse SHA-256 output for %s.', pathValue);
end
digest = token;
end

function local_write_json(pathValue, payload)
encoded = jsonencode(payload, 'PrettyPrint', true);
fileId = fopen(pathValue, 'w');
if fileId < 0
    error([mfilename, ':ManifestOpenFailed'], ...
        'Could not open export manifest for writing: %s', pathValue);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', encoded);
clear cleanup;
end

function local_delete_figures(figures)
figures = figures(isgraphics(figures, 'figure'));
for index = 1:numel(figures)
    delete(figures(index));
end
end
