function parser = mh_fiber_stnsnr_add_vta_parser_params(parser)
% Add shared STN/SNr VTA model, atlas, and execution parser parameters.

executionDefaults = mh_vta_default_execution_options();
parser.addParameter('VtaGmAtlas', mh_fiber_stnsnr_default_vta_gm_atlas(), ...
    @(x) ischar(x) || isstring(x));
parser.addParameter('VtaModelKey', mh_fiber_stnsnr_default_vta_model_key(), ...
    @(x) ischar(x) || isstring(x));
parser.addParameter('VtaExecutionMode', executionDefaults.executionMode, ...
    @(x) ischar(x) || isstring(x));
parser.addParameter('VtaParallelWorkers', executionDefaults.parallelWorkers, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
parser.addParameter('VtaMatlabExe', executionDefaults.matlabExe, ...
    @(x) ischar(x) || isstring(x));
parser.addParameter('VtaCondaEnv', executionDefaults.condaEnv, ...
    @(x) ischar(x) || isstring(x));
parser.addParameter('VtaProcessWorkDir', executionDefaults.processWorkDir, ...
    @(x) ischar(x) || isstring(x));
parser.addParameter('VtaProcessDryRun', executionDefaults.processDryRun, ...
    @(x) islogical(x) || isnumeric(x));
parser.addParameter('VtaProcessPollSeconds', executionDefaults.processPollSeconds, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
parser.addParameter('VtaProcessTimeoutSeconds', executionDefaults.processTimeoutSeconds, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0);
end
