function stimSpec = mh_fiber_stnsnr_stimspec_from_table(rows, label)
% Build an STN/SNr stimulation spec from workbook-style or normalized rows.

if ~istable(rows)
    error('mh_fiber_stnsnr_stimspec_from_table:InvalidRows', ...
        'STN/SNr stimulation rows must be a table.');
end

columns = { ...
    select_column(rows, {'Side', 'side'}, 'side'), ...
    select_column(rows, {'LeadContact', 'lead_contact', 'leadContact'}, 'lead contact'), ...
    select_column(rows, {'Voltage', 'voltage'}, 'voltage'), ...
    select_column(rows, {'PulseWidth', 'pulse_width', 'pulseWidth'}, 'pulse width'), ...
    select_column(rows, {'Frequency', 'frequency'}, 'frequency')};

stimSpec = mh_fiber_stimspec_from_table(rows(:, columns), 'case', ...
    'Label', label, ...
    'Model', 'simbio', ...
    'Space', 'native_and_mni', ...
    'Unit', 'V');
end

function column = select_column(rows, candidates, description)
names = string(rows.Properties.VariableNames);
for i = 1:numel(candidates)
    candidate = string(candidates{i});
    if any(names == candidate)
        column = char(candidate);
        return;
    end
end
error('mh_fiber_stnsnr_stimspec_from_table:MissingColumn', ...
    'STN/SNr stimulation rows are missing the %s column.', description);
end
