% Validate strict YAML configuration for the generic BIDS DWI runner.

repoDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(repoDir));

testDir = tempname;
mkdir(testDir);
cleanupObj = onCleanup(@() rmdir(testDir, 's'));

configPath = fullfile(testDir, 'valid.yaml');
write_text(configPath, complete_yaml('auto', ''));
[config, source] = mh_fiber_dwi_load_config(configPath, struct());

assert(config.schema_version == 1, 'Schema version should be one.');
assert(strcmp(config.project.name, 'test_project'), 'Project name was not loaded.');
assert(strcmp(config.project.study_root, '/tmp/test_project'), 'Study root was not loaded.');
assert(strcmp(config.project.session, 'research'), 'Session was not loaded.');
assert(strcmp(config.subjects.mode, 'auto'), 'Subject mode was not loaded.');
assert(~isfield(config.subjects, 'ids'), 'Auto mode should not retain subject IDs.');
assert(isequal(config.dwi.phase_encoding_vector, [0 1 0]), ...
    'Phase-encoding vector was not normalized.');
assert(strcmp(config.dwi.b0_reference.strategy, 'last'), ...
    'Configured b0 reference strategy was not loaded.');
assert(config.dwi.b0_reference.threshold == 10, ...
    'Configured b0 threshold was not loaded.');
assert(config.execution.parallel_workers == 2, 'Parallel worker count was not loaded.');
assert(config.execution.parallel, 'Boolean YAML values were not normalized.');
assert(strcmp(source.path, configPath), 'Configuration source path was not recorded.');

minimalPath = fullfile(testDir, 'minimal.yaml');
write_text(minimalPath, minimal_yaml());
minimal = mh_fiber_dwi_load_config(minimalPath, struct());
assert(strcmp(minimal.project.session, 'preop'), 'Missing session should use the default.');
assert(strcmp(minimal.dwi.distortion_correction, 'synb0'), ...
    'Missing distortion correction should use the default.');
assert(strcmp(minimal.dwi.b0_reference.strategy, 'mean'), ...
    'Missing b0 reference strategy should retain the compatibility default.');
assert(~minimal.execution.parallel, 'Missing parallel setting should use the default.');
assert(minimal.execution.max_concurrent_synb0 == 1, ...
    'Missing Synb0 concurrency should use the default.');

explicitPath = fullfile(testDir, 'explicit.yaml');
write_text(explicitPath, complete_yaml('explicit', sprintf('  ids:\n    - Subject001\n    - Subject002\n')));
explicit = mh_fiber_dwi_load_config(explicitPath, struct());
assert(isequal(explicit.subjects.ids, {'Subject001', 'Subject002'}), ...
    'Explicit subject IDs were not normalized to a row cell array.');

overrides = struct();
overrides.project = struct('study_root', '/runtime/project');
overrides.subjects = struct('mode', 'explicit', 'ids', {{'Runtime001'}});
overrides.execution = struct('force', true, 'parallel_workers', 3);
resolved = mh_fiber_dwi_load_config(configPath, overrides);
assert(strcmp(resolved.project.study_root, '/runtime/project'), ...
    'Runtime study root should override YAML.');
assert(isequal(resolved.subjects.ids, {'Runtime001'}), ...
    'Runtime subjects should override YAML subject selection.');
assert(resolved.execution.force && resolved.execution.parallel_workers == 3, ...
    'Runtime execution options should override YAML.');

compatOverrides = struct();
compatOverrides.project = struct('name', 'compat', 'study_root', '/tmp/compat');
compatOverrides.subjects = struct('mode', 'auto');
compat = mh_fiber_dwi_load_config('', compatOverrides);
assert(strcmp(compat.project.session, 'preop'), ...
    'Name-value compatibility should receive internal defaults.');

assert_config_error(testDir, 'unknown_top.yaml', ...
    [minimal_yaml(), sprintf('unexpected: value\n')], ...
    'mh_fiber_dwi_load_config:UnknownField');
assert_config_error(testDir, 'unknown_nested.yaml', ...
    strrep(minimal_yaml(), '  mode: auto', sprintf('  mode: auto\n  unexpected: value')), ...
    'mh_fiber_dwi_load_config:UnknownField');
assert_config_error(testDir, 'schema.yaml', ...
    strrep(minimal_yaml(), 'schema_version: 1', 'schema_version: 2'), ...
    'mh_fiber_dwi_load_config:UnsupportedSchemaVersion');
assert_config_error(testDir, 'explicit_empty.yaml', ...
    strrep(minimal_yaml(), 'mode: auto', 'mode: explicit'), ...
    'mh_fiber_dwi_load_config:InvalidSubjects');
assert_config_error(testDir, 'auto_ids.yaml', ...
    strrep(minimal_yaml(), '  mode: auto', sprintf('  mode: auto\n  ids:\n    - Subject001')), ...
    'mh_fiber_dwi_load_config:InvalidSubjects');
assert_config_error(testDir, 'prefixed_subject.yaml', ...
    strrep(minimal_yaml(), '  mode: auto', sprintf('  mode: explicit\n  ids:\n    - sub-Subject001')), ...
    'mh_fiber_dwi_load_config:InvalidSubjectId');
assert_config_error(testDir, 'invalid_subject_mode.yaml', ...
    strrep(minimal_yaml(), 'mode: auto', 'mode: all'), ...
    'mh_fiber_dwi_load_config:InvalidSubjects');
assert_config_error(testDir, 'invalid_phase_encoding.yaml', ...
    strrep(complete_yaml('auto', ''), '[0, 1, 0]', '[1, 1, 0]'), ...
    'mh_fiber_dwi_load_config:InvalidPhaseEncodingVector');
assert_config_error(testDir, 'invalid_readout.yaml', ...
    strrep(complete_yaml('auto', ''), 'seconds: 0.05', 'seconds: 0'), ...
    'mh_fiber_dwi_load_config:InvalidReadoutTime');
assert_config_error(testDir, 'invalid_b0_strategy.yaml', ...
    strrep(complete_yaml('auto', ''), 'strategy: last', 'strategy: first'), ...
    'mh_fiber_dwi_load_config:InvalidEnum');
assert_config_error(testDir, 'invalid_b0_threshold.yaml', ...
    strrep(complete_yaml('auto', ''), 'threshold: 10', 'threshold: 0'), ...
    'mh_fiber_dwi_load_config:InvalidB0Threshold');
assert_config_error(testDir, 'invalid_distortion.yaml', ...
    strrep(complete_yaml('auto', ''), 'distortion_correction: synb0', ...
    'distortion_correction: unknown'), ...
    'mh_fiber_dwi_load_config:InvalidEnum');
assert_config_error(testDir, 'invalid_boolean.yaml', ...
    strrep(complete_yaml('auto', ''), 'parallel: true', 'parallel: sometimes'), ...
    'mh_fiber_dwi_load_config:InvalidType');
assert_config_error(testDir, 'invalid_workers.yaml', ...
    strrep(complete_yaml('auto', ''), 'parallel_workers: 2', 'parallel_workers: two'), ...
    'mh_fiber_dwi_load_config:InvalidType');

fprintf('BIDS DWI YAML configuration test passed.\n');

function assert_config_error(testDir, fileName, content, expectedId)
path = fullfile(testDir, fileName);
write_text(path, content);
try
    mh_fiber_dwi_load_config(path, struct());
    error('test_bids_dwi_config:ExpectedError', ...
        'Expected configuration error %s for %s.', expectedId, fileName);
catch ME
    assert(strcmp(ME.identifier, expectedId), ...
        'Expected %s for %s, received %s: %s', ...
        expectedId, fileName, ME.identifier, ME.message);
end
end

function text = minimal_yaml()
text = sprintf([ ...
    'schema_version: 1\n', ...
    'project:\n', ...
    '  name: test_project\n', ...
    '  study_root: /tmp/test_project\n', ...
    'subjects:\n', ...
    '  mode: auto\n']);
end

function text = complete_yaml(subjectMode, subjectLines)
text = sprintf([ ...
    'schema_version: 1\n', ...
    'project:\n', ...
    '  name: test_project\n', ...
    '  study_root: /tmp/test_project\n', ...
    '  session: research\n', ...
    'subjects:\n', ...
    '  mode: %s\n', ...
    '%s', ...
    'dwi:\n', ...
    '  distortion_correction: synb0\n', ...
    '  phase_encoding_vector: [0, 1, 0]\n', ...
    '  b0_reference:\n', ...
    '    strategy: last\n', ...
    '    threshold: 10\n', ...
    '  total_readout_time:\n', ...
    '    strategy: json_then_fallback\n', ...
    '    seconds: 0.05\n', ...
    'anatomy:\n', ...
    '  synb0_modality: T1w\n', ...
    '  coregistration_anchor: T2w\n', ...
    '  allow_anchor_fallback: false\n', ...
    'lead_dbs:\n', ...
    '  run_coregistration: false\n', ...
    '  coregistration_method: SPM\n', ...
    'processing:\n', ...
    '  generate_optional_dwi_qc: true\n', ...
    'execution:\n', ...
    '  force: false\n', ...
    '  parallel: true\n', ...
    '  parallel_workers: 2\n', ...
    '  max_concurrent_synb0: 1\n', ...
    '  synb0_min_memory_gb: 12\n', ...
    'runtime:\n', ...
    '  freesurfer_license: /tmp/license.txt\n', ...
    '  synb0:\n', ...
    '    container_engine: auto\n', ...
    '    container_image: leonyichencai/synb0-disco:v3.1\n', ...
    '    work_root: /tmp/synb0_work\n'], subjectMode, subjectLines);
end

function write_text(path, content)
fid = fopen(path, 'w');
assert(fid >= 0, 'Could not create test YAML: %s', path);
cleanupObj = onCleanup(@() fclose(fid));
fprintf(fid, '%s', content);
end
