% Validate immutable versioned run records for BIDS DWI execution modes.

repoDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(repoDir));

workDir = tempname;
mkdir(workDir);
cleanupObj = onCleanup(@() mh_fiber_cleanup_temp_dir(workDir));
studyRoot = fullfile(workDir, 'study');
mh_util_make_dir(studyRoot);

sourcePath = fullfile(workDir, 'source.yaml');
write_text(sourcePath, sprintf([ ...
    'schema_version: 1\n', ...
    'project:\n', ...
    '  name: record_test\n', ...
    '  study_root: %s\n', ...
    'subjects:\n', ...
    '  mode: auto\n'], studyRoot));
[config, source] = mh_fiber_dwi_load_config(sourcePath, struct());

manifest = table( ...
    {'Subject001'; 'Subject002'}, ...
    {'preop'; 'preop'}, ...
    {'/tmp/raw1.nii'; '/tmp/raw2.nii'}, ...
    'VariableNames', {'subject', 'session', 'raw_dwi'});
status = table( ...
    {'Subject001'; 'Subject002'}, ...
    {'validated'; 'validated'}, ...
    {'ok'; 'ok'}, ...
    'VariableNames', {'subject', 'status', 'message'});

record1 = mh_fiber_dwi_run_records('start', source, config, manifest, 'validate');
assert(isfolder(record1.runDir), 'Start should create a versioned run directory.');
assert(isfile(fullfile(record1.runDir, 'config_source.yaml')), ...
    'Run directory should contain the source YAML.');
assert(strcmp(fileread(fullfile(record1.runDir, 'config_source.yaml')), ...
    fileread(sourcePath)), 'Source YAML should be preserved exactly.');
assert(isfile(fullfile(record1.runDir, 'config_resolved.json')), ...
    'Run directory should contain resolved JSON.');
assert(isfile(fullfile(record1.runDir, 'job_manifest.csv')), ...
    'Run directory should contain the job manifest.');

record1 = mh_fiber_dwi_run_records('finish', record1, status);
assert(isfile(record1.statusPath), 'Finish should write status.csv.');
assert(isfile(fullfile(record1.subjectsDir, ...
    'Subject001_dwi_preprocessing_qc.json')), ...
    'Finish should write a per-subject JSON record.');
assert(isfile(fullfile(record1.subjectsDir, ...
    'Subject002_dwi_preprocessing_qc.json')), ...
    'Finish should write every selected subject record.');
savedStatus = readtable(record1.statusPath, 'TextType', 'string');
assert(height(savedStatus) == 2 && all(savedStatus.status == "validated"), ...
    'Saved status should preserve all subject states.');

record2 = mh_fiber_dwi_run_records('start', source, config, manifest, 'validate');
assert(~strcmp(record1.runId, record2.runId), ...
    'Repeated invocations must receive unique run IDs.');
assert(~strcmp(record1.runDir, record2.runDir), ...
    'Repeated invocations must not overwrite an earlier run directory.');

generatedSource = struct('path', '', 'provided', false);
record3 = mh_fiber_dwi_run_records('start', generatedSource, config, manifest, 'plan');
generatedText = fileread(fullfile(record3.runDir, 'config_source.yaml'));
assert(contains(generatedText, 'schema_version: 1'), ...
    'Compatibility runs should serialize a valid source YAML snapshot.');
assert(contains(generatedText, 'mode: auto'), ...
    'Generated source YAML should preserve subject selection.');

expectedRoot = fullfile(studyRoot, 'derivatives', 'leaddbs', ...
    'import_logs', 'dwi_runs');
assert(startsWith(record1.runDir, expectedRoot), ...
    'Run records should live under the Lead-DBS import log tree.');

fprintf('BIDS DWI versioned run-record test passed.\n');

function write_text(path, content)
fid = fopen(path, 'w');
assert(fid >= 0, 'Could not create test file: %s', path);
cleanupObj = onCleanup(@() fclose(fid));
fprintf(fid, '%s', content);
end
