% Validate public validate, plan, run, and compatibility runner modes.

repoDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(repoDir));

workDir = tempname;
mkdir(workDir);
cleanupObj = onCleanup(@() mh_fiber_cleanup_temp_dir(workDir));
studyRoot = fullfile(workDir, 'study');
session = 'research';
create_subject(studyRoot, 'Subject001', session);
create_subject(studyRoot, 'Subject002', session);

configPath = fullfile(workDir, 'project.yaml');
write_text(configPath, project_yaml(studyRoot, session));

validated = run_bids_dwi_preprocessing( ...
    'Config', configPath, ...
    'Mode', 'validate');
assert(strcmp(validated.mode, 'validate'), 'Runner should report validate mode.');
assert(isequal(validated.subjects, {'Subject001', 'Subject002'}), ...
    'Validate mode should automatically discover both subjects.');
assert(numel(validated.jobSpecs) == 2 && numel(validated.preflight) == 2, ...
    'Validate mode should resolve and preflight every subject.');
assert(isfile(validated.runRecord.statusPath), ...
    'Validate mode should write a versioned status record.');
assert(~isfolder(fullfile(studyRoot, 'derivatives', 'leaddbs', ...
    'sub-Subject001', 'preprocessing', 'dwi')), ...
    'Validate mode must not create image derivative directories.');

planned = run_bids_dwi_preprocessing( ...
    'Config', configPath, ...
    'Mode', 'plan', ...
    'SubjectIds', {'Subject002'});
assert(strcmp(planned.mode, 'plan'), 'Runner should report plan mode.');
assert(isequal(planned.subjects, {'Subject002'}), ...
    'Runtime SubjectIds should override YAML auto discovery.');
assert(height(planned.jobManifest) == 1, ...
    'Plan mode should return one manifest row for the runtime subject.');
assert(strcmp(planned.jobManifest.subject{1}, 'Subject002'), ...
    'Plan manifest should report the runtime-selected subject.');
assert(isfile(planned.runRecord.manifestPath), ...
    'Plan mode should write its resolved job manifest.');
assert(~isfolder(fullfile(studyRoot, 'derivatives', 'leaddbs', ...
    'sub-Subject002', 'preprocessing', 'dwi')), ...
    'Plan mode must not create image derivative directories.');

runResult = run_bids_dwi_preprocessing( ...
    'Config', configPath, ...
    'Mode', 'run', ...
    'SubjectIds', {'Subject001'}, ...
    'Force', true);
assert(strcmp(runResult.mode, 'run'), 'Runner should report run mode.');
assert(height(runResult.summary) == 1, 'Run mode should process one selected subject.');
assert(strcmp(runResult.summary.subject{1}, 'Subject001'), ...
    'Run mode should dispatch only the runtime-selected subject.');
assert(strcmp(runResult.summary.status{1}, 'staged'), ...
    'Distortion-correction-none fixture should finish in staged status.');
assert(isfile(runResult.runRecord.statusPath), ...
    'Run mode should write its batch status to a versioned record.');
expectedDwi = fullfile(studyRoot, 'derivatives', 'leaddbs', ...
    'sub-Subject001', 'preprocessing', 'dwi', ...
    'sub-Subject001_ses-research_dwi.nii');
assert(isfile(expectedDwi), 'Run mode should stage the session-aware DWI derivative.');

compatStudyRoot = fullfile(tempdir, 'bids_dwi_project');
compat = run_bids_dwi_preprocessing( ...
    'StudyRoot', compatStudyRoot, ...
    'SubjectIds', {'Subject001'}, ...
    'DryRun', true);
assert(compat.dryRun, 'Legacy DryRun should not launch preprocessing.');
assert(strcmp(compat.config.project.study_root, compatStudyRoot), ...
    'Legacy name-value mode should preserve the explicit study root.');
assert(isequal(compat.config.subjects.ids, {'Subject001'}), ...
    'Legacy name-value mode should preserve explicit subject IDs.');

fprintf('Generic BIDS DWI public runner test passed.\n');

function create_subject(studyRoot, subjectId, session)
patientName = ['sub-', subjectId];
sessionLabel = ['ses-', session];
rawDir = fullfile(studyRoot, 'rawdata', patientName, sessionLabel, 'dwi');
anatDir = fullfile(studyRoot, 'derivatives', 'leaddbs', patientName, ...
    'coregistration', 'anat');
mh_util_make_dir(rawDir);
mh_util_make_dir(anatDir);

sourceBase = [patientName, '_', sessionLabel, '_acq-ax_dwi'];
dwi = reshape(single(1:(2 * 2 * 2 * 2)), [2 2 2 2]);
niftiwrite(dwi, fullfile(rawDir, [sourceBase, '.nii']), 'Compressed', false);
write_text(fullfile(rawDir, [sourceBase, '.json']), ...
    '{"PhaseEncodingDirection":"j","TotalReadoutTime":0.05}');
writematrix([0 1000], fullfile(rawDir, [sourceBase, '.bval']), ...
    'FileType', 'text', 'Delimiter', ' ');
writematrix([0 1; 0 0; 0 0], fullfile(rawDir, [sourceBase, '.bvec']), ...
    'FileType', 'text', 'Delimiter', ' ');

anat = single(ones(2, 2, 2));
niftiwrite(anat, fullfile(anatDir, [patientName, '_', sessionLabel, ...
    '_space-anchorNative_desc-preproc_acq-iso_T1w.nii']), 'Compressed', false);
niftiwrite(anat, fullfile(anatDir, [patientName, '_', sessionLabel, ...
    '_space-anchorNative_desc-preproc_acq-iso_T2w.nii']), 'Compressed', false);
end

function text = project_yaml(studyRoot, session)
text = sprintf([ ...
    'schema_version: 1\n', ...
    'project:\n', ...
    '  name: runner_test\n', ...
    '  study_root: %s\n', ...
    '  session: %s\n', ...
    'subjects:\n', ...
    '  mode: auto\n', ...
    'dwi:\n', ...
    '  distortion_correction: none\n', ...
    'anatomy:\n', ...
    '  coregistration_anchor: T2w\n', ...
    'lead_dbs:\n', ...
    '  run_coregistration: false\n', ...
    'processing:\n', ...
    '  generate_optional_dwi_qc: false\n'], studyRoot, session);
end

function write_text(path, content)
fid = fopen(path, 'w');
assert(fid >= 0, 'Could not create test file: %s', path);
cleanupObj = onCleanup(@() fclose(fid));
fprintf(fid, '%s', content);
end
