% Validate project presets and thin compatibility wrappers.

repoDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(repoDir));

meigePath = fullfile(repoDir, 'my_helper', 'stnvop', 'config', 'dwi.yaml');
stnsnrPath = fullfile(repoDir, 'my_helper', 'stnsnr', 'config', 'dwi.yaml');

meige = mh_fiber_dwi_load_config(meigePath, struct());
assert(strcmp(meige.project.study_root, '/Volumes/VAL/meige'), ...
    'Meige preset should select the Meige study root.');
assert(strcmp(meige.subjects.mode, 'auto'), ...
    'Meige preset should use standard BIDS subject discovery.');
assert(isequal(meige.dwi.phase_encoding_vector, [0 1 0]), ...
    'Meige preset should retain the accepted phase-encoding vector.');
assert(meige.dwi.total_readout_time.seconds == 0.05, ...
    'Meige preset should retain the accepted readout fallback.');

stnsnr = mh_fiber_dwi_load_config(stnsnrPath, struct());
assert(strcmp(stnsnr.project.study_root, '/Volumes/VAL/STNSNr'), ...
    'STN/SNr preset should select the STN/SNr study root.');
assert(strcmp(stnsnr.subjects.mode, 'auto'), ...
    'STN/SNr preset should use standard BIDS subject discovery.');
assert(strcmp(stnsnr.anatomy.coregistration_anchor, 'T2w'), ...
    'STN/SNr preset should retain its T2w coregistration anchor.');

wrapperPath = fullfile(repoDir, 'my_helper', 'fiber', 'stnsnr', ...
    'run_stnsnr_dwi_registration.m');
wrapperText = fileread(wrapperPath);
required = { ...
    'run_bids_dwi_preprocessing(', ...
    'config', ...
    '''stnsnr''', ...
    '''dwi.yaml'''};
for i = 1:numel(required)
    assert(contains(lower(wrapperText), lower(required{i})), ...
        'STN/SNr wrapper is missing generic preset snippet: %s', required{i});
end
forbidden = { ...
    'run_project_dwi_fake_b0_coreg(', ...
    'importLog', ...
    'switch runMode', ...
    'PilotSubject'};
for i = 1:numel(forbidden)
    assert(~contains(wrapperText, forbidden{i}), ...
        'STN/SNr wrapper should not retain project orchestration: %s', forbidden{i});
end

genericText = fileread(fullfile(repoDir, 'my_helper', 'dwi', ...
    'run_bids_dwi_preprocessing.m'));
forbiddenGeneric = {'/Volumes/VAL/meige', 'Meige001', 'Dys022', 'cohort_subjects'};
for i = 1:numel(forbiddenGeneric)
    assert(~contains(genericText, forbiddenGeneric{i}), ...
        'Generic runner contains project-specific content: %s', forbiddenGeneric{i});
end
assert(~isfile(fullfile(repoDir, 'my_helper', 'dwi', 'config', 'meige.yaml')), ...
    'Project-named presets must not live under the generic DWI module.');
assert(~isfile(fullfile(repoDir, 'my_helper', 'dwi', 'config', 'stnvop.yaml')), ...
    'STNVOP-named presets must not live under the generic DWI module.');

fprintf('BIDS DWI project preset test passed.\n');
