% Validate the project-agnostic BIDS/Lead-DBS DWI wrapper configuration.

repoDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(repoDir));

studyRoot = fullfile(tempdir, 'bids_dwi_project');

explicit = run_bids_dwi_preprocessing( ...
    'StudyRoot', studyRoot, ...
    'SubjectIds', {'Subject001'}, ...
    'DryRun', true);

assert(explicit.dryRun, 'DryRun should not launch preprocessing.');
assert(strcmp(explicit.studyRoot, studyRoot), ...
    'The wrapper should preserve the explicit study root.');
assert(isequal(explicit.subjects, {'Subject001'}), ...
    'The wrapper should preserve explicit subject IDs.');
assert(strcmp(explicit.subjectSelection, 'explicit'), ...
    'A nonempty SubjectIds list should select explicit subjects.');
assert(strcmp(explicit.coregistrationMethod, 'SPM'), ...
    'The default automatic coregistration method should be SPM.');
assert(~explicit.runCoregistration, ...
    'The default workflow should leave B0 coregistration to the Lead-DBS UI.');
assert(strcmp(explicit.distortionCorrection, 'synb0'), ...
    'The default distortion correction should be Synb0.');

discovered = run_bids_dwi_preprocessing( ...
    'StudyRoot', studyRoot, ...
    'SubjectIds', {}, ...
    'DryRun', true);

assert(isempty(discovered.subjects), ...
    'An empty SubjectIds list should remain empty for downstream discovery.');
assert(strcmp(discovered.subjectSelection, 'discover'), ...
    'An empty SubjectIds list should request BIDS subject discovery.');

fprintf('Generic BIDS DWI wrapper dry-run test passed.\n');
