% Static regression check for Synb0 archive idempotent reruns.

repoDir = fileparts(fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))));
sourcePath = fullfile(repoDir, 'my_helper', 'fiber', 'core', 'dwi', ...
    'mh_fiber_dwi_distortion_correction.m');
sourceText = fileread(sourcePath);

requiredSnippets = { ...
    'existing_synb0_archive_complete', ...
    'isfolder(archiveDir) && ~force && existing_synb0_archive_complete(archiveDir)', ...
    'b0_u.nii.gz', ...
    'b0_u.nii', ...
    'topup_fieldcoef.nii.gz', ...
    'topup_movpar.txt', ...
    'Synb0 archive already exists'};

for i = 1:numel(requiredSnippets)
    assert(contains(sourceText, requiredSnippets{i}), ...
        'Missing Synb0 archive idempotency snippet: %s', requiredSnippets{i});
end

fprintf('Synb0 archive idempotent reuse static check passed.\n');
