% Static regression check for pseudo-B0 Lead-DBS coregistration target staging.

repoDir = fileparts(fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))));
processPath = fullfile(repoDir, 'my_helper', 'fiber', 'core', 'dwi', ...
    'mh_fiber_process_imported_dwi.m');
jobSpecPath = fullfile(repoDir, 'my_helper', 'fiber', 'core', 'dwi', ...
    'mh_fiber_dwi_bids_jobspec.m');

processText = fileread(processPath);
jobSpecText = fileread(jobSpecPath);

requiredProcessSnippets = { ...
    'row.fake_b0_coreg_target = paths.fakeB0Coreg;', ...
    'stage_fake_b0_coreg_target(dcResult.b0, paths.fakeB0Coreg, opts.Force);', ...
    'function stage_fake_b0_coreg_target(sourceB0, targetB0, force)', ...
    'copyfile(sourceB0, targetB0, ''f'');', ...
    'write_subject_json(metadata, sidecar_json_path(paths.fakeB0Coreg));', ...
    'metadata.FakeCoregisterVolume = true;', ...
    'metadata.IntendedUse = ''coregistration_qc_only'';', ...
    'metadata.ExcludeFromNormalization = true;'};

for i = 1:numel(requiredProcessSnippets)
    assert(contains(processText, requiredProcessSnippets{i}), ...
        'Missing pseudo-B0 staging snippet: %s', requiredProcessSnippets{i});
end

requiredJobSpecSnippets = { ...
    'paths.coregAnatDir = fullfile(subjectDir, ''coregistration'', ''anat'');', ...
    'paths.fakeB0Coreg = fullfile(paths.coregAnatDir', ...
    '[patientName, ''_ses-preop_space-anchorNative_desc-preproc_B0.nii'']'};

for i = 1:numel(requiredJobSpecSnippets)
    assert(contains(jobSpecText, requiredJobSpecSnippets{i}), ...
        'Missing pseudo-B0 job spec snippet: %s', requiredJobSpecSnippets{i});
end

fprintf('Pseudo-B0 coregistration target staging static check passed.\n');
