% Validate image-content DWI orientation correction and bvec synchronization.

repoDir = fileparts(fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))));
addpath(genpath(repoDir));

workDir = tempname;
mkdir(workDir);
cleanupObj = onCleanup(@() mh_fiber_cleanup_temp_dir(workDir));

sourceData = reshape(single(1:(2 * 3 * 4 * 2)), [2 3 4 2]);
sourceNii = fullfile(workDir, 'source.nii');
niftiwrite(sourceData, sourceNii, 'Compressed', false);
gzip(sourceNii);
sourceNiiGz = [sourceNii, '.gz'];

sourceJson = fullfile(workDir, 'source.json');
fid = fopen(sourceJson, 'w');
assert(fid > 0, 'Could not create source JSON.');
fprintf(fid, '{"ExistingField":"kept"}');
fclose(fid);

sourceBval = fullfile(workDir, 'source.bval');
writematrix([0 1000], sourceBval, 'FileType', 'text', 'Delimiter', ' ');

sourceBvec = fullfile(workDir, 'source.bvec');
sourceBvecMatrix = [0 1; 0 2; 0 3];
writematrix(sourceBvecMatrix, sourceBvec, 'FileType', 'text', 'Delimiter', ' ');

outputDir = fullfile(workDir, 'out');
result = mh_fiber_reorient_dwi_image_content( ...
    'SourceNifti', sourceNiiGz, ...
    'SourceJson', sourceJson, ...
    'SourceBval', sourceBval, ...
    'SourceBvec', sourceBvec, ...
    'OutputDir', outputDir, ...
    'OutputBase', 'sub-Test_ses-preop_dwi', ...
    'Transform', 'rotX180', ...
    'Force', true);

assert(isfile(result.Nifti), 'Corrected NIfTI was not written.');
assert(isfile(result.Json), 'Corrected JSON was not written.');
assert(isfile(result.Bval), 'Corrected bval was not written.');
assert(isfile(result.Bvec), 'Corrected bvec was not written.');

correctedData = niftiread(result.Nifti);
expectedData = flip(flip(sourceData, 2), 3);
assert(isequal(correctedData, expectedData), ...
    'rotX180 did not flip voxel dimensions 2 and 3.');

correctedBvec = readmatrix(result.Bvec, 'FileType', 'text');
expectedBvec = [0 1; 0 -2; 0 -3];
assert(isequal(size(correctedBvec), size(expectedBvec)), ...
    'Corrected bvec size changed unexpectedly.');
assert(max(abs(correctedBvec(:) - expectedBvec(:))) < 1e-12, ...
    'rotX180 did not apply diag([1 -1 -1]) to bvec.');

correctedBval = readmatrix(result.Bval, 'FileType', 'text');
assert(isequal(correctedBval(:)', [0 1000]), 'bval changed unexpectedly.');

metadata = jsondecode(fileread(result.Json));
assert(isfield(metadata, 'ExistingField'), 'Existing JSON fields were not preserved.');
assert(metadata.ImageContentOrientationCorrection, ...
    'JSON does not record ImageContentOrientationCorrection=true.');
assert(strcmp(metadata.OrientationCorrectionTransform, 'rotX180'), ...
    'JSON does not record the transform name.');
assert(isequal(metadata.OrientationCorrectionBvecMatrix, [1 0 0; 0 -1 0; 0 0 -1]), ...
    'JSON does not record the bvec transform matrix.');

fprintf('DWI image-content orientation correction test passed.\n');

incrementalWorkDir = fullfile(workDir, 'incremental');
mkdir(incrementalWorkDir);

incrementalNii = fullfile(incrementalWorkDir, 'current.nii');
niftiwrite(sourceData, incrementalNii, 'Compressed', false);
gzip(incrementalNii);
incrementalNiiGz = [incrementalNii, '.gz'];

incrementalJson = fullfile(incrementalWorkDir, 'current.json');
metadata = struct();
metadata.ImageContentOrientationCorrection = true;
metadata.OrientationCorrectionTransform = 'rotX180';
metadata.OrientationCorrectionBvecMatrix = [1 0 0; 0 -1 0; 0 0 -1];
fid = fopen(incrementalJson, 'w');
assert(fid > 0, 'Could not create incremental source JSON.');
fprintf(fid, '%s\n', jsonencode(metadata));
fclose(fid);

incrementalBval = fullfile(incrementalWorkDir, 'current.bval');
writematrix([0 1000], incrementalBval, 'FileType', 'text', 'Delimiter', ' ');

incrementalBvec = fullfile(incrementalWorkDir, 'current.bvec');
writematrix(expectedBvec, incrementalBvec, 'FileType', 'text', 'Delimiter', ' ');

blocked = false;
try
    mh_fiber_reorient_dwi_image_content( ...
        'SourceNifti', incrementalNiiGz, ...
        'SourceJson', incrementalJson, ...
        'SourceBval', incrementalBval, ...
        'SourceBvec', incrementalBvec, ...
        'OutputDir', fullfile(incrementalWorkDir, 'blocked'), ...
        'OutputBase', 'sub-Test_ses-preop_dwi', ...
        'Transform', 'flipY', ...
        'Force', true);
catch ME
    blocked = strcmp(ME.identifier, ...
        'mh_fiber_reorient_dwi_image_content:AlreadyCorrected');
end
assert(blocked, 'Existing corrections must require AllowIncrementalCorrection=true.');

incrementalResult = mh_fiber_reorient_dwi_image_content( ...
    'SourceNifti', incrementalNiiGz, ...
    'SourceJson', incrementalJson, ...
    'SourceBval', incrementalBval, ...
    'SourceBvec', incrementalBvec, ...
    'OutputDir', fullfile(incrementalWorkDir, 'out'), ...
    'OutputBase', 'sub-Test_ses-preop_dwi', ...
    'Transform', 'flipY', ...
    'AllowIncrementalCorrection', true, ...
    'Force', true);

incrementalData = niftiread(incrementalResult.Nifti);
assert(isequal(incrementalData, flip(sourceData, 2)), ...
    'Incremental flipY did not flip voxel dimension 2.');

incrementalBvecMatrix = readmatrix(incrementalResult.Bvec, 'FileType', 'text');
expectedIncrementalBvec = [0 1; 0 2; 0 -3];
assert(max(abs(incrementalBvecMatrix(:) - expectedIncrementalBvec(:))) < 1e-12, ...
    'Incremental flipY did not update bvec from rotX180 to net flipZ.');

incrementalMetadata = jsondecode(fileread(incrementalResult.Json));
assert(strcmp(incrementalMetadata.OrientationCorrectionPreviousTransform, 'rotX180'), ...
    'Incremental JSON does not record the previous transform.');
assert(strcmp(incrementalMetadata.OrientationCorrectionIncrementalTransform, 'flipY'), ...
    'Incremental JSON does not record the incremental transform.');
assert(strcmp(incrementalMetadata.OrientationCorrectionNetTransform, 'flipZ'), ...
    'Incremental JSON does not record the net transform.');
assert(strcmp(incrementalMetadata.OrientationCorrectionTransform, 'flipZ'), ...
    'Backward-compatible transform field should record the net transform.');
assert(isequal(incrementalMetadata.OrientationCorrectionBvecMatrix, ...
    [1 0 0; 0 1 0; 0 0 -1]), ...
    'Incremental JSON does not record the net bvec matrix.');
assert(strcmp(incrementalMetadata.OrientationCorrectionChainText, ...
    'rotX180 -> flipY => flipZ'), ...
    'Incremental JSON does not record an MRtrix-compatible chain summary.');
assert(~isfield(incrementalMetadata, 'OrientationCorrectionChain'), ...
    'Incremental JSON must not use object arrays that break MRtrix JSON import.');

missingSubjectsBlocked = false;
try
    run_stnsnr_dwi_orientation_qc( ...
        'RepoDir', repoDir, ...
        'SourceRoot', incrementalWorkDir, ...
        'SubjectIds', {}, ...
        'OutputRoot', fullfile(incrementalWorkDir, 'qc'), ...
        'GenerateColorFa', false);
catch ME
    missingSubjectsBlocked = strcmp(ME.identifier, ...
        'run_stnsnr_dwi_orientation_qc:MissingSubjectIds');
end
assert(missingSubjectsBlocked, ...
    'Orientation QC wrapper must require caller-supplied SubjectIds.');

missingApplySubjectsBlocked = false;
try
    run_stnsnr_apply_dwi_orientation_correction( ...
        'RepoDir', repoDir, ...
        'SourceRoot', incrementalWorkDir, ...
        'StudyRoot', incrementalWorkDir, ...
        'SubjectIds', {}, ...
        'LogRoot', fullfile(incrementalWorkDir, 'apply'), ...
        'Transform', 'flipY', ...
        'AllowIncrementalCorrection', true, ...
        'Force', true);
catch ME
    missingApplySubjectsBlocked = strcmp(ME.identifier, ...
        'run_stnsnr_apply_dwi_orientation_correction:MissingSubjectIds');
end
assert(missingApplySubjectsBlocked, ...
    'Apply wrapper must require caller-supplied SubjectIds.');

qcSourceRoot = fullfile(incrementalWorkDir, 'source_root');
qcSubjectId = 'AnonSubject';
qcSubjectDir = fullfile(qcSourceRoot, ['sub-', qcSubjectId]);
mkdir(qcSubjectDir);
qcBase = ['sub-', qcSubjectId, '_ses-preop_dwi'];
copyfile(incrementalNiiGz, fullfile(qcSubjectDir, [qcBase, '.nii.gz']));
copyfile(incrementalJson, fullfile(qcSubjectDir, [qcBase, '.json']));
copyfile(incrementalBval, fullfile(qcSubjectDir, [qcBase, '.bval']));
copyfile(incrementalBvec, fullfile(qcSubjectDir, [qcBase, '.bvec']));

qcStatus = run_stnsnr_dwi_orientation_qc( ...
    'RepoDir', repoDir, ...
    'SourceRoot', qcSourceRoot, ...
    'SubjectIds', {qcSubjectId}, ...
    'TransformCandidates', {'flipY'}, ...
    'AllowIncrementalCorrection', true, ...
    'OutputRoot', fullfile(incrementalWorkDir, 'qc'), ...
    'GenerateColorFa', false, ...
    'Force', true);
assert(strcmp(qcStatus.status{1}, 'ok'), ...
    'QC wrapper should support explicit incremental correction.');

fprintf('Incremental DWI image-content correction test passed.\n');
