% Validate Synb0-DISCO fallback topup support for odd image dimensions.

repoDir = fileparts(fileparts(fileparts(fileparts(fileparts(mfilename('fullpath'))))));
synb0Path = fullfile(repoDir, 'ext_libs', 'synb0', 'ea_synb0.m');

assert(isfile(synb0Path), 'Missing ea_synb0 wrapper: %s', synb0Path);

text = fileread(synb0Path);
requiredSnippets = { ...
    'run_fallback_topup_if_needed', ...
    'write_fallback_topup_config', ...
    '''--subsamp=1,1,1,1,1,1,1''', ...
    'b0_all.nii.gz', ...
    'topup_fieldcoef.nii.gz', ...
    'topup_movpar.txt', ...
    '--entrypoint bash', ...
    'FSLOUTPUTTYPE=NIFTI_GZ', ...
    'Synb0-DISCO fallback topup'};

for i = 1:numel(requiredSnippets)
    assert(contains(text, requiredSnippets{i}), ...
        'ea_synb0 is missing fallback topup snippet: %s', requiredSnippets{i});
end

fprintf('Synb0 fallback topup static checks passed.\n');
