% Validate Meige DWI Synb0/eddy fake-B0 wrapper argument construction.

repoDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(repoDir));

pilot = run_meige_dwi_synb0_fakeb0('DryRun', true, 'RunMode', 'pilot');
assert(pilot.dryRun, 'Pilot dry run should not launch preprocessing.');
assert(strcmp(pilot.runMode, 'pilot'), 'Pilot dry run recorded the wrong run mode.');
assert(isequal(pilot.subjects, {'Meige001', 'Meige008', 'Meige021'}), ...
    'Pilot subject list should cover UIH, Philips 24-slice, and Philips 60-slice protocols.');
assert(strcmp(pilot.studyRoot, '/Volumes/VAL/meige'), ...
    'Wrapper should default to the Meige study root.');
assert(strcmp(pilot.freeSurferLicense, '/Applications/freesurfer/8.2.0/license.txt'), ...
    'Wrapper should use the documented FreeSurfer license by default.');
assert(isequal(pilot.phaseEncodingVector, [0 1 0]), ...
    'Wrapper should use the accepted positive j phase-encoding vector.');
assert(abs(pilot.defaultTotalReadoutTime - 0.05) < 1e-12, ...
    'Wrapper should use the accepted Philips fallback readout time.');
assert(strcmp(pilot.coregistrationTag, 'dwi_synb0_fakeb0'), ...
    'Wrapper should use the fake-B0 UI-coreg tag.');
assert(strcmp(pilot.distortionCorrection, 'synb0'), ...
    'Wrapper should request Synb0/eddy distortion correction.');
assert(~pilot.runCoregistration, ...
    'Wrapper should leave b0-to-anchor coregistration for the Lead-DBS UI.');
assert(~pilot.parallel, 'Wrapper should default to serial execution.');
assert(pilot.maxConcurrentSynb0 == 1, ...
    'Wrapper should default to one concurrent Synb0 run.');

cohort = run_meige_dwi_synb0_fakeb0('DryRun', true, 'RunMode', 'cohort');
assert(strcmp(cohort.runMode, 'cohort'), 'Cohort dry run recorded the wrong run mode.');
assert(numel(cohort.subjects) == 22, 'Cohort should include 22 subjects.');
assert(strcmp(cohort.subjects{1}, 'Meige001'), 'Cohort should start with Meige001.');
assert(strcmp(cohort.subjects{21}, 'Meige021'), 'Cohort should include Meige021 before Dys022.');
assert(strcmp(cohort.subjects{22}, 'Dys022'), 'Cohort should include Dys022.');

custom = run_meige_dwi_synb0_fakeb0('DryRun', true, ...
    'SubjectIds', {'Dys022'}, ...
    'Force', true, ...
    'Parallel', true, ...
    'ParallelWorkers', 2, ...
    'MaxConcurrentSynb0', 2);
assert(isequal(custom.subjects, {'Dys022'}), ...
    'Explicit SubjectIds should override the run-mode subject list.');
assert(custom.force, 'Force option should be forwarded into dry-run metadata.');
assert(custom.parallel, 'Parallel option should be forwarded into dry-run metadata.');
assert(custom.parallelWorkers == 2, 'ParallelWorkers should be forwarded.');
assert(custom.maxConcurrentSynb0 == 2, 'MaxConcurrentSynb0 should be forwarded.');

fprintf('Meige DWI Synb0 fake-B0 wrapper dry-run test passed.\n');
