function [headmodelPath, state] = mh_vta_prepare_canonical_headmodel( ...
        S, sideIndex, options, stimulationLabel, expectedContract)
% Build or reuse a canonical native head model with embedded reuse metadata.

validateattributes(sideIndex, {'numeric'}, {'scalar', 'integer', '>=', 1, '<=', 2}, ...
    mfilename, 'sideIndex');
if ~isstruct(options) || ~isfield(options, 'subj') || ...
        ~isfield(options.subj, 'subjDir') || ~isfield(options.subj, 'subjId')
    error('mh_vta_prepare_canonical_headmodel:InvalidOptions', ...
        'options.subj.subjDir and options.subj.subjId are required.');
end
validate_contract(expectedContract);

subjectId = char(string(options.subj.subjId));
subjectId = regexprep(subjectId, '^sub-', '');
headmodelDir = fullfile(char(string(options.subj.subjDir)), 'headmodel', 'native');
headmodelPath = fullfile(headmodelDir, sprintf( ...
    'sub-%s_desc-headmodel%d.mat', subjectId, sideIndex));

if isfile(headmodelPath)
    stored = load(headmodelPath, 'mh_vta_headmodel_contract');
    if ~isfield(stored, 'mh_vta_headmodel_contract') || ...
            ~isequaln(stored.mh_vta_headmodel_contract, expectedContract)
        error('mh_vta_prepare_canonical_headmodel:IncompatibleHeadmodel', ...
            ['Canonical head model is missing a compatible embedded contract. ', ...
             'Move it to a recoverable backup before an explicit rebuild: %s'], ...
            headmodelPath);
    end
    state = 'reused';
    return;
end

if ~isfolder(headmodelDir)
    mkdir(headmodelDir);
end
nativeOptions = options;
nativeOptions.native = 1;
nativeOptions.orignative = 1;
nativeOptions.subj.subjId = subjectId;
nativeOptions.mh_vta_headmodel_only = true;
mh_vta_run_horn_with_retry( ...
    S, sideIndex, nativeOptions, char(string(stimulationLabel)), headmodelPath);
if ~isfile(headmodelPath)
    error('mh_vta_prepare_canonical_headmodel:BuildFailed', ...
        'Head-model preparation did not create the canonical MAT file: %s', ...
        headmodelPath);
end

mh_vta_headmodel_contract = expectedContract;
save(headmodelPath, 'mh_vta_headmodel_contract', '-append');
state = 'built';
end

function validate_contract(contract)
required = { ...
    'subject_id', ...
    'side', ...
    'atlas_set', ...
    'conductivity_s_per_m', ...
    'reconstruction_sha256', ...
    'anchor_sha256', ...
    'implementation_sha256'};
if ~isstruct(contract) || ~isscalar(contract) || ...
        ~all(isfield(contract, required))
    error('mh_vta_prepare_canonical_headmodel:InvalidContract', ...
        'The canonical head-model contract is incomplete.');
end
conductivity = contract.conductivity_s_per_m;
if ~isstruct(conductivity) || ...
        ~all(isfield(conductivity, {'gray_matter', 'white_matter'}))
    error('mh_vta_prepare_canonical_headmodel:InvalidContract', ...
        'The contract must contain gray- and white-matter conductivity.');
end
end
