function cfg = mh_vta_apply_execution_options(cfg, opts)
% Apply task execution options to a VTA configuration struct.

cfg.vta.executionMode = validate_execution_mode(mh_util_get_field(opts, ...
    'VtaExecutionMode', cfg.vta.executionMode));
cfg.vta.parallelWorkers = max(1, round(double(mh_util_get_field(opts, ...
    'VtaParallelWorkers', cfg.vta.parallelWorkers))));
cfg.vta.parallel = ~strcmp(cfg.vta.executionMode, 'sequential') && ...
    cfg.vta.parallelWorkers > 1;
cfg.vta.matlabExe = char(string(mh_util_get_field(opts, ...
    'VtaMatlabExe', cfg.vta.matlabExe)));
cfg.vta.condaEnv = char(string(mh_util_get_field(opts, ...
    'VtaCondaEnv', cfg.vta.condaEnv)));
cfg.vta.processWorkDir = char(string(mh_util_get_field(opts, ...
    'VtaProcessWorkDir', cfg.vta.processWorkDir)));
cfg.vta.processDryRun = logical(mh_util_get_field(opts, ...
    'VtaProcessDryRun', cfg.vta.processDryRun));
cfg.vta.processPollSeconds = max(0.1, double(mh_util_get_field(opts, ...
    'VtaProcessPollSeconds', cfg.vta.processPollSeconds)));
cfg.vta.processTimeoutSeconds = max(0, double(mh_util_get_field(opts, ...
    'VtaProcessTimeoutSeconds', cfg.vta.processTimeoutSeconds)));
end

function mode = validate_execution_mode(value)
mode = lower(char(string(value)));
if ~ismember(mode, {'sequential', 'parpool', 'process'})
    error('mh_vta_apply_execution_options:InvalidExecutionMode', ...
        'Unsupported VTA execution mode: %s', mode);
end
end
