function runtime = mh_vta_create_subject_runtime(subjectId)
% Create one explicit process-local cache owner for a subject worker.

if nargin < 1
    subjectId = '';
end
if ~(ischar(subjectId) || isstring(subjectId) && isscalar(subjectId))
    error('mh_vta:InvalidSubjectRuntime', ...
        'Subject runtime identity must be scalar text.');
end

cacheNames = { ...
    'transform_context', 'subject_context', ...
    'headmodel', 'headmodel_path_key', ...
    'export_geometry', 'native_anchor', 'fem_factorization'};
caches = struct();
for index = 1:numel(cacheNames)
    caches.(cacheNames{index}) = containers.Map( ...
        'KeyType', 'char', 'ValueType', 'any');
end
runtime = struct( ...
    'schema_version', 'vta_subject_runtime_v1', ...
    'subject_id', char(string(subjectId)), ...
    'caches', caches);
end
