% Run STN/SNr cohort VTA coverage analysis.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

executionDefaults = mh_vta_default_execution_options();
vtaGmAtlas = mh_fiber_getenv_default('STNSNR_VTA_GM_ATLAS', ...
    mh_fiber_stnsnr_default_vta_gm_atlas());
vtaModelKey = mh_fiber_getenv_default('STNSNR_VTA_MODEL_KEY', ...
    mh_fiber_stnsnr_default_vta_model_key());
vtaExecutionMode = mh_fiber_getenv_default('STNSNR_VTA_EXECUTION_MODE', ...
    executionDefaults.executionMode);
vtaParallelWorkers = mh_fiber_env_number('STNSNR_VTA_PARALLEL_WORKERS', ...
    executionDefaults.parallelWorkers, ...
    'run_stnsnr_vta_coverage:InvalidEnvNumber');
vtaTaskMatlabExe = mh_fiber_getenv_default('STNSNR_VTA_TASK_MATLAB_EXE', ...
    executionDefaults.matlabExe);
vtaTaskCondaEnv = mh_fiber_getenv_default('STNSNR_VTA_TASK_CONDA_ENV', ...
    executionDefaults.condaEnv);
vtaProcessWorkDir = mh_fiber_getenv_default('STNSNR_VTA_PROCESS_WORK_DIR', ...
    executionDefaults.processWorkDir);
vtaProcessDryRun = mh_fiber_env_flag('STNSNR_VTA_PROCESS_DRY_RUN', ...
    executionDefaults.processDryRun, ...
    'run_stnsnr_vta_coverage:InvalidEnvFlag');
vtaProcessPollSeconds = mh_fiber_env_double('STNSNR_VTA_PROCESS_POLL_SECONDS', ...
    executionDefaults.processPollSeconds, 0.1, ...
    'run_stnsnr_vta_coverage:InvalidEnvNumber');
vtaProcessTimeoutSeconds = mh_fiber_env_double('STNSNR_VTA_PROCESS_TIMEOUT_SECONDS', ...
    executionDefaults.processTimeoutSeconds, 0, ...
    'run_stnsnr_vta_coverage:InvalidEnvNumber');

result = mh_fiber_run_stnsnr_vta_coverage( ...
    'RepoDir', repoDir, ...
    'SubjectRoot', '/Volumes/VAL/STNSNr/derivatives/leaddbs', ...
    'Workbook', '/Users/mojackhu/Research/STNSNr/summary/cohort/subj/followup_stimulation.xlsx', ...
    'Sheet', 'Contact Parameters', ...
    'AtlasDir', fullfile(repoDir, 'templates', 'space', 'MNI152NLin2009bAsym', ...
        'atlases', 'Custom_Ewert_Zhang_Middlebrooks0.05'), ...
    'CohortOutputDir', '/Volumes/VAL/STNSNr/summary/vta', ...
    'ThresholdsVPerMm', [0.18, 0.20, 0.22], ...
    'MainThresholdVPerMm', 0.20, ...
    'OutputVoxelSizeMm', 0.5, ...
    'ForceVta', false, ...
    'ForceOutputs', false, ...
    'StopOnSubjectError', true, ...
    'WriteCohortOutputs', true, ...
    'CohortOnly', false, ...
    'SkipCompletedSubjects', false, ...
    'UseSubjectLocks', true, ...
    'SkipLockedSubjects', false, ...
    'VtaGmAtlas', vtaGmAtlas, ...
    'VtaModelKey', vtaModelKey, ...
    'VtaExecutionMode', vtaExecutionMode, ...
    'VtaParallelWorkers', vtaParallelWorkers, ...
    'VtaMatlabExe', vtaTaskMatlabExe, ...
    'VtaCondaEnv', vtaTaskCondaEnv, ...
    'VtaProcessWorkDir', vtaProcessWorkDir, ...
    'VtaProcessDryRun', vtaProcessDryRun, ...
    'VtaProcessPollSeconds', vtaProcessPollSeconds, ...
    'VtaProcessTimeoutSeconds', vtaProcessTimeoutSeconds);

fprintf('\nSTN/SNr VTA coverage analysis finished.\n');
fprintf('Cohort output directory: %s\n', result.cohortOutputDir);
fprintf('Coverage table: %s\n', result.coverageLongCsv);
fprintf('Contact QC table: %s\n', result.contactQcCsv);
