% Run a small STN/SNr DWI Synb0-DISCO, eddy, and FLIRT BBR pilot.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

pilotSubjects = {'ChenMeiJu'};

result = mh_fiber_register_imported_dwi_batch( ...
    'StudyRoot', '/Volumes/VAL/STNSNr', ...
    'RepoDir', repoDir, ...
    'ImportLog', fullfile('/Volumes/VAL/STNSNr', 'derivatives', 'leaddbs', ...
        'import_logs', 'dwi_import_20260701_013240.csv'), ...
    'SubjectIds', pilotSubjects, ...
    'AnchorModality', 'T2w', ...
    'CoregistrationTag', 'dwi_t2_synb0_flirtbbr', ...
    'CoregistrationMethod', 'FLIRT BBR', ...
    'DistortionCorrection', 'synb0', ...
    'PhaseEncodingVector', [0 1 0], ...
    'DefaultTotalReadoutTime', 0.05, ...
    'AllowT1Fallback', false, ...
    'RunCoregistration', true, ...
    'GenerateOptionalDwiQc', true, ...
    'Force', true);

fprintf('\nFinished STN/SNr DWI Synb0/eddy/FLIRT BBR pilot.\n');
fprintf('Status CSV: %s\n', result.statusCsv);
