% Aggregate completed per-subject STN/SNr VTA coverage outputs.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

subjectRoot = mh_fiber_getenv_default('STNSNR_VTA_SUBJECT_ROOT', ...
    '/Volumes/VAL/STNSNr/derivatives/leaddbs');
workbook = mh_fiber_getenv_default('STNSNR_VTA_WORKBOOK', ...
    '/Users/mojackhu/Research/STNSNr/summary/cohort/subj/followup_stimulation.xlsx');
cohortOutputDir = mh_fiber_getenv_default('STNSNR_VTA_COHORT_OUTPUT_DIR', ...
    '/Volumes/VAL/STNSNr/summary/vta');
vtaGmAtlas = mh_fiber_getenv_default('STNSNR_VTA_GM_ATLAS', ...
    'DISTAL Minimal (Ewert 2017)');

result = mh_fiber_run_stnsnr_vta_coverage( ...
    'RepoDir', repoDir, ...
    'SubjectRoot', subjectRoot, ...
    'Workbook', workbook, ...
    'Sheet', 'Contact Parameters', ...
    'AtlasDir', fullfile(repoDir, 'templates', 'space', 'MNI152NLin2009bAsym', ...
        'atlases', 'Custom_Ewert_Zhang_Middlebrooks0.05'), ...
    'CohortOutputDir', cohortOutputDir, ...
    'ThresholdsVPerMm', [0.18, 0.20, 0.22], ...
    'MainThresholdVPerMm', 0.20, ...
    'OutputVoxelSizeMm', 0.5, ...
    'CohortOnly', true, ...
    'WriteCohortOutputs', true, ...
    'StopOnSubjectError', true, ...
    'VtaGmAtlas', vtaGmAtlas);

fprintf('\nSTN/SNr VTA coverage cohort aggregation finished.\n');
fprintf('Cohort output directory: %s\n', result.cohortOutputDir);
fprintf('Coverage table: %s\n', result.coverageLongCsv);
fprintf('Contact QC table: %s\n', result.contactQcCsv);
