% Register imported STN/SNr cohort DWI scans to Lead-DBS anchorNative T1.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

result = mh_fiber_register_imported_dwi_batch( ...
    'StudyRoot', '/Volumes/VAL/STNSNr', ...
    'RepoDir', repoDir, ...
    'ImportLog', fullfile('/Volumes/VAL/STNSNr', 'derivatives', 'leaddbs', ...
        'import_logs', 'dwi_import_20260701_013240.csv'), ...
    'RunCoregistration', true, ...
    'GenerateOptionalDwiQc', true, ...
    'Force', false);

fprintf('\nFinished STN/SNr DWI registration batch.\n');
fprintf('Status CSV: %s\n', result.statusCsv);
