% Run a small STNSNr DWI Synb0/eddy fake B0 UI-coreg pilot.

repoDir = '/Users/mojackhu/Github/leaddbs';
studyRoot = '/Volumes/VAL/STNSNr';
importLog = fullfile(studyRoot, 'derivatives', 'leaddbs', ...
    'import_logs', 'dwi_import_20260701_013240.csv');

cd(repoDir);
addpath(genpath(repoDir));

result = run_project_dwi_fake_b0_coreg( ...
    'StudyRoot', studyRoot, ...
    'RepoDir', repoDir, ...
    'ImportLog', importLog, ...
    'PilotSubject', 'ChenMeiJu', ...
    'FreeSurferLicense', '/Applications/freesurfer/8.2.0/license.txt', ...
    'Force', true);

fprintf('\nFinished STNSNr DWI Synb0/eddy fake B0 UI-coreg pilot.\n');
fprintf('Status CSV: %s\n', result.statusCsv);
