% Run STN/SNr target-component VTA coverage distribution analysis.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

result = mh_fiber_run_stnsnr_target_component_vta_distribution( ...
    'RepoDir', repoDir, ...
    'SubjectRoot', '/Volumes/VAL/STNSNr/derivatives/leaddbs', ...
    'ContactQcCsv', '/Volumes/VAL/STNSNr/summary/vta/cohort_contact_mapping_qc.csv', ...
    'AtlasDir', fullfile(repoDir, 'templates', 'space', 'MNI152NLin2009bAsym', ...
        'atlases', 'Custom_Ewert_Zhang_Middlebrooks0.05'), ...
    'OutputDir', '/Volumes/VAL/STNSNr/summary/vta/target_component_distribution', ...
    'ThresholdsVPerMm', [0.18, 0.20, 0.22], ...
    'MainThresholdVPerMm', 0.20, ...
    'OutputVoxelSizeMm', 0.5, ...
    'ForceVta', false, ...
    'ForceOutputs', false);

fprintf('\nSTN/SNr target-component VTA distribution finished.\n');
fprintf('Output directory: %s\n', result.outputDir);
fprintf('Coverage table: %s\n', result.coverageLongCsv);
fprintf('Component QC table: %s\n', result.componentQcCsv);
fprintf('Summary table: %s\n', result.summaryCsv);
