% Run STN/SNr target-component VTA coverage distribution analysis.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

executionDefaults = mh_vta_default_execution_options();
vtaGmAtlas = mh_fiber_getenv_default('STNSNR_VTA_GM_ATLAS', ...
    mh_fiber_stnsnr_default_vta_gm_atlas());
vtaModelKey = mh_fiber_getenv_default('STNSNR_VTA_MODEL_KEY', ...
    mh_fiber_stnsnr_default_vta_model_key());
vtaExecutionMode = mh_fiber_getenv_default('STNSNR_VTA_EXECUTION_MODE', ...
    executionDefaults.executionMode);
vtaParallelWorkers = mh_fiber_env_number('STNSNR_VTA_PARALLEL_WORKERS', ...
    executionDefaults.parallelWorkers, ...
    'run_stnsnr_target_component_vta_distribution:InvalidEnvNumber');
vtaTaskMatlabExe = mh_fiber_getenv_default('STNSNR_VTA_TASK_MATLAB_EXE', ...
    executionDefaults.matlabExe);
vtaTaskCondaEnv = mh_fiber_getenv_default('STNSNR_VTA_TASK_CONDA_ENV', ...
    executionDefaults.condaEnv);
vtaProcessWorkDir = mh_fiber_getenv_default('STNSNR_VTA_PROCESS_WORK_DIR', ...
    executionDefaults.processWorkDir);
vtaProcessDryRun = mh_fiber_env_flag('STNSNR_VTA_PROCESS_DRY_RUN', ...
    executionDefaults.processDryRun, ...
    'run_stnsnr_target_component_vta_distribution:InvalidEnvFlag');
vtaProcessPollSeconds = mh_fiber_env_double('STNSNR_VTA_PROCESS_POLL_SECONDS', ...
    executionDefaults.processPollSeconds, 0.1, ...
    'run_stnsnr_target_component_vta_distribution:InvalidEnvNumber');
vtaProcessTimeoutSeconds = mh_fiber_env_double('STNSNR_VTA_PROCESS_TIMEOUT_SECONDS', ...
    executionDefaults.processTimeoutSeconds, 0, ...
    'run_stnsnr_target_component_vta_distribution:InvalidEnvNumber');

result = mh_fiber_run_stnsnr_target_component_vta_distribution( ...
    'RepoDir', repoDir, ...
    'SubjectRoot', '/Volumes/VAL/STNSNr/derivatives/leaddbs', ...
    'ContactQcCsv', '/Volumes/VAL/STNSNr/summary/vta/cohort_contact_mapping_qc.csv', ...
    'AtlasDir', fullfile(repoDir, 'templates', 'space', 'MNI152NLin2009bAsym', ...
        'atlases', 'Custom_Ewert_Zhang_Middlebrooks0.05'), ...
    'OutputDir', '/Volumes/VAL/STNSNr/summary/vta/target_component_distribution', ...
    'ThresholdsVPerMm', [0.18, 0.20, 0.22], ...
    'MainThresholdVPerMm', 0.20, ...
    'OutputVoxelSizeMm', 0.5, ...
    'ForceVta', false, ...
    'ForceOutputs', false, ...
    'VtaGmAtlas', vtaGmAtlas, ...
    'VtaModelKey', vtaModelKey, ...
    'VtaExecutionMode', vtaExecutionMode, ...
    'VtaParallelWorkers', vtaParallelWorkers, ...
    'VtaMatlabExe', vtaTaskMatlabExe, ...
    'VtaCondaEnv', vtaTaskCondaEnv, ...
    'VtaProcessWorkDir', vtaProcessWorkDir, ...
    'VtaProcessDryRun', vtaProcessDryRun, ...
    'VtaProcessPollSeconds', vtaProcessPollSeconds, ...
    'VtaProcessTimeoutSeconds', vtaProcessTimeoutSeconds);

fprintf('\nSTN/SNr target-component VTA distribution finished.\n');
fprintf('Output directory: %s\n', result.outputDir);
fprintf('Coverage table: %s\n', result.coverageLongCsv);
fprintf('Component QC table: %s\n', result.componentQcCsv);
fprintf('Summary table: %s\n', result.summaryCsv);
