% Run one STN/SNr VTA coverage worker on a subject subset.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

subjectIds = split_env_list(getenv('STNSNR_VTA_SUBJECT_IDS'));
subjectNames = split_env_list(getenv('STNSNR_VTA_SUBJECT_NAMES'));

if isempty(subjectIds) && isempty(subjectNames)
    error('run_stnsnr_vta_coverage_worker:MissingSubjectFilter', ...
        ['Set STNSNR_VTA_SUBJECT_IDS or STNSNR_VTA_SUBJECT_NAMES before ', ...
        'starting a worker. Workers must not run the full cohort.']);
end

result = mh_fiber_run_stnsnr_vta_coverage( ...
    'RepoDir', repoDir, ...
    'SubjectRoot', '/Volumes/VAL/STNSNr/derivatives/leaddbs', ...
    'Workbook', '/Users/mojackhu/Research/STNSNr/summary/cohort/subj/followup_stimulation.xlsx', ...
    'Sheet', 'Contact Parameters', ...
    'AtlasDir', fullfile(repoDir, 'templates', 'space', 'MNI152NLin2009bAsym', ...
        'atlases', 'Custom_Ewert_Zhang_Middlebrooks0.05'), ...
    'CohortOutputDir', '/Volumes/VAL/STNSNr/summary/vta', ...
    'ThresholdsVPerMm', [0.18, 0.20, 0.22], ...
    'MainThresholdVPerMm', 0.20, ...
    'OutputVoxelSizeMm', 0.5, ...
    'ForceVta', env_flag('STNSNR_VTA_FORCE_VTA', false), ...
    'ForceOutputs', env_flag('STNSNR_VTA_FORCE_OUTPUTS', false), ...
    'StopOnSubjectError', true, ...
    'SubjectIDs', subjectIds, ...
    'SubjectNames', subjectNames, ...
    'WriteCohortOutputs', false, ...
    'CohortOnly', false, ...
    'SkipCompletedSubjects', env_flag('STNSNR_VTA_SKIP_COMPLETED', true), ...
    'UseSubjectLocks', true, ...
    'SkipLockedSubjects', env_flag('STNSNR_VTA_SKIP_LOCKED', false));

fprintf('\nSTN/SNr VTA coverage worker finished.\n');
fprintf('Processed subject IDs: %s\n', strjoin(string(subjectIds), ', '));
fprintf('Processed subject names: %s\n', strjoin(string(subjectNames), ', '));
fprintf('Cohort output directory: %s\n', result.cohortOutputDir);

function values = split_env_list(rawValue)
if isempty(rawValue)
    values = strings(0, 1);
    return;
end
parts = string(regexp(rawValue, '[,;]+', 'split'));
values = strtrim(parts(:));
values = values(values ~= "");
end

function value = env_flag(name, defaultValue)
rawValue = lower(strtrim(string(getenv(name))));
if rawValue == ""
    value = defaultValue;
elseif ismember(rawValue, ["1", "true", "yes", "on"])
    value = true;
elseif ismember(rawValue, ["0", "false", "no", "off"])
    value = false;
else
    error('run_stnsnr_vta_coverage_worker:InvalidEnvFlag', ...
        'Invalid logical value for %s: %s', name, rawValue);
end
end
