% Run STNSNr DWI Synb0/eddy fake B0 UI-coreg staging.

repoDir = '/Users/mojackhu/Github/leaddbs';
studyRoot = '/Volumes/VAL/STNSNr';
importLog = fullfile(studyRoot, 'derivatives', 'leaddbs', ...
    'import_logs', 'dwi_import_20260701_013240.csv');

cd(repoDir);
addpath(genpath(repoDir));

runMode = 'cohort';

switch runMode
    case 'cohort'
        result = run_project_dwi_fake_b0_coreg( ...
            'StudyRoot', studyRoot, ...
            'RepoDir', repoDir, ...
            'ImportLog', importLog, ...
            'FreeSurferLicense', '/Applications/freesurfer/8.2.0/license.txt', ...
            'Force', false);
    case 'pilot'
        result = run_project_dwi_fake_b0_coreg( ...
            'StudyRoot', studyRoot, ...
            'RepoDir', repoDir, ...
            'ImportLog', importLog, ...
            'PilotSubject', 'ChenMeiJu', ...
            'FreeSurferLicense', '/Applications/freesurfer/8.2.0/license.txt', ...
            'Force', true);
    otherwise
        error('Unsupported runMode: %s', runMode);
end

fprintf('\nFinished STNSNr DWI Synb0/eddy fake B0 UI-coreg staging.\n');
fprintf('Status CSV: %s\n', result.statusCsv);
