% Aggregate completed per-subject STN/SNr VTA coverage outputs.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

result = mh_fiber_run_stnsnr_vta_coverage( ...
    'RepoDir', repoDir, ...
    'SubjectRoot', '/Volumes/VAL/STNSNr/derivatives/leaddbs', ...
    'Workbook', '/Users/mojackhu/Research/STNSNr/summary/cohort/subj/followup_stimulation.xlsx', ...
    'Sheet', 'Contact Parameters', ...
    'AtlasDir', fullfile(repoDir, 'templates', 'space', 'MNI152NLin2009bAsym', ...
        'atlases', 'Custom_Ewert_Zhang_Middlebrooks0.05'), ...
    'CohortOutputDir', '/Volumes/VAL/STNSNr/summary/vta', ...
    'ThresholdsVPerMm', [0.18, 0.20, 0.22], ...
    'MainThresholdVPerMm', 0.20, ...
    'OutputVoxelSizeMm', 0.5, ...
    'CohortOnly', true, ...
    'WriteCohortOutputs', true, ...
    'StopOnSubjectError', true);

fprintf('\nSTN/SNr VTA coverage cohort aggregation finished.\n');
fprintf('Cohort output directory: %s\n', result.cohortOutputDir);
fprintf('Coverage table: %s\n', result.coverageLongCsv);
fprintf('Contact QC table: %s\n', result.contactQcCsv);
