% Run one STN/SNr VTA coverage worker on a subject subset.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

subjectRoot = mh_fiber_getenv_default('STNSNR_VTA_SUBJECT_ROOT', ...
    '/Volumes/VAL/STNSNr/derivatives/leaddbs');
workbook = mh_fiber_getenv_default('STNSNR_VTA_WORKBOOK', ...
    '/Users/mojackhu/Research/STNSNr/summary/cohort/subj/followup_stimulation.xlsx');
cohortOutputDir = mh_fiber_getenv_default('STNSNR_VTA_COHORT_OUTPUT_DIR', ...
    '/Volumes/VAL/STNSNr/summary/vta');
vtaGmAtlas = mh_fiber_getenv_default('STNSNR_VTA_GM_ATLAS', ...
    'DISTAL Minimal (Ewert 2017)');
vtaExecutionMode = mh_fiber_getenv_default('STNSNR_VTA_EXECUTION_MODE', 'sequential');
vtaParallelWorkers = mh_fiber_env_number('STNSNR_VTA_PARALLEL_WORKERS', 1, ...
    'run_stnsnr_vta_coverage_worker:InvalidEnvNumber');
vtaTaskMatlabExe = mh_fiber_getenv_default('STNSNR_VTA_TASK_MATLAB_EXE', ...
    '/Applications/MATLAB_R2024b.app/bin/matlab');
vtaTaskCondaEnv = mh_fiber_getenv_default('STNSNR_VTA_TASK_CONDA_ENV', 'leaddbs');
vtaProcessWorkDir = mh_fiber_getenv_default('STNSNR_VTA_PROCESS_WORK_DIR', '');
vtaProcessPollSeconds = mh_fiber_env_double('STNSNR_VTA_PROCESS_POLL_SECONDS', 2, 0.1, ...
    'run_stnsnr_vta_coverage_worker:InvalidEnvNumber');
vtaProcessTimeoutSeconds = mh_fiber_env_double('STNSNR_VTA_PROCESS_TIMEOUT_SECONDS', 0, 0, ...
    'run_stnsnr_vta_coverage_worker:InvalidEnvNumber');
subjectIds = mh_fiber_split_env_list(getenv('STNSNR_VTA_SUBJECT_IDS'));
subjectNames = mh_fiber_split_env_list(getenv('STNSNR_VTA_SUBJECT_NAMES'));

if isempty(subjectIds) && isempty(subjectNames)
    error('run_stnsnr_vta_coverage_worker:MissingSubjectFilter', ...
        ['Set STNSNR_VTA_SUBJECT_IDS or STNSNR_VTA_SUBJECT_NAMES before ', ...
        'starting a worker. Workers must not run the full cohort.']);
end

result = mh_fiber_run_stnsnr_vta_coverage( ...
    'RepoDir', repoDir, ...
    'SubjectRoot', subjectRoot, ...
    'Workbook', workbook, ...
    'Sheet', 'Contact Parameters', ...
    'AtlasDir', fullfile(repoDir, 'templates', 'space', 'MNI152NLin2009bAsym', ...
        'atlases', 'Custom_Ewert_Zhang_Middlebrooks0.05'), ...
    'CohortOutputDir', cohortOutputDir, ...
    'ThresholdsVPerMm', [0.18, 0.20, 0.22], ...
    'MainThresholdVPerMm', 0.20, ...
    'OutputVoxelSizeMm', 0.5, ...
    'ForceVta', mh_fiber_env_flag('STNSNR_VTA_FORCE_VTA', false, ...
        'run_stnsnr_vta_coverage_worker:InvalidEnvFlag'), ...
    'ForceOutputs', mh_fiber_env_flag('STNSNR_VTA_FORCE_OUTPUTS', false, ...
        'run_stnsnr_vta_coverage_worker:InvalidEnvFlag'), ...
    'StopOnSubjectError', true, ...
    'SubjectIDs', subjectIds, ...
    'SubjectNames', subjectNames, ...
    'WriteCohortOutputs', false, ...
    'CohortOnly', false, ...
    'SkipCompletedSubjects', mh_fiber_env_flag('STNSNR_VTA_SKIP_COMPLETED', true, ...
        'run_stnsnr_vta_coverage_worker:InvalidEnvFlag'), ...
    'UseSubjectLocks', true, ...
    'SkipLockedSubjects', mh_fiber_env_flag('STNSNR_VTA_SKIP_LOCKED', false, ...
        'run_stnsnr_vta_coverage_worker:InvalidEnvFlag'), ...
    'VtaGmAtlas', vtaGmAtlas, ...
    'VtaExecutionMode', vtaExecutionMode, ...
    'VtaParallelWorkers', vtaParallelWorkers, ...
    'VtaMatlabExe', vtaTaskMatlabExe, ...
    'VtaCondaEnv', vtaTaskCondaEnv, ...
    'VtaProcessWorkDir', vtaProcessWorkDir, ...
    'VtaProcessPollSeconds', vtaProcessPollSeconds, ...
    'VtaProcessTimeoutSeconds', vtaProcessTimeoutSeconds);

fprintf('\nSTN/SNr VTA coverage worker finished.\n');
fprintf('Processed subject IDs: %s\n', strjoin(string(subjectIds), ', '));
fprintf('Processed subject names: %s\n', strjoin(string(subjectNames), ', '));
fprintf('Cohort output directory: %s\n', result.cohortOutputDir);
