% Run the STN/SNr three-subject b0-to-anchorNative T2 registration method pilot.

repoDir = '/Users/mojackhu/Github/leaddbs';
cd(repoDir);
addpath(genpath(repoDir));

pilotSubjects = {'ChenMeiJu', 'ZhangXiaoHong', 'ZhangMing'};

commonArgs = { ...
    'StudyRoot', '/Volumes/VAL/STNSNr', ...
    'RepoDir', repoDir, ...
    'ImportLog', fullfile('/Volumes/VAL/STNSNr', 'derivatives', 'leaddbs', ...
        'import_logs', 'dwi_import_20260701_013240.csv'), ...
    'SubjectIds', pilotSubjects, ...
    'AnchorModality', 'T2w', ...
    'AllowT1Fallback', false, ...
    'RunCoregistration', true, ...
    'GenerateOptionalDwiQc', true, ...
    'Force', false};

spmResult = mh_fiber_register_imported_dwi_batch(commonArgs{:}, ...
    'CoregistrationTag', 'dwi_t2_spm', ...
    'CoregistrationMethod', 'SPM');

hybridResult = mh_fiber_register_imported_dwi_batch(commonArgs{:}, ...
    'CoregistrationTag', 'dwi_t2_hybrid_spm_ants', ...
    'CoregistrationMethod', 'Hybrid SPM & ANTs');

fprintf('\nSPM status CSV:\n%s\n', spmResult.statusCsv);
fprintf('Hybrid SPM+ANTs status CSV:\n%s\n', hybridResult.statusCsv);
