% Validate the STNSNr DWI re-import and fake-B0 preprocessing runner.

repoDir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
runnerPath = fullfile(repoDir, 'my_helper', 'fiber', 'stnsnr', ...
    'run_stnsnr_dwi_reimport_preprocess_fakeb0.m');
projectRunnerPath = fullfile(repoDir, 'my_helper', 'fiber', 'core', 'dwi', ...
    'run_project_dwi_fake_b0_coreg.m');
batchPath = fullfile(repoDir, 'my_helper', 'fiber', 'core', 'dwi', ...
    'mh_fiber_register_imported_dwi_batch.m');
processPath = fullfile(repoDir, 'my_helper', 'fiber', 'core', 'dwi', ...
    'mh_fiber_process_imported_dwi.m');
distortionPath = fullfile(repoDir, 'my_helper', 'fiber', 'core', 'dwi', ...
    'mh_fiber_dwi_distortion_correction.m');

assert(isfile(runnerPath), 'Missing runner: %s', runnerPath);
assert(isfile(projectRunnerPath), 'Missing project runner: %s', projectRunnerPath);
assert(isfile(batchPath), 'Missing batch processor: %s', batchPath);
assert(isfile(processPath), 'Missing subject processor: %s', processPath);
assert(isfile(distortionPath), 'Missing distortion correction function: %s', distortionPath);

text = fileread(runnerPath);
expectedSubjects = { ...
    'LinJia', ...
    'HuFengXian', ...
    'YuDongJian', ...
    'WuYueFen', ...
    'LiPing', ...
    'MaoXiaoMing', ...
    'ShengGuoLiang', ...
    'ZhangXiaoHong', ...
    'ZhengXiangQuan', ...
    'ZhaoPeiGen', ...
    'ChenLingHua', ...
    'FanDongDong', ...
    'HuangDan', ...
    'ZhangMing', ...
    'GengHui', ...
    'ChenMeiJu'};

lastIndex = 0;
for i = 1:numel(expectedSubjects)
    token = ['''', expectedSubjects{i}, ''''];
    idx = strfind(text, token);
    assert(~isempty(idx), 'Runner does not include subject %s.', expectedSubjects{i});
    assert(idx(1) > lastIndex, 'Subject %s is not in the expected cohort order.', expectedSubjects{i});
    lastIndex = idx(1);
end

requiredSnippets = { ...
    '''/Volumes/VAL/STNSNr''', ...
    '''/Volumes/VAL/STNSNrdwi''', ...
    '''/Applications/freesurfer/8.2.0/license.txt''', ...
    '''dwi_import_''', ...
    '''dwi_reimport_cleanup_''', ...
    '''stnsnr_dwi_reimport_''', ...
    '''stnsnr_synb0_work''', ...
    'movefile(', ...
    'copyfile(', ...
    'file_sha256(', ...
    'run_project_dwi_fake_b0_coreg(', ...
    '''CoregistrationTag'', ''dwi_synb0_fakeb0''', ...
    '''RunCoregistration'', false', ...
    '''Parallel'', false', ...
    '''MaxConcurrentSynb0'', 1', ...
    '''Synb0WorkRoot'', synb0WorkRoot', ...
    '''Force'', true', ...
    '''PhaseEncodingVector'', [0 1 0]', ...
    '''DefaultTotalReadoutTime'', 0.05'};

for i = 1:numel(requiredSnippets)
    assert(contains(text, requiredSnippets{i}), ...
        'Runner is missing required snippet: %s', requiredSnippets{i});
end

forbiddenSnippets = { ...
    'dwi_import_20260701_013240.csv', ...
    'delete(', ...
    'rmdir('};

for i = 1:numel(forbiddenSnippets)
    assert(~contains(text, forbiddenSnippets{i}), ...
        'Runner contains forbidden snippet: %s', forbiddenSnippets{i});
end

projectText = fileread(projectRunnerPath);
batchText = fileread(batchPath);
processText = fileread(processPath);
distortionText = fileread(distortionPath);
assert(contains(projectText, '''Synb0WorkRoot'''), ...
    'Project runner does not expose Synb0WorkRoot.');
assert(contains(batchText, '''Synb0WorkRoot'''), ...
    'Batch processor does not accept Synb0WorkRoot.');
assert(contains(processText, '''Synb0WorkRoot'''), ...
    'Subject processor does not pass Synb0WorkRoot.');
assert(contains(distortionText, '''Synb0WorkRoot'''), ...
    'Distortion correction does not implement Synb0WorkRoot.');
assert(contains(distortionText, 'archive_synb0_result'), ...
    'Distortion correction does not archive local Synb0 results to project work.');

fprintf('STNSNr DWI re-import fake-B0 runner static checks passed.\n');
