function specs = mh_fiber_seed_target_roi_specs(cfg)
% Return deterministic atlas ROI definitions for seed-target tractography.

hybra = struct( ...
    'name', cfg.rois.atlasName, ...
    'nii', cfg.rois.labelingNii, ...
    'txt', cfg.rois.labelingTxt);
aal3 = struct( ...
    'name', cfg.rois.aal3Name, ...
    'nii', cfg.rois.aal3Nii, ...
    'txt', cfg.rois.aal3Txt);
hammers = struct( ...
    'name', cfg.rois.hammersName, ...
    'nii', cfg.rois.hammersNii, ...
    'txt', cfg.rois.hammersTxt);

specs = struct('roi', {}, 'side', {}, 'atlas', {}, 'labelIds', {}, 'note', {});

for sideCell = {'L', 'R'}
    side = sideCell{1};
    specs(end+1) = roi_spec('NAc', side, hybra, side_ids(side, 305, 306), ...
        'HybraPD nucleus accumbens label.'); %#ok<AGROW>
    specs(end+1) = roi_spec('ALIC', side, hybra, side_ids(side, 218, 217), ...
        'HybraPD anterior limb of internal capsule label. Centroid side is checked because the local label text may be side-swapped.'); %#ok<AGROW>
    specs(end+1) = roi_spec('mPFC', side, hybra, side_ids(side, [19, 21, 23], [20, 22, 24]), ...
        'HybraPD merged Frontal_Sup_Medial, Frontal_Med_Orb, and Rectus labels.'); %#ok<AGROW>
    specs(end+1) = roi_spec('OFC', side, hybra, side_ids(side, [25, 27, 29, 31], [26, 28, 30, 32]), ...
        'HybraPD merged OFCmed, OFCant, OFCpost, and OFClat labels.'); %#ok<AGROW>
    specs(end+1) = roi_spec('ACC', side, hammers, side_ids(side, 24, 25), ...
        'Hammers n30r95 anterior cingulate fallback because the local HybraPD table lacks a clear Cingulate_Ant label and the local AAL3 NIfTI has empty anterior cingulate labels.'); %#ok<AGROW>
    specs(end+1) = roi_spec('amygdala', side, hybra, side_ids(side, 45, 46), ...
        'HybraPD amygdala label.'); %#ok<AGROW>
    specs(end+1) = roi_spec('hippocampus', side, hybra, side_ids(side, 41, 42), ...
        'HybraPD hippocampus label.'); %#ok<AGROW>
    specs(end+1) = roi_spec('thalamus', side, hybra, side_ids(side, 333, 334), ...
        'HybraPD thalamus label.'); %#ok<AGROW>
    specs(end+1) = roi_spec('VTA', side, aal3, side_ids(side, 159, 160), ...
        'AAL3 VTA label. This is an anatomical target, separate from the stimulation VTA used for VTA-hit statistics.'); %#ok<AGROW>
end

end

function spec = roi_spec(roi, side, atlas, labelIds, note)
spec = struct();
spec.roi = roi;
spec.side = side;
spec.atlas = atlas;
spec.labelIds = double(labelIds(:)');
spec.note = note;
end

function ids = side_ids(side, leftIds, rightIds)
if strcmp(side, 'L')
    ids = leftIds;
else
    ids = rightIds;
end
end
