function result = mh_compare_single_source_backend_outputs( ...
    referencePath, candidatePath, varargin)
% Compare two single-source backend E-field NIfTI images.
%
% result = mh_compare_single_source_backend_outputs(referencePath, ...
%     candidatePath, 'Space', space, 'Side', side, ...
%     'Comparison', comparison, 'ThrowOnFailure', throwOnFailure)
%
% comparison is either "equivalence" or "repeatability". Repeatability
% applies all equivalence gates and additionally requires voxel-identical
% image values. The returned struct contains efield_row (one-row table),
% binary_rows (one row for each 180/200/220 V/m mask), and pass (logical).
% Tables can be written with writetable or converted for JSON with
% table2struct. ThrowOnFailure defaults to true and raises deterministic
% namespaced error IDs. Set it false to retain complete failed metrics.

limits = acceptance_limits();
inputs = parse_inputs(referencePath, candidatePath, varargin{:});

referenceNii = load_nii(inputs.reference_path, 'reference');
candidateNii = load_nii(inputs.candidate_path, 'candidate');

referenceSize = size(referenceNii.img);
originalCandidateSize = size(candidateNii.img);
inputs.resampled_to_reference_grid = false;
if inputs.resample_candidate_to_reference && ...
        ~grid_geometry_matches(candidateNii, referenceNii)
    candidateNii = resample_linear_to_reference(candidateNii, referenceNii);
    inputs.resampled_to_reference_grid = true;
end
candidateSize = size(candidateNii.img);
dimensionsMatch = isequal(referenceSize, candidateSize);
if ~dimensionsMatch
    if inputs.throw_on_failure
        error('mh_compare_single_source_backend_outputs:DimensionMismatch', ...
            'E-field dimensions differ: reference=%s, candidate=%s.', ...
            dimensions_text(referenceSize), dimensions_text(candidateSize));
    end
    result = structural_failure_result(inputs, referenceSize, ...
        originalCandidateSize, candidateSize, ...
        nnz(isfinite(referenceNii.img)), false, false);
    return;
end

referenceFinite = isfinite(referenceNii.img);
candidateFinite = isfinite(candidateNii.img);
finiteMaskMatch = isequal(referenceFinite, candidateFinite);
if ~finiteMaskMatch
    if inputs.throw_on_failure
        error('mh_compare_single_source_backend_outputs:FiniteMaskMismatch', ...
            'E-field finite masks differ at %d voxels.', ...
            nnz(xor(referenceFinite, candidateFinite)));
    end
    result = structural_failure_result(inputs, referenceSize, ...
        originalCandidateSize, candidateSize, nnz(referenceFinite), ...
        true, false);
    return;
end
finiteSignalPresent = any(referenceFinite(:));

affineMaxAbs = affine_difference(referenceNii, candidateNii);

referenceValues = double(referenceNii.img(referenceFinite));
candidateValues = double(candidateNii.img(candidateFinite));
nonzeroSignal = max_abs_or_zero(referenceValues) > 0 && ...
    max_abs_or_zero(candidateValues) > 0;
valueDifference = candidateValues - referenceValues;
valueMaxAbs = max_abs_or_zero(valueDifference);
relativeL2 = relative_l2(referenceValues, valueDifference);
correlation = pearson_correlation(referenceValues, candidateValues);
exactRepeatability = isequaln(referenceNii.img, candidateNii.img);

equivalencePass = affineMaxAbs <= limits.affine_max_abs && ...
    valueMaxAbs <= limits.value_max_abs && ...
    relativeL2 <= limits.relative_l2 && ...
    correlation >= limits.correlation_min;
repeatabilityPass = inputs.comparison ~= "repeatability" || exactRepeatability;
efieldPass = finiteSignalPresent && nonzeroSignal && ...
    equivalencePass && repeatabilityPass;

efieldRow = make_efield_row(inputs, referenceSize, originalCandidateSize, ...
    candidateSize, ...
    nnz(referenceFinite), true, true, ...
    affineMaxAbs, valueMaxAbs, relativeL2, correlation, ...
    exactRepeatability, finiteSignalPresent, nonzeroSignal, efieldPass);
binaryRows = make_binary_rows(inputs, referenceNii, candidateNii, limits);

result = struct();
result.efield_row = efieldRow;
result.binary_rows = binaryRows;
result.pass = logical(efieldPass && all(binaryRows.pass));
if inputs.throw_on_failure && ~result.pass
    throw_gate_failure(inputs, efieldRow, binaryRows, limits);
end
end

function limits = acceptance_limits()
limits = struct( ...
    'affine_max_abs', 1e-12, ...
    'value_max_abs', 1e-3, ...
    'relative_l2', 1e-5, ...
    'correlation_min', 0.999999, ...
    'thresholds_v_per_m', [180 200 220], ...
    'dice_min', 0.999, ...
    'relative_volume_diff_max', 0.001, ...
    'discordant_distance_max_v_per_m', 1e-3);
end

function inputs = parse_inputs(referencePath, candidatePath, varargin)
parser = inputParser;
parser.FunctionName = 'mh_compare_single_source_backend_outputs';
addRequired(parser, 'referencePath', @(x) ischar(x) || isstring(x));
addRequired(parser, 'candidatePath', @(x) ischar(x) || isstring(x));
addParameter(parser, 'Space', '', @(x) ischar(x) || isstring(x));
addParameter(parser, 'Side', '', @(x) ischar(x) || isstring(x));
addParameter(parser, 'Comparison', 'equivalence', ...
    @(x) ischar(x) || isstring(x));
addParameter(parser, 'ThrowOnFailure', true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(parser, 'ResampleCandidateToReference', false, ...
    @(x) islogical(x) && isscalar(x));
parse(parser, referencePath, candidatePath, varargin{:});

inputs = struct( ...
    'reference_path', string(parser.Results.referencePath), ...
    'candidate_path', string(parser.Results.candidatePath), ...
    'space', string(parser.Results.Space), ...
    'side', string(parser.Results.Side), ...
    'comparison', lower(string(parser.Results.Comparison)), ...
    'throw_on_failure', parser.Results.ThrowOnFailure, ...
    'resample_candidate_to_reference', ...
        parser.Results.ResampleCandidateToReference);
if ~isscalar(inputs.reference_path) || ~isscalar(inputs.candidate_path) || ...
        ~isscalar(inputs.space) || ~isscalar(inputs.side) || ...
        ~isscalar(inputs.comparison)
    error('mh_compare_single_source_backend_outputs:InvalidInput', ...
        'Paths and metadata values must be scalar text values.');
end
if ~any(inputs.comparison == ["equivalence" "repeatability"])
    error('mh_compare_single_source_backend_outputs:InvalidComparison', ...
        'Comparison must be "equivalence" or "repeatability".');
end
if inputs.resample_candidate_to_reference && ...
        inputs.comparison == "repeatability"
    error('mh_compare_single_source_backend_outputs:InvalidComparison', ...
        'Repeatability comparison cannot resample either input.');
end
end

function resampled = resample_linear_to_reference(source, reference)
sourceImage = double(source.img);
referenceSize = size(reference.img);
resampledImage = nan(referenceSize);
interpolant = griddedInterpolant( ...
    {1:size(sourceImage, 1), 1:size(sourceImage, 2), ...
     1:size(sourceImage, 3)}, ...
    sourceImage, 'linear', 'none');

voxelCount = prod(referenceSize);
chunkSize = 250000;
for firstIndex = 1:chunkSize:voxelCount
    lastIndex = min(voxelCount, firstIndex + chunkSize - 1);
    linearIndices = (firstIndex:lastIndex)';
    [x, y, z] = ind2sub(referenceSize, linearIndices);
    worldCoordinates = ea_vox2mm([x, y, z], reference.mat);
    sourceCoordinates = ea_mm2vox(worldCoordinates, source.mat);
    resampledImage(linearIndices) = interpolant( ...
        sourceCoordinates(:, 1), sourceCoordinates(:, 2), ...
        sourceCoordinates(:, 3));
end

resampled = source;
resampled.img = resampledImage;
resampled.mat = reference.mat;
end

function matches = grid_geometry_matches(candidate, reference)
matches = isequal(size(candidate.img), size(reference.img)) && ...
    max(abs(double(candidate.mat(:)) - double(reference.mat(:)))) <= 1e-12;
end

function nii = load_nii(path, role)
if ~isfile(path)
    error('mh_compare_single_source_backend_outputs:FileNotFound', ...
        'The %s E-field does not exist: %s', role, path);
end
try
    nii = ea_load_nii(char(path));
catch ME
    wrapped = MException( ...
        'mh_compare_single_source_backend_outputs:NiftiReadFailed', ...
        'Could not read the %s E-field NIfTI: %s', role, path);
    wrapped = addCause(wrapped, ME);
    throw(wrapped);
end
if ~isfield(nii, 'img') || ~isfield(nii, 'mat') || ...
        ~isnumeric(nii.img) || ~isreal(nii.img)
    error('mh_compare_single_source_backend_outputs:InvalidNifti', ...
        'The %s E-field is missing real numeric image or affine data.', role);
end
end

function value = affine_difference(referenceNii, candidateNii)
if ~isequal(size(referenceNii.mat), size(candidateNii.mat)) || ...
        ~all(isfinite(referenceNii.mat(:))) || ...
        ~all(isfinite(candidateNii.mat(:)))
    value = Inf;
    return
end
value = max_abs_or_zero(double(candidateNii.mat(:)) - ...
    double(referenceNii.mat(:)));
end

function row = make_efield_row(inputs, referenceSize, originalCandidateSize, ...
    candidateSize, ...
    finiteVoxelCount, dimensionsMatch, finiteMaskMatch, ...
    affineMaxAbs, valueMaxAbs, relativeL2, correlation, ...
    exactRepeatability, finiteSignalPresent, nonzeroSignal, pass)
row = table( ...
    inputs.space, inputs.side, inputs.comparison, ...
    inputs.reference_path, inputs.candidate_path, ...
    string(dimensions_text(referenceSize)), ...
    string(dimensions_text(originalCandidateSize)), ...
    string(dimensions_text(candidateSize)), prod(referenceSize), ...
        finiteVoxelCount, dimensionsMatch, finiteMaskMatch, ...
        inputs.resampled_to_reference_grid, ...
    finiteSignalPresent, nonzeroSignal, affineMaxAbs, ...
    valueMaxAbs, relativeL2, correlation, exactRepeatability, logical(pass), ...
    'VariableNames', { ...
        'space', 'side', 'comparison', 'reference_path', 'candidate_path', ...
        'dimensions', 'candidate_original_dimensions', ...
        'candidate_dimensions', 'voxel_count', ...
        'finite_voxel_count', ...
        'dimensions_match', 'finite_mask_match', ...
        'resampled_to_reference_grid', 'finite_signal_present', ...
        'nonzero_signal', ...
        'affine_max_abs', 'value_max_abs', ...
        'relative_l2', 'correlation', ...
        'exact_repeatability', 'pass'});
end

function result = structural_failure_result(inputs, referenceSize, ...
        originalCandidateSize, candidateSize, finiteVoxelCount, ...
        dimensionsMatch, finiteMaskMatch)
finiteSignalPresent = finiteVoxelCount > 0;
efieldRow = make_efield_row(inputs, referenceSize, originalCandidateSize, ...
    candidateSize, ...
    finiteVoxelCount, dimensionsMatch, finiteMaskMatch, NaN, NaN, NaN, ...
    NaN, false, finiteSignalPresent, false, false);
limits = acceptance_limits();
binaryRows = failed_binary_rows(inputs, limits.thresholds_v_per_m);
result = struct('efield_row', efieldRow, 'binary_rows', binaryRows, ...
    'pass', false);
end

function rows = failed_binary_rows(inputs, thresholds)
thresholds = thresholds(:);
rowCount = numel(thresholds);
missing = nan(rowCount, 1);
rows = table( ...
    repmat(inputs.space, rowCount, 1), ...
    repmat(inputs.side, rowCount, 1), ...
    repmat(inputs.comparison, rowCount, 1), ...
    thresholds, missing, missing, missing, missing, missing, missing, ...
    missing, missing, missing, false(rowCount, 1), false(rowCount, 1), ...
    'VariableNames', { ...
        'space', 'side', 'comparison', 'threshold_v_per_m', ...
        'reference_voxels', 'candidate_voxels', ...
        'reference_volume_mm3', 'candidate_volume_mm3', ...
        'discordant_voxels', 'dice', 'relative_volume_diff', ...
        'reference_discordant_max_distance_v_per_m', ...
        'candidate_discordant_max_distance_v_per_m', ...
        'discordant_within_tolerance', 'pass'});
end

function rows = make_binary_rows(inputs, referenceNii, candidateNii, limits)
thresholds = limits.thresholds_v_per_m(:);
rowCount = numel(thresholds);
referenceVoxelVolume = voxel_volume(referenceNii.mat);
candidateVoxelVolume = voxel_volume(candidateNii.mat);

referenceVoxels = zeros(rowCount, 1);
candidateVoxels = zeros(rowCount, 1);
referenceVolume = zeros(rowCount, 1);
candidateVolume = zeros(rowCount, 1);
discordantVoxels = zeros(rowCount, 1);
dice = zeros(rowCount, 1);
relativeVolumeDiff = zeros(rowCount, 1);
referenceDiscordantMaxDistance = zeros(rowCount, 1);
candidateDiscordantMaxDistance = zeros(rowCount, 1);
discordantWithinTolerance = false(rowCount, 1);
pass = false(rowCount, 1);

for index = 1:rowCount
    threshold = thresholds(index);
    referenceMask = isfinite(referenceNii.img) & referenceNii.img >= threshold;
    candidateMask = isfinite(candidateNii.img) & candidateNii.img >= threshold;
    discordantMask = xor(referenceMask, candidateMask);

    referenceVoxels(index) = nnz(referenceMask);
    candidateVoxels(index) = nnz(candidateMask);
    referenceVolume(index) = referenceVoxels(index) * referenceVoxelVolume;
    candidateVolume(index) = candidateVoxels(index) * candidateVoxelVolume;
    discordantVoxels(index) = nnz(discordantMask);
    dice(index) = dice_coefficient(referenceMask, candidateMask);
    relativeVolumeDiff(index) = relative_difference( ...
        referenceVolume(index), candidateVolume(index));
    referenceDiscordantMaxDistance(index) = discordant_distance( ...
        referenceNii.img, discordantMask, threshold);
    candidateDiscordantMaxDistance(index) = discordant_distance( ...
        candidateNii.img, discordantMask, threshold);
    discordantWithinTolerance(index) = ...
        referenceDiscordantMaxDistance(index) <= ...
            limits.discordant_distance_max_v_per_m && ...
        candidateDiscordantMaxDistance(index) <= ...
            limits.discordant_distance_max_v_per_m;
    pass(index) = referenceVoxels(index) > 0 && ...
        candidateVoxels(index) > 0 && ...
        dice(index) >= limits.dice_min && ...
        relativeVolumeDiff(index) <= limits.relative_volume_diff_max && ...
        discordantWithinTolerance(index);
end

rows = table( ...
    repmat(inputs.space, rowCount, 1), ...
    repmat(inputs.side, rowCount, 1), ...
    repmat(inputs.comparison, rowCount, 1), ...
    thresholds, referenceVoxels, candidateVoxels, ...
    referenceVolume, candidateVolume, discordantVoxels, dice, ...
    relativeVolumeDiff, referenceDiscordantMaxDistance, ...
    candidateDiscordantMaxDistance, discordantWithinTolerance, pass, ...
    'VariableNames', { ...
        'space', 'side', 'comparison', 'threshold_v_per_m', ...
        'reference_voxels', 'candidate_voxels', ...
        'reference_volume_mm3', 'candidate_volume_mm3', ...
        'discordant_voxels', 'dice', 'relative_volume_diff', ...
        'reference_discordant_max_distance_v_per_m', ...
        'candidate_discordant_max_distance_v_per_m', ...
        'discordant_within_tolerance', 'pass'});
end

function throw_gate_failure(inputs, efieldRow, binaryRows, limits)
if ~efieldRow.finite_signal_present
    error('mh_compare_single_source_backend_outputs:NoFiniteSignal', ...
        'E-field images do not contain any finite voxels.');
end
if ~efieldRow.nonzero_signal
    error('mh_compare_single_source_backend_outputs:ZeroSignal', ...
        'Both E-field images must contain nonzero finite signal.');
end
if ~(efieldRow.affine_max_abs <= limits.affine_max_abs)
    error('mh_compare_single_source_backend_outputs:AffineToleranceExceeded', ...
        'Affine maximum absolute difference %.17g exceeds %.17g.', ...
        efieldRow.affine_max_abs, limits.affine_max_abs);
end
if inputs.comparison == "repeatability" && ~efieldRow.exact_repeatability
    error('mh_compare_single_source_backend_outputs:RepeatabilityMismatch', ...
        'Repeatability comparison requires voxel-identical E-fields.');
end
if ~(efieldRow.value_max_abs <= limits.value_max_abs)
    error('mh_compare_single_source_backend_outputs:ValueToleranceExceeded', ...
        'Value maximum absolute difference %.17g V/m exceeds %.17g V/m.', ...
        efieldRow.value_max_abs, limits.value_max_abs);
end
if ~(efieldRow.relative_l2 <= limits.relative_l2)
    error('mh_compare_single_source_backend_outputs:RelativeL2ToleranceExceeded', ...
        'Relative L2 error %.17g exceeds %.17g.', ...
        efieldRow.relative_l2, limits.relative_l2);
end
if ~(efieldRow.correlation >= limits.correlation_min)
    error('mh_compare_single_source_backend_outputs:CorrelationToleranceExceeded', ...
        'Pearson correlation %.17g is below %.17g.', ...
        efieldRow.correlation, limits.correlation_min);
end

firstEmptyMask = find(binaryRows.reference_voxels == 0 | ...
    binaryRows.candidate_voxels == 0, 1);
if ~isempty(firstEmptyMask)
    error('mh_compare_single_source_backend_outputs:EmptyThresholdMask', ...
        'Both E-fields must contain suprathreshold voxels at %.17g V/m.', ...
        binaryRows.threshold_v_per_m(firstEmptyMask));
end

firstDiceFailure = find(binaryRows.dice < limits.dice_min, 1);
if ~isempty(firstDiceFailure)
    error('mh_compare_single_source_backend_outputs:BinaryDiceToleranceExceeded', ...
        'Dice %.17g at %.17g V/m is below %.17g.', ...
        binaryRows.dice(firstDiceFailure), ...
        binaryRows.threshold_v_per_m(firstDiceFailure), limits.dice_min);
end
firstVolumeFailure = find( ...
    binaryRows.relative_volume_diff > limits.relative_volume_diff_max, 1);
if ~isempty(firstVolumeFailure)
    error('mh_compare_single_source_backend_outputs:BinaryVolumeToleranceExceeded', ...
        'Relative volume difference %.17g at %.17g V/m exceeds %.17g.', ...
        binaryRows.relative_volume_diff(firstVolumeFailure), ...
        binaryRows.threshold_v_per_m(firstVolumeFailure), ...
        limits.relative_volume_diff_max);
end
firstDiscordanceFailure = find(~binaryRows.discordant_within_tolerance, 1);
if ~isempty(firstDiscordanceFailure)
    error('mh_compare_single_source_backend_outputs:BinaryDiscordanceToleranceExceeded', ...
        'Discordant voxels at %.17g V/m exceed the %.17g V/m distance limit.', ...
        binaryRows.threshold_v_per_m(firstDiscordanceFailure), ...
        limits.discordant_distance_max_v_per_m);
end
end

function value = voxel_volume(affine)
value = abs(det(double(affine(1:3, 1:3))));
end

function value = dice_coefficient(referenceMask, candidateMask)
denominator = nnz(referenceMask) + nnz(candidateMask);
if denominator == 0
    value = 1;
else
    value = 2 * nnz(referenceMask & candidateMask) / denominator;
end
end

function value = relative_difference(referenceValue, candidateValue)
denominator = max(abs([referenceValue candidateValue]));
if denominator == 0
    value = 0;
else
    value = abs(candidateValue - referenceValue) / denominator;
end
end

function value = discordant_distance(image, discordantMask, threshold)
if ~any(discordantMask(:))
    value = 0;
else
    value = max(abs(double(image(discordantMask)) - threshold));
end
end

function value = relative_l2(referenceValues, difference)
denominator = norm(referenceValues, 2);
numerator = norm(difference, 2);
if denominator == 0
    if numerator == 0
        value = 0;
    else
        value = Inf;
    end
else
    value = numerator / denominator;
end
end

function value = pearson_correlation(referenceValues, candidateValues)
if isequaln(referenceValues, candidateValues)
    value = 1;
elseif numel(referenceValues) < 2 || ...
        std(referenceValues) == 0 || std(candidateValues) == 0
    value = 0;
else
    correlationMatrix = corrcoef(referenceValues, candidateValues);
    value = correlationMatrix(1, 2);
end
end

function value = max_abs_or_zero(values)
if isempty(values)
    value = 0;
else
    value = max(abs(values));
end
end

function text = dimensions_text(dimensions)
text = char(join(string(dimensions), 'x'));
end
