function result = mh_validate_canonical_mni_outputs( ...
        storedMniPath, repeatMniPath, thresholdPaths, thresholds, varargin)
% Validate deterministic canonical MNI transformation and threshold outputs.

parser = inputParser;
parser.FunctionName = mfilename;
parser.addParameter('ThrowOnFailure', true, ...
    @(value) islogical(value) && isscalar(value));
parser.parse(varargin{:});
throwOnFailure = parser.Results.ThrowOnFailure;

stored = load_nii(storedMniPath, 'stored MNI E-field');
repeated = load_nii(repeatMniPath, 'repeated MNI E-field');
dimensionsMatch = isequal(size(stored.img), size(repeated.img));
affineMatch = isequal(size(stored.mat), size(repeated.mat)) && ...
    max(abs(double(stored.mat(:)) - double(repeated.mat(:)))) <= 1e-12;
finiteMaskMatch = dimensionsMatch && ...
    isequal(isfinite(stored.img), isfinite(repeated.img));
deterministicRepeat = dimensionsMatch && affineMatch && finiteMaskMatch && ...
    isequaln(stored.img, repeated.img);
finiteValues = double(stored.img(isfinite(stored.img)));
finiteNonzeroSignal = ~isempty(finiteValues) && any(finiteValues ~= 0);

thresholds = double(thresholds(:));
if ~iscell(thresholdPaths) || numel(thresholdPaths) ~= numel(thresholds)
    error('mh_vta_acceptance:InvalidMniThresholdInventory', ...
        'MNI threshold paths must align one-to-one with thresholds.');
end
thresholdPass = false(numel(thresholds), 1);
for index = 1:numel(thresholds)
    thresholdNii = load_nii(thresholdPaths{index}, 'MNI threshold');
    expected = uint8(isfinite(stored.img) & stored.img >= thresholds(index));
    thresholdPass(index) = ...
        isequal(size(thresholdNii.img), size(stored.img)) && ...
        isequal(size(thresholdNii.mat), size(stored.mat)) && ...
        max(abs(double(thresholdNii.mat(:)) - double(stored.mat(:)))) <= 1e-12 && ...
        isequal(uint8(thresholdNii.img), expected);
end

thresholdRows = table(thresholds, thresholdPass, ...
    'VariableNames', {'threshold_v_per_m', 'pass'});
pass = deterministicRepeat && finiteNonzeroSignal && all(thresholdPass);
result = struct( ...
    'stored_mni_path', char(string(storedMniPath)), ...
    'repeat_mni_path', char(string(repeatMniPath)), ...
    'dimensions_match', dimensionsMatch, ...
    'affine_match', affineMatch, ...
    'finite_mask_match', finiteMaskMatch, ...
    'finite_nonzero_signal', finiteNonzeroSignal, ...
    'deterministic_repeat', deterministicRepeat, ...
    'threshold_rows', thresholdRows, ...
    'pass', pass);

if throwOnFailure && ~pass
    if ~deterministicRepeat
        error('mh_vta_acceptance:MniTransformNondeterministic', ...
            'Repeated native-to-MNI transformation is not voxel-identical.');
    end
    if ~finiteNonzeroSignal
        error('mh_vta_acceptance:InvalidMniSignal', ...
            'Canonical MNI E-field must contain finite nonzero signal.');
    end
    error('mh_vta_acceptance:MniThresholdMismatch', ...
        'One or more MNI VTA files do not match continuous-field thresholding.');
end
end

function nii = load_nii(path, label)
path = char(string(path));
if ~isfile(path)
    error('mh_vta_acceptance:MissingMniArtifact', ...
        'Required %s does not exist: %s', label, path);
end
nii = ea_load_nii(path);
if ~isfield(nii, 'img') || ~isfield(nii, 'mat') || ...
        ~isnumeric(nii.img) || ~isreal(nii.img) || ...
        ~isnumeric(nii.mat) || any(~isfinite(nii.mat(:)))
    error('mh_vta_acceptance:InvalidMniArtifact', ...
        'Required %s is not a valid real NIfTI: %s', label, path);
end
end
