function result = run_current_factorization_cache_acceptance(varargin)
% Run a bounded two-solve real-FEM factorization-cache acceptance gate.

parser = inputParser;
parser.FunctionName = mfilename;
parser.addParameter('StudyBase', ...
    '/Volumes/VAL/STNSNr/summary/cohort/subj/study_base.json', ...
    @(value) ischar(value) || isstring(value) && isscalar(value));
parser.addParameter('WorkRoot', '/Volumes/VAL/STNSNr/validation', ...
    @(value) ischar(value) || isstring(value) && isscalar(value));
parser.addParameter('SubjectId', 'SNr003', ...
    @(value) ischar(value) || isstring(value) && isscalar(value));
parser.addParameter('Seed', 20260712, ...
    @(value) isnumeric(value) && isscalar(value) && isfinite(value));
parser.addParameter('Mode', 'fem', ...
    @(value) ischar(value) || isstring(value) && isscalar(value));
parser.parse(varargin{:});
opts = parser.Results;
mode = lower(char(string(opts.Mode)));
if ~ismember(mode, {'fem', 'fixture_only'})
    error('run_current_factorization_cache_acceptance:InvalidMode', ...
        'Mode must be fem or fixture_only.');
end

repoDir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(genpath(repoDir), '-end');
fixture = run_current_backend_equivalence( ...
    'WorkRoot', opts.WorkRoot, 'Seed', opts.Seed, 'Mode', 'fixture_only');
oneCase = select_cache_case(fixture.cases);
if strcmp(mode, 'fixture_only')
    result = struct( ...
        'mode', mode, ...
        'case', oneCase, ...
        'planned_fem_solve_count', 2, ...
        'expected_matrix_cache_status', {{'miss', 'hit'}}, ...
        'expected_preconditioner_cache_status', {{'miss', 'hit'}}, ...
        'pass', true);
    return;
end

studyBasePath = must_be_file(opts.StudyBase, 'study-base JSON');
studyDocument = jsondecode(fileread(studyBasePath));
subject = select_subject(studyDocument, opts.SubjectId);
electrode = select_electrode(subject, oneCase.hemisphere);
runRoot = create_run_root(opts.WorkRoot);
copiedSubject = copy_subject_tree( ...
    must_be_folder(subject.subject_sources.leaddbs_subject_dir, ...
        'Lead-DBS subject directory'), runRoot);

runtime = mh_vta_create_subject_runtime(subject.subject_id);
events = repmat(empty_event(), 0, 1);
firstTask = build_task(subject, electrode, copiedSubject, oneCase, ...
    'factorization-cache-pass-1', 'cache-pass-1');
secondTask = build_task(subject, electrode, copiedSubject, oneCase, ...
    'factorization-cache-pass-2', 'cache-pass-2');
firstPhysical = physical_payload(firstTask);
secondPhysical = physical_payload(secondTask);
if ~isequaln(firstPhysical, secondPhysical)
    error('run_current_factorization_cache_acceptance:PhysicalInputMismatch', ...
        'The two acceptance tasks must have identical physical inputs.');
end

manifest = struct( ...
    'schema_version', 'vta_current_factorization_cache_acceptance_v1', ...
    'subject_id', char(string(subject.subject_id)), ...
    'case_id', oneCase.case_id, ...
    'planned_fem_solve_count', 2, ...
    'study_base', studyBasePath, ...
    'study_base_sha256', mh_fiber_file_sha256(studyBasePath), ...
    'copied_subject', copiedSubject, ...
    'physical_input', firstPhysical, ...
    'started_at', timestamp_iso(), ...
    'completed_at', '', ...
    'pass', false);
write_json(fullfile(runRoot, 'validation_manifest.json'), manifest);

firstStatus = mh_vta_backend_simbio_onesolve_canonical(firstTask, ...
    'EventEmitter', @collect_event, 'TaskId', firstTask.task_id, ...
    'SubjectRuntime', runtime);
secondStatus = mh_vta_backend_simbio_onesolve_canonical(secondTask, ...
    'EventEmitter', @collect_event, 'TaskId', secondTask.task_id, ...
    'SubjectRuntime', runtime);

eventTable = struct2table(events);
writetable(eventTable, fullfile(runRoot, 'stage_timing_events.csv'));
matrixStatuses = cache_statuses(eventTable, ...
    'fem_matrix_preparation', {firstTask.task_id, secondTask.task_id});
preconditionerStatuses = cache_statuses(eventTable, ...
    'fem_preconditioner', {firstTask.task_id, secondTask.task_id});
cacheSequencePass = isequal(matrixStatuses, ["miss"; "hit"]) && ...
    isequal(preconditionerStatuses, ["miss"; "hit"]);
cacheBoundPass = runtime.caches.fem_factorization.Count == 1;

nativeComparison = mh_compare_single_source_backend_outputs( ...
    firstStatus.native_efield, secondStatus.native_efield, ...
    'Space', 'native', 'Side', oneCase.hemisphere, ...
    'Comparison', 'optimization_regression', 'ThrowOnFailure', false);
mniComparison = mh_compare_single_source_backend_outputs( ...
    firstStatus.mni_efield, secondStatus.mni_efield, ...
    'Space', 'MNI152NLin2009bAsym', 'Side', oneCase.hemisphere, ...
    'Comparison', 'optimization_regression', 'ThrowOnFailure', false);
efieldMetrics = [nativeComparison.efield_row; mniComparison.efield_row];
binaryMetrics = [nativeComparison.binary_rows; mniComparison.binary_rows];
writetable(efieldMetrics, fullfile(runRoot, 'efield_metrics.csv'));
writetable(binaryMetrics, fullfile(runRoot, 'binary_vta_metrics.csv'));

independentLeaves = ~strcmp(firstTask.output_leaves.native, ...
    secondTask.output_leaves.native) && ...
    ~strcmp(firstTask.output_leaves.MNI152NLin2009bAsym, ...
        secondTask.output_leaves.MNI152NLin2009bAsym);
artifactPass = independentLeaves && ...
    all_required_artifacts_exist(firstTask) && ...
    all_required_artifacts_exist(secondTask);
overallPass = cacheSequencePass && cacheBoundPass && ...
    nativeComparison.pass && mniComparison.pass && artifactPass;
summary = struct( ...
    'schema_version', 'vta_current_factorization_cache_summary_v1', ...
    'subject_id', char(string(subject.subject_id)), ...
    'case_id', oneCase.case_id, ...
    'planned_fem_solve_count', 2, ...
    'actual_fem_solve_count', 2, ...
    'matrix_cache_status', {cellstr(matrixStatuses)}, ...
    'preconditioner_cache_status', {cellstr(preconditionerStatuses)}, ...
    'factorization_cache_entry_count', ...
        double(runtime.caches.fem_factorization.Count), ...
    'cache_sequence_passed', cacheSequencePass, ...
    'cache_bound_passed', cacheBoundPass, ...
    'native_optimization_regression_passed', nativeComparison.pass, ...
    'mni_optimization_regression_passed', mniComparison.pass, ...
    'independent_output_leaves_passed', artifactPass, ...
    'pass', overallPass);
write_json(fullfile(runRoot, 'acceptance_summary.json'), summary);
manifest.completed_at = timestamp_iso();
manifest.pass = overallPass;
write_json(fullfile(runRoot, 'validation_manifest.json'), manifest);

result = struct('mode', mode, 'run_root', runRoot, ...
    'summary', summary, 'pass', overallPass);
if ~overallPass
    error('run_current_factorization_cache_acceptance:AcceptanceFailed', ...
        'Current factorization cache acceptance failed: %s', runRoot);
end

    function collect_event(eventType, fields)
        if ~strcmp(char(string(eventType)), 'stage_timing')
            return;
        end
        cacheStatus = '';
        if isfield(fields, 'cache_status')
            cacheStatus = char(string(fields.cache_status));
        end
        events(end + 1) = struct( ... %#ok<AGROW>
            'task_id', char(string(fields.task_id)), ...
            'stage', char(string(fields.stage)), ...
            'status', char(string(fields.status)), ...
            'cache_status', cacheStatus, ...
            'duration_seconds', double(fields.duration_seconds));
    end
end

function oneCase = select_cache_case(cases)
selected = strcmp({cases.hemisphere}, 'R') & ...
    strcmp({cases.design}, 'single_cathode_case_return');
if nnz(selected) ~= 1
    error('run_current_factorization_cache_acceptance:CaseSelectionFailed', ...
        'Expected one right single-cathode/case-return current case.');
end
oneCase = cases(selected);
end

function subject = select_subject(document, subjectId)
if ~isfield(document, 'study') || ~isfield(document.study, 'subjects')
    error('run_current_factorization_cache_acceptance:InvalidStudyBase', ...
        'Study base must contain study.subjects.');
end
subjects = document.study.subjects;
selected = strcmp(string({subjects.subject_id}), string(subjectId));
if nnz(selected) ~= 1
    error('run_current_factorization_cache_acceptance:SubjectSelectionFailed', ...
        'Subject must resolve exactly once: %s', char(string(subjectId)));
end
subject = subjects(selected);
end

function electrode = select_electrode(subject, hemisphere)
selected = strcmp(string({subject.electrodes.hemisphere}), ...
    string(hemisphere));
if nnz(selected) ~= 1
    error('run_current_factorization_cache_acceptance:ElectrodeSelectionFailed', ...
        'Hemisphere must resolve to one electrode: %s', hemisphere);
end
electrode = subject.electrodes(selected);
end

function task = build_task(subject, electrode, copiedSubject, oneCase, ...
        taskId, phaseId)
reconstructionSource = char(string( ...
    subject.subject_sources.electrode_reconstruction.path));
[~, reconstructionName, reconstructionExtension] = ...
    fileparts(reconstructionSource);
reconstructionPath = must_be_file(fullfile(copiedSubject, 'reconstruction', ...
    [reconstructionName, reconstructionExtension]), ...
    'copied electrode reconstruction');
source = struct( ...
    'source_id', 'current-source-1', ...
    'frequency_hz', oneCase.frequency_hz, ...
    'control_mode', 'current', ...
    'amplitude', oneCase.amplitude_mA, ...
    'pulse_width_us', oneCase.pulse_width_us, ...
    'contacts', oneCase.contacts);
artifacts = { ...
    'efield.nii.gz', ...
    'vta_threshold-0p18Vpermm.nii.gz', ...
    'vta_threshold-0p20Vpermm.nii.gz', ...
    'vta_threshold-0p22Vpermm.nii.gz'};
task = struct( ...
    'task_id', taskId, ...
    'kind', 'continuous_joint', ...
    'subject_id', char(string(subject.subject_id)), ...
    'subject_dir', copiedSubject, ...
    'reconstruction_path', reconstructionPath, ...
    'phase_id', phaseId, ...
    'program_id', 0, ...
    'electrode_id', char(string(electrode.electrode_id)), ...
    'hemisphere', oneCase.hemisphere, ...
    'electrode_model', char(string(electrode.electrode_model)), ...
    'reconstruction_lead_id', double(electrode.reconstruction_lead_id), ...
    'frequency_group_id', 'current-factorization-cache', ...
    'delivery_mode', 'continuous', ...
    'sources', source, ...
    'dependencies', {{}}, ...
    'model', struct( ...
        'gray_matter_s_per_m', 0.33, ...
        'white_matter_s_per_m', 0.14, ...
        'atlas_set', 'Custom_Ewert_Zhang_Middlebrooks', ...
        'spaces', {{'native', 'MNI152NLin2009bAsym'}}, ...
        'thresholds_v_per_m', [180 200 220]), ...
    'run_id', timestamp_iso());
task.output_leaves = struct( ...
    'native', mh_vta_canonical_leaf_path(task, 'native'), ...
    'MNI152NLin2009bAsym', ...
        mh_vta_canonical_leaf_path(task, 'MNI152NLin2009bAsym'));
task.missing_artifacts = struct( ...
    'native', {artifacts}, ...
    'MNI152NLin2009bAsym', {artifacts});
task = mh_vta_validate_canonical_task(task);
end

function payload = physical_payload(task)
payload = struct( ...
    'subject_id', task.subject_id, ...
    'reconstruction_path', task.reconstruction_path, ...
    'electrode_id', task.electrode_id, ...
    'hemisphere', task.hemisphere, ...
    'electrode_model', task.electrode_model, ...
    'reconstruction_lead_id', task.reconstruction_lead_id, ...
    'delivery_mode', task.delivery_mode, ...
    'sources', task.sources, ...
    'model', task.model);
end

function statuses = cache_statuses(events, stage, taskIds)
statuses = strings(numel(taskIds), 1);
for index = 1:numel(taskIds)
    selected = strcmp(events.task_id, taskIds{index}) & ...
        strcmp(events.stage, stage);
    if nnz(selected) ~= 1
        error('run_current_factorization_cache_acceptance:TimingMissing', ...
            'Expected one %s timing event for task %s.', stage, taskIds{index});
    end
    statuses(index) = string(events.cache_status(selected));
end
end

function passed = all_required_artifacts_exist(task)
passed = true;
spaces = {'native', 'MNI152NLin2009bAsym'};
for spaceIndex = 1:numel(spaces)
    space = spaces{spaceIndex};
    leaf = task.output_leaves.(space);
    artifacts = task.missing_artifacts.(space);
    for artifactIndex = 1:numel(artifacts)
        passed = passed && isfile(fullfile(leaf, artifacts{artifactIndex}));
    end
end
end

function event = empty_event()
event = struct( ...
    'task_id', '', ...
    'stage', '', ...
    'status', '', ...
    'cache_status', '', ...
    'duration_seconds', NaN);
end

function runRoot = create_run_root(workRootValue)
workRoot = char(string(workRootValue));
protected = '/Volumes/VAL/STNSNr/derivatives/leaddbs';
canonicalWorkRoot = canonical_path(workRoot);
if startsWith(canonicalWorkRoot, [canonical_path(protected), filesep]) || ...
        strcmp(canonicalWorkRoot, canonical_path(protected))
    error('run_current_factorization_cache_acceptance:UnsafeWorkRoot', ...
        'Validation output cannot be written into the production tree.');
end
if ~isfolder(workRoot)
    mkdir(workRoot);
end
stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss_SSS'));
runRoot = fullfile(workRoot, ...
    ['vta_current_factorization_cache_', stamp]);
if isfolder(runRoot)
    error('run_current_factorization_cache_acceptance:ExistingRunRoot', ...
        'Refusing to overwrite validation root: %s', runRoot);
end
mkdir(runRoot);
end

function copiedSubject = copy_subject_tree(sourceSubject, runRoot)
[datasetRoot, derivativeRoot] = bids_roots(sourceSubject);
[~, subjectLeaf] = fileparts(sourceSubject);
copyRoot = fullfile(runRoot, 'copied_subject');
copiedDerivativeRoot = fullfile(copyRoot, 'derivatives', 'leaddbs');
copiedSubject = fullfile(copiedDerivativeRoot, subjectLeaf);
mkdir(copiedDerivativeRoot);
copy_required(fullfile(datasetRoot, 'dataset_description.json'), ...
    fullfile(copyRoot, 'dataset_description.json'));
derivativeDescription = fullfile(derivativeRoot, 'dataset_description.json');
if isfile(derivativeDescription)
    copy_required(derivativeDescription, ...
        fullfile(copiedDerivativeRoot, 'dataset_description.json'));
end
[ok, message] = copyfile(sourceSubject, copiedSubject);
if ~ok
    error('run_current_factorization_cache_acceptance:SubjectCopyFailed', ...
        'Could not copy subject directory: %s', message);
end
end

function [datasetRoot, derivativeRoot] = bids_roots(subjectDir)
marker = [filesep, 'derivatives', filesep, 'leaddbs', filesep];
markerIndex = strfind(subjectDir, marker);
if numel(markerIndex) ~= 1
    error('run_current_factorization_cache_acceptance:InvalidSubjectPath', ...
        'Subject must be under derivatives/leaddbs: %s', subjectDir);
end
datasetRoot = subjectDir(1:markerIndex - 1);
derivativeRoot = fullfile(datasetRoot, 'derivatives', 'leaddbs');
end

function copy_required(source, target)
must_be_file(source, 'BIDS dataset description');
[ok, message] = copyfile(source, target);
if ~ok
    error('run_current_factorization_cache_acceptance:CopyFailed', ...
        'Could not copy required file: %s', message);
end
end

function value = must_be_file(value, label)
value = char(string(value));
if ~isfile(value)
    error('run_current_factorization_cache_acceptance:MissingFile', ...
        'Missing %s: %s', label, value);
end
end

function value = must_be_folder(value, label)
value = char(string(value));
if ~isfolder(value)
    error('run_current_factorization_cache_acceptance:MissingFolder', ...
        'Missing %s: %s', label, value);
end
end

function path = canonical_path(value)
path = char(java.io.File(char(string(value))).getCanonicalPath());
end

function write_json(path, value)
text = jsonencode(value, 'PrettyPrint', true);
fileId = fopen(path, 'w');
if fileId < 0
    error('run_current_factorization_cache_acceptance:WriteFailed', ...
        'Could not open JSON output: %s', path);
end
cleanupObj = onCleanup(@() fclose(fileId));
fwrite(fileId, text, 'char');
fwrite(fileId, newline, 'char');
end

function value = timestamp_iso()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
