function result = run_current_backend_equivalence(varargin)
% Run deterministic current fixtures or copied-subject backend acceptance.

parser = inputParser;
parser.FunctionName = 'run_current_backend_equivalence';
parser.addParameter('StudyBase', ...
    '/Volumes/VAL/STNSNr/summary/cohort/subj/study_base.json', ...
    @(x) ischar(x) || isstring(x));
parser.addParameter('WorkRoot', '/Volumes/VAL/STNSNr/validation', ...
    @(x) ischar(x) || isstring(x));
parser.addParameter('SubjectId', 'SNr003', @(x) ischar(x) || isstring(x));
parser.addParameter('Seed', 20260712, @is_valid_seed);
parser.addParameter('Mode', 'fem', @(x) ischar(x) || isstring(x));
parser.addParameter('ExistingRunRoot', '', @(x) ischar(x) || isstring(x));
parser.addParameter('TrashRoot', '', @(x) ischar(x) || isstring(x));
parser.addParameter('RecoveryReason', ...
    'canonical_backend_post_runtime_cache_validation', ...
    @(x) ischar(x) && isrow(x) || isstring(x) && isscalar(x));
parser.addParameter('MniRepeatFunction', @generate_mni_repeat, ...
    @(x) isa(x, 'function_handle'));
parser.parse(varargin{:});
opts = parser.Results;
recoveryReason = strtrim(char(string(opts.RecoveryReason)));
if isempty(recoveryReason)
    error('run_current_backend_equivalence:InvalidRecoveryReason', ...
        'RecoveryReason must be nonempty scalar text.');
end

mode = lower(char(string(opts.Mode)));
if ~ismember(mode, {'fem', 'fixture_only', 'compare_existing', ...
        'rerun_candidate'})
    error('run_current_backend_equivalence:InvalidMode', ...
        ['Mode must be fem, fixture_only, compare_existing, or ', ...
         'rerun_candidate.']);
end
assert_safe_work_root(opts.WorkRoot);

if ismember(mode, {'compare_existing', 'rerun_candidate'})
    runRoot = must_be_folder(opts.ExistingRunRoot, ...
        'existing current acceptance run');
    assert_safe_work_root(runRoot);
    if strcmp(mode, 'compare_existing')
        result = compare_existing_run(runRoot, opts.StudyBase, ...
            opts.TrashRoot, opts.MniRepeatFunction);
    else
        result = rerun_existing_candidate(runRoot, opts.StudyBase, ...
            opts.TrashRoot, opts.MniRepeatFunction, recoveryReason);
    end
    return;
end

atlasSet = 'Custom_Ewert_Zhang_Middlebrooks';
thresholdsVPerM = [180 200 220];
if strcmp(mode, 'fixture_only')
    cases = generate_current_cases(double(opts.Seed), {'L', 'R'}, [4 4]);
    result = fixture_result(cases, double(opts.Seed), atlasSet);
    return;
end

repoDir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(genpath(repoDir), '-end');
studyBasePath = must_be_file(opts.StudyBase, 'study-base JSON');
studyDocument = jsondecode(fileread(studyBasePath));
subject = select_subject(studyDocument, opts.SubjectId);
[sides, contactCounts] = subject_electrode_inventory(subject);
fixtureCases = generate_current_cases(double(opts.Seed), sides, contactCounts);
femPlan = official_fem_plan(fixtureCases);
cases = femPlan.cases;

runRoot = create_run_root(opts.WorkRoot);
sourceSubject = must_be_folder( ...
    subject.subject_sources.leaddbs_subject_dir, 'Lead-DBS subject directory');
sourceHashBefore = directory_inventory_hash(sourceSubject);
copiedSubject = copy_subject_tree(sourceSubject, runRoot);

manifest = struct( ...
    'schema_version', 'vta_current_backend_acceptance_v1', ...
    'subject_id', char(string(opts.SubjectId)), ...
    'seed', double(opts.Seed), ...
    'atlas_set', atlasSet, ...
    'thresholds_v_per_m', thresholdsVPerM, ...
    'source_subject', sourceSubject, ...
    'copied_subject', copiedSubject, ...
    'source_tree_sha256_before', sourceHashBefore, ...
    'fixture_sha256', fixture_hash(cases), ...
    'hemisphere', cases.hemisphere, ...
    'case_design', cases.design, ...
    'planned_fem_solve_count', femPlan.planned_fem_solve_count, ...
    'started_at', timestamp_iso(), ...
    'completed_at', '', ...
    'pass', false);
write_json(fullfile(runRoot, 'validation_manifest.json'), manifest);
writetable(case_inventory(cases), fullfile(runRoot, 'case_inventory.csv'));

outputs = run_all_cases(copiedSubject, subject, femPlan, atlasSet, runRoot, ...
    double(opts.Seed));
[efieldMetrics, binaryMetrics, repeatabilityMetrics, comparisonPass] = ...
    compare_all_outputs(cases, outputs);
mniContract = validate_candidate_mni(cases, outputs, runRoot, manifest, ...
    studyBasePath, opts.TrashRoot, opts.MniRepeatFunction);
comparisonPass = comparisonPass && mniContract.pass;
writetable(efieldMetrics, fullfile(runRoot, 'efield_metrics.csv'));
writetable(binaryMetrics, fullfile(runRoot, 'binary_vta_metrics.csv'));
writetable(repeatabilityMetrics, ...
    fullfile(runRoot, 'repeatability_metrics.csv'));
writetable(mniContract.rows, fullfile(runRoot, 'mni_transform_metrics.csv'));

sourceHashAfter = directory_inventory_hash(sourceSubject);
sourceTreeUnchanged = strcmp(sourceHashBefore, sourceHashAfter);
overallPass = comparisonPass && sourceTreeUnchanged;
summary = struct( ...
    'subject_id', char(string(opts.SubjectId)), ...
    'case_count', numel(cases), ...
    'hemisphere', cases.hemisphere, ...
    'case_design', cases.design, ...
    'planned_fem_solve_count', femPlan.planned_fem_solve_count, ...
    'actual_fem_solve_count', femPlan.planned_fem_solve_count, ...
    'comparison_gates_passed', comparisonPass, ...
    'native_equivalence_passed', all(efieldMetrics.pass) && ...
        all(binaryMetrics.pass), ...
    'mni_transform_contract_passed', mniContract.pass, ...
    'production_subject_tree_unchanged', sourceTreeUnchanged, ...
    'pass', overallPass);
write_json(fullfile(runRoot, 'acceptance_summary.json'), summary);

manifest.completed_at = timestamp_iso();
manifest.source_tree_sha256_after = sourceHashAfter;
manifest.pass = overallPass;
write_json(fullfile(runRoot, 'validation_manifest.json'), manifest);
result = struct('mode', mode, 'run_root', runRoot, 'cases', cases, ...
    'summary', summary, 'pass', overallPass);
if ~overallPass
    error('run_current_backend_equivalence:AcceptanceFailed', ...
        'Current backend acceptance failed: %s', runRoot);
end
end

function result = fixture_result(cases, seed, atlasSet)
result = struct( ...
    'mode', 'fixture_only', ...
    'seed', seed, ...
    'atlas_set', atlasSet, ...
    'cases', cases, ...
    'fem_plan', official_fem_plan(cases), ...
    'fixture_sha256', fixture_hash(cases), ...
    'superposition_fixture', vector_superposition_fixture(), ...
    'pass', true);
end

function plan = official_fem_plan(cases)
isSelected = strcmp({cases.hemisphere}, 'R') & ...
    strcmp({cases.design}, 'single_cathode_case_return');
if nnz(isSelected) ~= 1
    error('run_current_backend_equivalence:OfficialFemCaseMissing', ...
        ['Expected exactly one right-sided single-cathode/case-return ', ...
         'current case.']);
end
backends = {'simbio', 'canonical'};
plan = struct( ...
    'cases', cases(isSelected), ...
    'backends', {backends}, ...
    'execution_paths', {{'standard_simbio', 'canonical_backend'}}, ...
    'runs_per_backend', 1, ...
    'planned_fem_solve_count', numel(backends));
end

function cases = generate_current_cases(seed, sides, contactCounts)
previousRng = rng;
cleanupObj = onCleanup(@() rng(previousRng));
rng(seed, 'twister');

if numel(sides) ~= numel(contactCounts) || isempty(sides)
    error('run_current_backend_equivalence:InvalidElectrodeInventory', ...
        'Sides and contact counts must be nonempty and have equal length.');
end
designs = { ...
    'single_cathode_case_return', ...
    'multi_cathode_case_return', ...
    'electrode_return'};
emptyCase = struct( ...
    'case_id', '', ...
    'hemisphere', '', ...
    'design', '', ...
    'control_mode', 'current', ...
    'unit', 'mA', ...
    'amplitude_mA', NaN, ...
    'pulse_width_us', NaN, ...
    'frequency_hz', 130, ...
    'has_case_return', false, ...
    'has_electrode_return', false, ...
    'contacts', empty_contacts());
cases = repmat(emptyCase, 1, numel(sides) * numel(designs));

caseIndex = 0;
for sideIndex = 1:numel(sides)
    side = upper(char(string(sides{sideIndex})));
    contactCount = double(contactCounts(sideIndex));
    if ~ismember(side, {'L', 'R'}) || ~isscalar(contactCount) || ...
            ~isfinite(contactCount) || contactCount < 4 || ...
            contactCount ~= fix(contactCount)
        error('run_current_backend_equivalence:InvalidElectrodeInventory', ...
            'Each hemisphere requires at least four integer contacts.');
    end
    for designIndex = 1:numel(designs)
        caseIndex = caseIndex + 1;
        design = designs{designIndex};
        amplitude = 0.5 + (5.0 - 0.5) * rand();
        pulseWidth = randi([30 120]);
        contactOrder = randperm(contactCount);
        contacts = design_contacts(design, contactOrder);
        cases(caseIndex) = struct( ...
            'case_id', sprintf('%s_%s', side, design), ...
            'hemisphere', side, ...
            'design', design, ...
            'control_mode', 'current', ...
            'unit', 'mA', ...
            'amplitude_mA', amplitude, ...
            'pulse_width_us', pulseWidth, ...
            'frequency_hz', 130, ...
            'has_case_return', endsWith(design, 'case_return'), ...
            'has_electrode_return', strcmp(design, 'electrode_return'), ...
            'contacts', contacts);
    end
end
end

function contacts = design_contacts(design, order)
switch design
    case 'single_cathode_case_return'
        contacts = [ ...
            make_contact(order(1), 'cathode', 1), ...
            make_contact('case', 'anode', 1)];
    case 'multi_cathode_case_return'
        cathodeFractions = normalized_random_fractions(2);
        contacts = [ ...
            make_contact(order(1), 'cathode', cathodeFractions(1)), ...
            make_contact(order(2), 'cathode', cathodeFractions(2)), ...
            make_contact('case', 'anode', 1)];
    case 'electrode_return'
        cathodeFractions = normalized_random_fractions(2);
        anodeFractions = normalized_random_fractions(2);
        contacts = [ ...
            make_contact(order(1), 'cathode', cathodeFractions(1)), ...
            make_contact(order(2), 'cathode', cathodeFractions(2)), ...
            make_contact(order(3), 'anode', anodeFractions(1)), ...
            make_contact(order(4), 'anode', anodeFractions(2))];
    otherwise
        error('run_current_backend_equivalence:InvalidDesign', ...
            'Unsupported current fixture design: %s', design);
end
end

function values = normalized_random_fractions(count)
values = rand(1, count);
values = values / sum(values);
values(end) = 1 - sum(values(1:end-1));
end

function contact = make_contact(identifier, polarity, fraction)
contact = struct('contact', identifier, 'polarity', polarity, ...
    'fraction', fraction);
end

function contacts = empty_contacts()
contacts = repmat(struct('contact', NaN, 'polarity', '', ...
    'fraction', NaN), 1, 0);
end

function evidence = vector_superposition_fixture()
signedSourceVectors = [3 4 0; -1 2 0; 0 -3 4];
combinedVector = sum(signedSourceVectors, 1);
sourceMagnitudes = vecnorm(signedSourceVectors, 2, 2);
combinedMagnitude = norm(combinedVector);
scalarMaximum = max(sourceMagnitudes);
scalarSum = sum(sourceMagnitudes);
evidence = struct( ...
    'signed_source_vectors', signedSourceVectors, ...
    'combined_vector', combinedVector, ...
    'source_magnitudes', sourceMagnitudes, ...
    'combined_magnitude', combinedMagnitude, ...
    'scalar_max_magnitude', scalarMaximum, ...
    'scalar_sum_magnitude', scalarSum, ...
    'signed_linear_superposition_passed', ...
        isequal(combinedVector, sum(signedSourceVectors, 1)), ...
    'scalar_max_rejected', abs(combinedMagnitude - scalarMaximum) > 1e-12, ...
    'scalar_sum_rejected', abs(combinedMagnitude - scalarSum) > 1e-12);
end

function outputs = run_all_cases(copiedSubject, subject, femPlan, ...
        atlasSet, runRoot, seed)
cases = femPlan.cases;
outputs = struct();
for caseIndex = 1:numel(cases)
    oneCase = cases(caseIndex);
    caseField = matlab.lang.makeValidName(oneCase.case_id);
    for backendIndex = 1:numel(femPlan.backends)
        backend = femPlan.backends{backendIndex};
        executionPath = femPlan.execution_paths{backendIndex};
        backendField = matlab.lang.makeValidName(backend);
        label = sprintf('current_equivalence_%s_%s', ...
            backend, oneCase.case_id);
        switch executionPath
            case 'standard_simbio'
                taskResult = execute_standard_backend(copiedSubject, ...
                    oneCase, label, atlasSet, seed + 1000 * caseIndex);
                targetDir = fullfile(runRoot, 'outputs', backend, ...
                    oneCase.case_id);
                mkdir(targetDir);
                outputs.(caseField).(backendField) = struct( ...
                    'native', copy_output(taskResult.efield_native, ...
                        fullfile(targetDir, 'native_efield.nii')), ...
                    'mni', copy_output(taskResult.efield_mni, ...
                        fullfile(targetDir, 'mni_efield.nii')));
            case 'canonical_backend'
                standardOutput = outputs.(caseField).simbio;
                outputs.(caseField).(backendField) = ...
                    execute_canonical_backend(copiedSubject, subject, ...
                        oneCase, atlasSet, runRoot, standardOutput.native);
            otherwise
                error('run_current_backend_equivalence:InvalidExecutionPath', ...
                    'Unsupported FEM execution path: %s', executionPath);
        end
    end
end
end

function taskResult = execute_standard_backend(copiedSubject, oneCase, ...
        label, atlasSet, seed)
backend = 'simbio';
cfg = mh_fiber_default_config(copiedSubject, label);
cfg.forceRecomputeVTA = true;
cfg.vta.modelKey = backend;
cfg.vta.model = mh_fiber_model_name(backend);
cfg.vta.gmAtlas = atlasSet;
cfg.vta.executionMode = 'sequential';
cfg.vta.parallelWorkers = 1;

source = struct( ...
    'side', oneCase.hemisphere, ...
    'amp', oneCase.amplitude_mA, ...
    'unit', 'mA', ...
    'pulseWidth', oneCase.pulse_width_us, ...
    'frequency', oneCase.frequency_hz, ...
    'controlMode', 'current', ...
    'contacts', oneCase.contacts);
stimSpec = struct( ...
    'label', label, ...
    'model', backend, ...
    'space', 'MNI152NLin2009bAsym', ...
    'sources', source);
[taskResults, ~, ~, ~, ~] = mh_vta_run_stim_spec_tasks( ...
    cfg, stimSpec, {oneCase.hemisphere}, ...
    'ModelKey', backend, ...
    'Force', true, ...
    'OutputSpaces', {'native', 'mni'}, ...
    'ExportThresholdVPerMm', 0.18, ...
    'GmAtlas', atlasSet, ...
    'RngSeedBase', seed);
if numel(taskResults) ~= 1 || ~strcmp(taskResults.status, 'complete')
    error('run_current_backend_equivalence:BackendRunFailed', ...
        'Backend %s did not return one complete task.', backend);
end
taskResult = taskResults;
end

function output = execute_canonical_backend(copiedSubject, subject, ...
        oneCase, atlasSet, runRoot, nativeComparisonAnchor)
electrode = select_electrode(subject, oneCase.hemisphere);
reconstructionSource = char(string( ...
    subject.subject_sources.electrode_reconstruction.path));
[~, reconstructionName, reconstructionExtension] = fileparts(reconstructionSource);
reconstructionPath = must_be_file(fullfile(copiedSubject, 'reconstruction', ...
    [reconstructionName, reconstructionExtension]), ...
    'copied electrode reconstruction');
nativeLeaf = fullfile(runRoot, 'outputs', 'canonical', ...
    oneCase.case_id, 'native');
mniLeaf = fullfile(runRoot, 'outputs', 'canonical', ...
    oneCase.case_id, 'MNI152NLin2009bAsym');
source = struct( ...
    'source_id', 'current-source-1', ...
    'frequency_hz', oneCase.frequency_hz, ...
    'control_mode', 'current', ...
    'amplitude', oneCase.amplitude_mA, ...
    'pulse_width_us', oneCase.pulse_width_us, ...
    'contacts', oneCase.contacts);
allArtifacts = { ...
    'efield.nii.gz', ...
    'vta_threshold-0p18Vpermm.nii.gz', ...
    'vta_threshold-0p20Vpermm.nii.gz', ...
    'vta_threshold-0p22Vpermm.nii.gz'};
task = struct( ...
    'task_id', ['current-acceptance-', lower(oneCase.hemisphere)], ...
    'kind', 'continuous_joint', ...
    'subject_id', char(string(subject.subject_id)), ...
    'subject_dir', copiedSubject, ...
    'reconstruction_path', reconstructionPath, ...
    'phase_id', 'acceptance', ...
    'program_id', 0, ...
    'electrode_id', char(string(electrode.electrode_id)), ...
    'hemisphere', oneCase.hemisphere, ...
    'electrode_model', char(string(electrode.electrode_model)), ...
    'reconstruction_lead_id', double(electrode.reconstruction_lead_id), ...
    'frequency_group_id', 'current-acceptance', ...
    'delivery_mode', 'continuous', ...
    'sources', source, ...
    'dependencies', {{}}, ...
    'model', struct( ...
        'gray_matter_s_per_m', 0.33, ...
        'white_matter_s_per_m', 0.14, ...
        'atlas_set', atlasSet, ...
        'spaces', {{'native', 'MNI152NLin2009bAsym'}}, ...
        'thresholds_v_per_m', [180 200 220]), ...
    'run_id', timestamp_iso(), ...
    'output_leaves', struct( ...
        'native', nativeLeaf, ...
        'MNI152NLin2009bAsym', mniLeaf), ...
    'missing_artifacts', struct( ...
        'native', {allArtifacts}, ...
        'MNI152NLin2009bAsym', {allArtifacts}));
task = mh_vta_validate_canonical_task(task);
status = mh_vta_backend_simbio_onesolve_canonical(task, ...
    'NativeAnchorPath', nativeComparisonAnchor);
if ~strcmp(status.headmodel_state, 'reused')
    error('run_current_backend_equivalence:HeadmodelNotReused', ...
        'Canonical one-solve must reuse the standard SimBio headmodel.');
end
output = struct( ...
    'native', must_be_file(status.native_efield, ...
        'canonical native E-field'), ...
    'mni', must_be_file(status.mni_efield, ...
        'canonical MNI E-field'));
end

function [efieldRows, binaryRows, repeatRows, passed] = ...
        compare_all_outputs(cases, outputs)
efieldRows = table();
binaryRows = table();
repeatRows = table();
passed = true;
spaces = {'native'};
for caseIndex = 1:numel(cases)
    oneCase = cases(caseIndex);
    caseField = matlab.lang.makeValidName(oneCase.case_id);
    standard = outputs.(caseField).simbio;
    canonical = outputs.(caseField).canonical;
    for spaceIndex = 1:numel(spaces)
        space = spaces{spaceIndex};
        comparison = mh_compare_single_source_backend_outputs( ...
            standard.(space), canonical.(space), ...
            'Space', space, ...
            'Side', oneCase.hemisphere, ...
            'Comparison', 'equivalence', ...
            'ResampleCandidateToReference', false, ...
            'ThrowOnFailure', false);
        efield = annotate_rows(comparison.efield_row, oneCase.case_id, ...
            'backend');
        binary = annotate_rows(comparison.binary_rows, oneCase.case_id, ...
            'backend');
        efieldRows = [efieldRows; efield]; %#ok<AGROW>
        binaryRows = [binaryRows; binary]; %#ok<AGROW>
        passed = passed && comparison.pass;
    end
end
if ~isempty(efieldRows)
    repeatRows = efieldRows([],:);
end
end

function result = validate_candidate_mni(cases, outputs, runRoot, manifest, ...
        studyBasePath, trashRoot, repeatFunction)
thresholds = [180, 200, 220];
rows = table();
passed = true;
for caseIndex = 1:numel(cases)
    oneCase = cases(caseIndex);
    caseField = matlab.lang.makeValidName(oneCase.case_id);
    candidate = outputs.(caseField).canonical;
    repeatPath = fullfile(runRoot, 'mni_transform_repeat', ...
        [oneCase.case_id, '.nii.gz']);
    if isfile(repeatPath)
        mh_vta_move_path_to_trash(repeatPath, 'TrashRoot', trashRoot);
    end
    context = struct( ...
        'manifest', manifest, ...
        'study_base_path', char(string(studyBasePath)), ...
        'case', oneCase);
    repeatFunction(candidate.native, candidate.mni, repeatPath, context);
    mniLeaf = fileparts(candidate.mni);
    thresholdPaths = threshold_artifact_paths(mniLeaf, thresholds);
    validation = mh_validate_canonical_mni_outputs( ...
        candidate.mni, repeatPath, thresholdPaths, thresholds, ...
        'ThrowOnFailure', false);
    thresholdPass = all(validation.threshold_rows.pass);
    row = table(string(oneCase.case_id), ...
        validation.dimensions_match, validation.affine_match, ...
        validation.finite_mask_match, validation.finite_nonzero_signal, ...
        validation.deterministic_repeat, thresholdPass, validation.pass, ...
        'VariableNames', {'case_id', 'dimensions_match', 'affine_match', ...
            'finite_mask_match', 'finite_nonzero_signal', ...
            'deterministic_repeat', 'thresholds_match', 'pass'});
    rows = [rows; row]; %#ok<AGROW>
    passed = passed && validation.pass;
end
result = struct('rows', rows, 'pass', passed);
end

function generate_mni_repeat(nativePath, ~, repeatPath, context)
manifest = context.manifest;
studyDocument = jsondecode(fileread(must_be_file( ...
    context.study_base_path, 'study-base JSON')));
subject = select_subject(studyDocument, manifest.subject_id);
copiedSubject = must_be_folder(manifest.copied_subject, ...
    'copied Lead-DBS subject directory');
sourceReconstruction = char(string( ...
    subject.subject_sources.electrode_reconstruction.path));
[~, reconstructionName, reconstructionExtension] = ...
    fileparts(sourceReconstruction);
reconstructionPath = must_be_file(fullfile(copiedSubject, ...
    'reconstruction', [reconstructionName, reconstructionExtension]), ...
    'copied electrode reconstruction');
options = ea_getptopts(copiedSubject, struct());
options.subj.recon.recon = reconstructionPath;
mniReference = fullfile(ea_space(options), 't1.nii');
parent = fileparts(repeatPath);
if ~isfolder(parent)
    mkdir(parent);
end
mh_vta_transform_efield_to_mni(nativePath, options, mniReference, repeatPath);
end

function paths = threshold_artifact_paths(leaf, thresholds)
paths = cell(1, numel(thresholds));
for index = 1:numel(thresholds)
    token = strrep(sprintf('%.2f', thresholds(index) / 1000), '.', 'p');
    paths{index} = must_be_file(fullfile(leaf, ...
        ['vta_threshold-', token, 'Vpermm.nii.gz']), ...
        'canonical MNI threshold');
end
end

function result = compare_existing_run(runRoot, studyBasePath, trashRoot, ...
        repeatFunction)
manifestPath = fullfile(runRoot, 'validation_manifest.json');
manifest = jsondecode(fileread(must_be_file(manifestPath, ...
    'current acceptance manifest')));
required = {'subject_id', 'hemisphere', 'case_design', ...
    'planned_fem_solve_count'};
if ~all(isfield(manifest, required)) || ...
        ~strcmp(char(string(manifest.hemisphere)), 'R') || ...
        ~strcmp(char(string(manifest.case_design)), ...
            'single_cathode_case_return') || ...
        double(manifest.planned_fem_solve_count) ~= 2
    error('run_current_backend_equivalence:InvalidExistingRun', ...
        'Existing run does not satisfy the fixed current FEM contract.');
end

caseId = 'R_single_cathode_case_return';
oneCase = struct('case_id', caseId, 'hemisphere', 'R');
caseField = matlab.lang.makeValidName(caseId);
standardRoot = fullfile(runRoot, 'outputs', 'simbio', caseId);
candidateRoot = resolve_candidate_root(runRoot, caseId);
outputs.(caseField).simbio = struct( ...
    'native', first_existing_file({ ...
        fullfile(standardRoot, 'native_efield.nii'), ...
        fullfile(standardRoot, 'native_efield.nii.gz')}), ...
    'mni', first_existing_file({ ...
        fullfile(standardRoot, 'mni_efield.nii'), ...
        fullfile(standardRoot, 'mni_efield.nii.gz')}));
outputs.(caseField).canonical = struct( ...
    'native', first_existing_file({ ...
        fullfile(candidateRoot, 'native', 'efield.nii.gz'), ...
        fullfile(candidateRoot, 'native', 'efield.nii')}), ...
    'mni', first_existing_file({ ...
        fullfile(candidateRoot, 'MNI152NLin2009bAsym', 'efield.nii.gz'), ...
        fullfile(candidateRoot, 'MNI152NLin2009bAsym', 'efield.nii')}));

[efieldMetrics, binaryMetrics, repeatabilityMetrics, comparisonPass] = ...
    compare_all_outputs(oneCase, outputs);
mniContract = validate_candidate_mni(oneCase, outputs, runRoot, manifest, ...
    studyBasePath, trashRoot, repeatFunction);
comparisonPass = comparisonPass && mniContract.pass;
replace_table_safely(efieldMetrics, ...
    fullfile(runRoot, 'efield_metrics.csv'), trashRoot);
replace_table_safely(binaryMetrics, ...
    fullfile(runRoot, 'binary_vta_metrics.csv'), trashRoot);
replace_table_safely(repeatabilityMetrics, ...
    fullfile(runRoot, 'repeatability_metrics.csv'), trashRoot);
replace_table_safely(mniContract.rows, ...
    fullfile(runRoot, 'mni_transform_metrics.csv'), trashRoot);

summaryPath = fullfile(runRoot, 'acceptance_summary.json');
if isfile(summaryPath)
    summary = jsondecode(fileread(summaryPath));
else
    summary = struct();
end
productionTreeUnchanged = isfield(summary, ...
    'production_subject_tree_unchanged') && ...
    isscalar(summary.production_subject_tree_unchanged) && ...
    logical(summary.production_subject_tree_unchanged);
summary.subject_id = char(string(manifest.subject_id));
summary.case_count = 1;
summary.hemisphere = 'R';
summary.case_design = 'single_cathode_case_return';
summary.planned_fem_solve_count = 2;
actualFemSolveCounts = 2;
if isfield(summary, 'actual_fem_solve_count') && ...
        isnumeric(summary.actual_fem_solve_count) && ...
        isscalar(summary.actual_fem_solve_count) && ...
        isfinite(summary.actual_fem_solve_count) && ...
        summary.actual_fem_solve_count >= 2
    actualFemSolveCounts(end + 1) = ...
        double(summary.actual_fem_solve_count);
end
if isfield(manifest, 'accumulated_fem_solve_count') && ...
        isnumeric(manifest.accumulated_fem_solve_count) && ...
        isscalar(manifest.accumulated_fem_solve_count) && ...
        isfinite(manifest.accumulated_fem_solve_count) && ...
        manifest.accumulated_fem_solve_count >= 2
    actualFemSolveCounts(end + 1) = ...
        double(manifest.accumulated_fem_solve_count);
end
summary.actual_fem_solve_count = max(actualFemSolveCounts);
summary.comparison_fem_solve_count = 0;
summary.comparison_grid = 'standard_simbio_reference_grid';
summary.comparison_gates_passed = comparisonPass;
summary.native_equivalence_passed = all(efieldMetrics.pass) && ...
    all(binaryMetrics.pass);
summary.mni_transform_contract_passed = mniContract.pass;
summary.production_subject_tree_unchanged = productionTreeUnchanged;
summary.pass = comparisonPass && productionTreeUnchanged;
replace_json_safely(summaryPath, summary, trashRoot);

result = struct( ...
    'mode', 'compare_existing', ...
    'run_root', runRoot, ...
    'fem_solve_count', 0, ...
    'summary', summary, ...
    'pass', summary.pass);
end

function result = rerun_existing_candidate(runRoot, studyBasePath, trashRoot, ...
        repeatFunction, recoveryReason)
manifestPath = fullfile(runRoot, 'validation_manifest.json');
manifest = jsondecode(fileread(must_be_file(manifestPath, ...
    'current acceptance manifest')));
required = {'subject_id', 'seed', 'atlas_set', 'copied_subject', ...
    'source_subject', 'source_tree_sha256_before', 'fixture_sha256', ...
    'hemisphere', 'case_design', 'planned_fem_solve_count'};
if ~all(isfield(manifest, required)) || ...
        ~strcmp(char(string(manifest.hemisphere)), 'R') || ...
        ~strcmp(char(string(manifest.case_design)), ...
            'single_cathode_case_return') || ...
        double(manifest.planned_fem_solve_count) ~= 2
    error('run_current_backend_equivalence:InvalidExistingRun', ...
        'Existing run does not satisfy the fixed current recovery contract.');
end

studyDocument = jsondecode(fileread(must_be_file(studyBasePath, ...
    'study-base JSON')));
subject = select_subject(studyDocument, manifest.subject_id);
[sides, contactCounts] = subject_electrode_inventory(subject);
fixtureCases = generate_current_cases(double(manifest.seed), sides, ...
    contactCounts);
femPlan = official_fem_plan(fixtureCases);
oneCase = femPlan.cases;
if ~strcmp(fixture_hash(oneCase), char(string(manifest.fixture_sha256)))
    error('run_current_backend_equivalence:FixtureMismatch', ...
        'Regenerated current fixture does not match the existing run.');
end

copiedSubject = must_be_folder(manifest.copied_subject, ...
    'copied Lead-DBS subject directory');
sourceSubject = must_be_folder(manifest.source_subject, ...
    'production Lead-DBS subject directory');
sourceHashBeforeRecovery = directory_inventory_hash(sourceSubject);
sourceChangedSinceOriginal = ~strcmp(sourceHashBeforeRecovery, ...
    char(string(manifest.source_tree_sha256_before)));

caseId = oneCase.case_id;
standardRoot = fullfile(runRoot, 'outputs', 'simbio', caseId);
standardNative = first_existing_file({ ...
    fullfile(standardRoot, 'native_efield.nii'), ...
    fullfile(standardRoot, 'native_efield.nii.gz')});
first_existing_file({ ...
    fullfile(standardRoot, 'mni_efield.nii'), ...
    fullfile(standardRoot, 'mni_efield.nii.gz')});
candidateRoot = resolve_candidate_root(runRoot, caseId);
if ~isfolder(candidateRoot)
    error('run_current_backend_equivalence:InvalidExistingRun', ...
        'Existing candidate directory is missing: %s', candidateRoot);
end

priorAttempts = 0;
if isfield(manifest, 'recovery_attempt_count')
    priorAttempts = double(manifest.recovery_attempt_count);
end
recoveryAttempt = priorAttempts + 1;
recoveryStartedAt = timestamp_iso();
manifest.recovery_attempt_count = recoveryAttempt;
manifest.recovery_started_at = recoveryStartedAt;
manifest.recovery_completed_at = '';
manifest.source_tree_sha256_before_recovery = sourceHashBeforeRecovery;
manifest.source_tree_changed_since_original_acceptance = ...
    sourceChangedSinceOriginal;
manifest.accumulated_fem_solve_count = ...
    double(manifest.planned_fem_solve_count) + recoveryAttempt;
manifest.pass = false;
replace_json_safely(manifestPath, manifest, trashRoot);

mh_vta_move_path_to_trash(candidateRoot, 'TrashRoot', trashRoot);

execute_canonical_backend(copiedSubject, subject, oneCase, ...
    char(string(manifest.atlas_set)), runRoot, standardNative);
comparison = compare_existing_run(runRoot, studyBasePath, trashRoot, ...
    repeatFunction);

sourceHashAfterRecovery = directory_inventory_hash(sourceSubject);
productionTreeUnchanged = strcmp(sourceHashBeforeRecovery, ...
    sourceHashAfterRecovery);
summary = comparison.summary;
summary.actual_fem_solve_count = manifest.accumulated_fem_solve_count;
summary.recovery_attempt_count = recoveryAttempt;
summary.latest_recovery_fem_solve_count = 1;
summary.standard_reference_reused = true;
summary.recovery_reason = char(string(recoveryReason));
summary.production_subject_tree_changed_since_original_acceptance = ...
    sourceChangedSinceOriginal;
summary.production_subject_tree_unchanged_during_recovery = ...
    productionTreeUnchanged;
summary.production_subject_tree_unchanged = productionTreeUnchanged;
summary.pass = summary.comparison_gates_passed && productionTreeUnchanged;
replace_json_safely(fullfile(runRoot, 'acceptance_summary.json'), ...
    summary, trashRoot);

manifest.recovery_completed_at = timestamp_iso();
manifest.latest_recovery_fem_solve_count = 1;
manifest.source_tree_sha256_after_recovery = sourceHashAfterRecovery;
manifest.production_subject_tree_unchanged_during_recovery = ...
    productionTreeUnchanged;
manifest.pass = summary.pass;
replace_json_safely(manifestPath, manifest, trashRoot);

result = struct( ...
    'mode', 'rerun_candidate', ...
    'run_root', runRoot, ...
    'fem_solve_count', 1, ...
    'summary', summary, ...
    'pass', summary.pass);
if ~result.pass
    error('run_current_backend_equivalence:AcceptanceFailed', ...
        'Recovered current backend acceptance failed: %s', runRoot);
end
end

function replace_table_safely(value, path, trashRoot)
move_existing_to_trash(path, trashRoot);
writetable(value, path);
end

function replace_json_safely(path, value, trashRoot)
move_existing_to_trash(path, trashRoot);
write_json(path, value);
end

function move_existing_to_trash(path, trashRoot)
if ~isfile(path)
    return;
end
mh_vta_move_path_to_trash(path, 'TrashRoot', trashRoot);
end

function path = first_existing_file(candidates)
matching = candidates(cellfun(@isfile, candidates));
if numel(matching) ~= 1
    error('run_current_backend_equivalence:InvalidExistingRun', ...
        'Expected exactly one existing E-field path from: %s', ...
        strjoin(candidates, ', '));
end
path = matching{1};
end

function path = resolve_candidate_root(runRoot, caseId)
candidates = { ...
    fullfile(runRoot, 'outputs', 'canonical', caseId), ...
    fullfile(runRoot, 'outputs', 'simbio_onesolve', caseId)};
for index = 1:numel(candidates)
    if isfolder(candidates{index})
        path = candidates{index};
        return;
    end
end
error('run_current_backend_equivalence:InvalidExistingRun', ...
    'Existing canonical candidate directory is missing for %s.', caseId);
end

function rows = annotate_rows(rows, caseId, backendComparison)
rows = addvars(rows, repmat(string(caseId), height(rows), 1), ...
    repmat(string(backendComparison), height(rows), 1), ...
    'Before', 1, 'NewVariableNames', {'case_id', 'backend_comparison'});
end

function inventory = case_inventory(cases)
inventory = table( ...
    string({cases.case_id})', ...
    string({cases.hemisphere})', ...
    string({cases.design})', ...
    [cases.amplitude_mA]', ...
    [cases.pulse_width_us]', ...
    [cases.frequency_hz]', ...
    [cases.has_case_return]', ...
    [cases.has_electrode_return]', ...
    'VariableNames', {'case_id', 'hemisphere', 'design', 'amplitude_mA', ...
        'pulse_width_us', 'frequency_hz', 'has_case_return', ...
        'has_electrode_return'});
end

function subject = select_subject(document, subjectId)
if ~isstruct(document) || ~isfield(document, 'schema_version') || ...
        ~strcmp(char(string(document.schema_version)), ...
            'dual_frequency_study_v1') || ...
        ~isfield(document, 'study') || ...
        ~isfield(document.study, 'subjects')
    error('run_current_backend_equivalence:InvalidStudyBase', ...
        'Study-base JSON does not satisfy the required study contract.');
end
subjects = document.study.subjects;
matching = arrayfun(@(value) strcmp(char(string(value.subject_id)), ...
    char(string(subjectId))), subjects);
if nnz(matching) ~= 1
    error('run_current_backend_equivalence:SubjectSelectionFailed', ...
        'Expected exactly one subject matching %s.', char(string(subjectId)));
end
subject = subjects(matching);
end

function electrode = select_electrode(subject, hemisphere)
electrodes = subject.electrodes;
matching = strcmpi(string({electrodes.hemisphere}), string(hemisphere));
if nnz(matching) ~= 1
    error('run_current_backend_equivalence:ElectrodeSelectionFailed', ...
        'Expected exactly one %s electrode.', char(string(hemisphere)));
end
electrode = electrodes(matching);
end

function [sides, contactCounts] = subject_electrode_inventory(subject)
electrodes = subject.electrodes;
sides = cell(1, numel(electrodes));
contactCounts = zeros(1, numel(electrodes));
for index = 1:numel(electrodes)
    sides{index} = upper(char(string(electrodes(index).hemisphere)));
    contactCounts(index) = double(electrodes(index).contact_count);
end
[sides, order] = sort(sides);
contactCounts = contactCounts(order);
if ~isequal(string(sides), ["L" "R"])
    error('run_current_backend_equivalence:BilateralCasesRequired', ...
        'Current acceptance requires one left and one right electrode.');
end
end

function runRoot = create_run_root(workRootValue)
workRoot = char(string(workRootValue));
if ~isfolder(workRoot)
    mkdir(workRoot);
end
stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss_SSS'));
runRoot = fullfile(workRoot, ...
    ['vta_current_backend_equivalence_', stamp]);
if isfolder(runRoot)
    error('run_current_backend_equivalence:ExistingValidationRoot', ...
        'Refusing to overwrite validation root: %s', runRoot);
end
mkdir(runRoot);
end

function copiedSubject = copy_subject_tree(sourceSubject, runRoot)
[datasetRoot, derivativeRoot] = bids_roots(sourceSubject);
[~, subjectLeaf] = fileparts(sourceSubject);
copyRoot = fullfile(runRoot, 'copied_subject');
copiedDerivativeRoot = fullfile(copyRoot, 'derivatives', 'leaddbs');
copiedSubject = fullfile(copiedDerivativeRoot, subjectLeaf);
mkdir(copiedDerivativeRoot);
copy_required_file(fullfile(datasetRoot, 'dataset_description.json'), ...
    fullfile(copyRoot, 'dataset_description.json'));
copy_optional_file(fullfile(derivativeRoot, 'dataset_description.json'), ...
    fullfile(copiedDerivativeRoot, 'dataset_description.json'));
[ok, message] = copyfile(sourceSubject, copiedSubject);
if ~ok
    error('run_current_backend_equivalence:SubjectCopyFailed', ...
        'Could not copy subject directory: %s', message);
end
end

function [datasetRoot, derivativeRoot] = bids_roots(subjectDir)
marker = [filesep, 'derivatives', filesep, 'leaddbs', filesep];
markerIndex = strfind(subjectDir, marker);
if numel(markerIndex) ~= 1
    error('run_current_backend_equivalence:InvalidBidsSubjectPath', ...
        'Subject must be under derivatives/leaddbs: %s', subjectDir);
end
datasetRoot = subjectDir(1:markerIndex - 1);
derivativeRoot = fullfile(datasetRoot, 'derivatives', 'leaddbs');
end

function copy_required_file(source, target)
must_be_file(source, 'BIDS dataset description');
[ok, message] = copyfile(source, target);
if ~ok
    error('run_current_backend_equivalence:CopyFailed', ...
        'Could not copy required BIDS file: %s', message);
end
end

function copy_optional_file(source, target)
if isfile(source)
    [ok, message] = copyfile(source, target);
    if ~ok
        error('run_current_backend_equivalence:CopyFailed', ...
            'Could not copy optional BIDS file: %s', message);
    end
end
end

function target = copy_output(source, target)
source = must_be_file(source, 'backend E-field');
if endsWith(source, '.nii.gz')
    target = [erase(target, '.nii'), '.nii.gz'];
end
[ok, message] = copyfile(source, target);
if ~ok
    error('run_current_backend_equivalence:OutputCopyFailed', ...
        'Could not copy backend output: %s', message);
end
end

function assert_safe_work_root(value)
root = canonical_path(value);
production = canonical_path('/Volumes/VAL/STNSNr/derivatives/leaddbs');
rootPrefix = [root, filesep];
productionPrefix = [production, filesep];
if strcmp(root, production) || startsWith(rootPrefix, productionPrefix) || ...
        startsWith(productionPrefix, rootPrefix)
    error('mh_vta_acceptance:UnsafeWorkRoot', ...
        'WorkRoot must be outside the production Lead-DBS derivatives tree.');
end
end

function path = canonical_path(value)
path = char(java.io.File(char(string(value))).getCanonicalPath());
while numel(path) > 1 && path(end) == filesep
    path(end) = [];
end
end

function hash = fixture_hash(cases)
hash = sha256_text(jsonencode(cases));
end

function hash = directory_inventory_hash(root)
files = dir(fullfile(root, '**', '*'));
files = files(~[files.isdir]);
relativePaths = strings(1, numel(files));
for index = 1:numel(files)
    fullPath = fullfile(files(index).folder, files(index).name);
    relativePaths(index) = string(erase(fullPath, [root, filesep]));
end
relativePaths = sort(relativePaths);
parts = strings(1, numel(relativePaths));
for index = 1:numel(relativePaths)
    path = fullfile(root, char(relativePaths(index)));
    parts(index) = relativePaths(index) + ":" + ...
        string(mh_fiber_file_sha256(path));
end
hash = sha256_text(strjoin(parts, newline));
end

function hash = sha256_text(value)
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(unicode2native(char(string(value)), 'UTF-8'));
bytes = typecast(digest.digest(), 'uint8');
hash = lower(reshape(dec2hex(bytes, 2)', 1, []));
end

function path = must_be_file(value, label)
path = char(string(value));
if ~isfile(path)
    error('run_current_backend_equivalence:MissingFile', ...
        'Required %s does not exist: %s', label, path);
end
end

function path = must_be_folder(value, label)
path = char(string(value));
if ~isfolder(path)
    error('run_current_backend_equivalence:MissingFolder', ...
        'Required %s does not exist: %s', label, path);
end
end

function valid = is_valid_seed(value)
valid = isnumeric(value) && isscalar(value) && isfinite(value) && ...
    value >= 0 && value == fix(value);
end

function write_json(path, value)
text = jsonencode(value, PrettyPrint=true);
fid = fopen(path, 'w');
if fid < 0
    error('run_current_backend_equivalence:WriteFailed', ...
        'Could not write JSON: %s', path);
end
cleanupObj = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', text);
end

function value = timestamp_iso()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
