function test_run_voltage_backend_equivalence()
% Validate the real-data acceptance runner contract without running FEM.

repoDir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(genpath(repoDir));

testRoot = tempname;
sourceDataset = fullfile(testRoot, 'source');
sourceSubject = fullfile(sourceDataset, 'derivatives', 'leaddbs', ...
    'sub-Test003');
workRoot = fullfile(testRoot, 'validation');
stubDir = fullfile(testRoot, 'stubs');
mkdir(sourceSubject);
mkdir(workRoot);
mkdir(stubDir);
cleanupObj = onCleanup(@() cleanup_test(testRoot, stubDir));

assert_error_id(@() run_voltage_backend_equivalence( ...
    'StudyBase', fullfile(testRoot, 'missing.json'), ...
    'WorkRoot', '/Volumes/VAL/STNSNr/derivatives/leaddbs'), ...
    'mh_vta_acceptance:UnsafeWorkRoot');

write_text(fullfile(sourceDataset, 'dataset_description.json'), ...
    jsonencode(struct('Name', 'Synthetic VTA acceptance', ...
    'BIDSVersion', '1.6.0', 'DatasetType', 'raw'), PrettyPrint=true));
write_fixture_subject(sourceSubject);
studyBase = fullfile(testRoot, 'study_base.json');
write_study_base(studyBase, sourceSubject);
write_vta_stubs(stubDir);
addpath(stubDir, '-begin');
rehash;
test_explicit_horn_seed(testRoot);
test_process_space_override();

result = run_voltage_backend_equivalence( ...
    'StudyBase', studyBase, ...
    'WorkRoot', workRoot, ...
    'SubjectId', 'Test003', ...
    'PhaseId', 'T1', ...
    'ProgramId', 1, ...
    'ReusePreparedRoot', false);

assert(isfolder(result.run_root), 'Runner did not create a validation root.');
assert(isfile(fullfile(result.run_root, 'validation_manifest.json')), ...
    'Runner did not write the validation manifest.');
assert(isfile(fullfile(result.run_root, 'case_inventory.csv')), ...
    'Runner did not write the case inventory.');
assert(isfile(fullfile(result.run_root, 'headmodel_hashes.csv')), ...
    'Runner did not write head-model hashes.');
assert(isfile(fullfile(result.run_root, 'acceptance_summary.json')), ...
    'Runner did not write the acceptance summary.');

inventory = readtable(fullfile(result.run_root, 'case_inventory.csv'), ...
    'TextType', 'string');
assert(isequal(sort(inventory.side), ["L"; "R"]), ...
    'Runner did not select exactly one source per hemisphere.');
assert(all(inventory.frequency_hz == 130), ...
    'Runner did not preserve source frequency.');

hashes = readtable(fullfile(result.run_root, 'headmodel_hashes.csv'), ...
    'TextType', 'string');
assert(nnz(hashes.run_kind == "preparation") == 2, ...
    'Each hemisphere must have one explicit head-model preparation row.');
assert(nnz(hashes.run_kind == "measured") == 8, ...
    'Each hemisphere must have four measured backend rows.');
assert(all(hashes.hash_created(hashes.run_kind == "preparation")), ...
    'Preparation must create the shared head model.');
assert(all(hashes.hash_unchanged(hashes.run_kind == "measured")), ...
    'Measured backend runs must not modify the shared head model.');
for caseId = unique(hashes.case_id)'
    caseRows = hashes.case_id == caseId;
    caseSeeds = unique(hashes.actual_rng_seed(caseRows));
    assert(isscalar(caseSeeds), ...
        'Preparation, backends, and repeats must use the same actual RNG seed.');
    measuredLabels = hashes.stimulation_label(caseRows & ...
        hashes.run_kind == "measured");
    assert(numel(unique(measuredLabels)) == 4, ...
        'Measured backend/repeat runs must use distinct output labels.');
end

manifest = jsondecode(fileread(fullfile(result.run_root, 'validation_manifest.json')));
assert(strcmp(manifest.subject_id, 'Test003'), 'Manifest subject mismatch.');
assert(contains(string(manifest.copied_subject_dir), ...
    fullfile('copied_subject', 'derivatives', 'leaddbs', 'sub-Test003')), ...
    'Copied subject must preserve the Lead-DBS BIDS derivative layout.');
assert(isfile(fullfile(result.run_root, 'copied_subject', ...
    'dataset_description.json')), ...
    'Copied BIDS root must contain dataset_description.json.');
assert(strcmp(manifest.atlas_set, 'Custom_Ewert_Zhang_Middlebrooks'), ...
    'Manifest atlas mismatch.');
assert(strcmp(manifest.template_space, 'MNI152NLin2009bAsym'), ...
    'Manifest template-space mismatch.');
assert(isequal(manifest.thresholds_v_per_m(:)', [180 200 220]), ...
    'Manifest threshold mismatch.');
assert(~manifest.official_pilot, ...
    'A synthetic override must not be reported as the official pilot.');

summary = jsondecode(fileread(fullfile(result.run_root, 'acceptance_summary.json')));
assert(summary.pass, 'Identical stub outputs should pass acceptance.');
assert(summary.rng_streams_matched, ...
    'Acceptance summary must record matched actual RNG streams.');
assert(summary.native_equivalence_passed, ...
    'Acceptance summary must record native backend equivalence.');
assert(summary.mni_transform_contract_passed, ...
    'Acceptance summary must record the canonical MNI transform contract.');
assert(isequal(string(manifest.backends(:))', ["simbio" "canonical"]), ...
    'The voltage gate must compare standard SimBio with the canonical backend.');
assert(nnz(hashes.backend == "canonical") == 4, ...
    'Each hemisphere must run the canonical backend twice.');

trashRoot = fullfile(testRoot, 'voltage-compare-trash');
comparison = run_voltage_backend_equivalence( ...
    'Mode', 'compare_existing', ...
    'ExistingRunRoot', result.run_root, ...
    'TrashRoot', trashRoot);
assert(strcmp(comparison.mode, 'compare_existing'), ...
    'Voltage comparison must report compare_existing mode.');
assert(comparison.fem_solve_count == 0, ...
    'Voltage comparison must not run FEM.');
assert(comparison.pass, ...
    'Existing identical voltage outputs must pass re-comparison.');
trashed = dir(fullfile(trashRoot, '*'));
assert(nnz(~[trashed.isdir]) >= 4, ...
    'Replaced voltage tables and summaries must move to Trash.');

didFail = false;
try
    run_voltage_backend_equivalence( ...
        'StudyBase', studyBase, ...
        'WorkRoot', result.run_root, ...
        'SubjectId', 'Test003', ...
        'PhaseId', 'T1', ...
        'ProgramId', 1, ...
        'ReusePreparedRoot', false);
catch ME
    didFail = strcmp(ME.identifier, ...
        'run_voltage_backend_equivalence:ExistingValidationRoot');
end
assert(didFail, 'Runner should refuse to overwrite an existing validation root.');

didFail = false;
try
    run_voltage_backend_equivalence( ...
        'StudyBase', studyBase, ...
        'WorkRoot', result.run_root, ...
        'SubjectId', 'Test003', ...
        'PhaseId', 'T1', ...
        'ProgramId', 1, ...
        'ReusePreparedRoot', true);
catch ME
    didFail = strcmp(ME.identifier, ...
        'run_voltage_backend_equivalence:PreparedRootNotOutputFree');
end
assert(didFail, 'Reuse must reject a validation root containing outputs.');

fprintf('Voltage backend equivalence runner contract test passed.\n');
end

function assert_error_id(operation, expectedId)
actualId = '';
try
    operation();
catch ME
    actualId = ME.identifier;
end
assert(strcmp(actualId, expectedId), ...
    'Expected error ID "%s", received "%s".', expectedId, actualId);
end

function test_explicit_horn_seed(testRoot)
originalDirectory = pwd;
directoryCleanup = onCleanup(@() cd(originalDirectory));
cd(testRoot);
clear ea_genvat_horn;
expectedPath = fullfile(testRoot, 'unused_expected_output.nii');
first = mh_vta_run_horn_with_retry(struct(), 1, struct(), ...
    'label-one', expectedPath, 'SeedBase', 12345);
firstRandom = evalin('base', 'MH_TEST_HORN_RANDOM');
second = mh_vta_run_horn_with_retry(struct(), 1, struct(), ...
    'different-label', expectedPath, 'SeedBase', 12345);
secondRandom = evalin('base', 'MH_TEST_HORN_RANDOM');
rng(12345, 'twister');
expectedRandom = rand();
assert(first.seed_used == 12345 && second.seed_used == 12345, ...
    'Explicit Horn seed must be independent of stimulation label.');
assert(firstRandom == expectedRandom && secondRandom == expectedRandom, ...
    'Horn must receive the requested deterministic RNG stream.');
write_text(expectedPath, 'pre-existing');
didFail = false;
try
    mh_vta_run_horn_with_retry(struct(), 1, struct(), ...
        'forced-error', expectedPath, 'SeedBase', 12345);
catch ME
    didFail = strcmp(ME.identifier, 'test:ForcedHornFailure');
end

assert(didFail, ...
    'A pre-existing expected file must not swallow an arbitrary Horn error.');
end

function test_process_space_override()
previous = getenv('LEADDBS_SPACE_OVERRIDE');
environmentCleanup = onCleanup( ...
    @() setenv('LEADDBS_SPACE_OVERRIDE', previous));
setenv('LEADDBS_SPACE_OVERRIDE', 'MNI152NLin2009bAsym');
assert(strcmp(ea_getspace(), 'MNI152NLin2009bAsym'), ...
    'ea_getspace must honor the process-scoped override.');
end

function write_fixture_subject(subjectDir)
mkdir(fullfile(subjectDir, 'reconstruction'));
mkdir(fullfile(subjectDir, 'normalization', 'transformations'));
atlasDir = fullfile(subjectDir, 'atlases', ...
    'Custom_Ewert_Zhang_Middlebrooks');
mkdir(atlasDir);
write_text(fullfile(subjectDir, 'reconstruction', ...
    'sub-Test003_desc-reconstruction.mat'), 'reconstruction');
write_text(fullfile(subjectDir, 'normalization', 'transformations', ...
    'sub-Test003_from-anchorNative_to-MNI152NLin2009bAsym_desc-ants.nii.gz'), ...
    'transform');
write_text(fullfile(atlasDir, 'gm_mask.nii.gz'), 'mask');
end

function write_study_base(path, subjectDir)
source = @(id, contact) struct( ...
    'source_id', id, ...
    'source_label', 'target', ...
    'component_id', 'target_test', ...
    'frequency_hz', 130, ...
    'control_mode', 'voltage', ...
    'amplitude', 2.0, ...
    'pulse_width_us', 60, ...
    'contacts', [ ...
        struct('contact', contact, 'polarity', 'cathode', 'fraction', 1.0), ...
        struct('contact', 'case', 'polarity', 'anode', 'fraction', 1.0)]);
leftGroup = struct('frequency_group_id', 'group-1', ...
    'delivery_mode', 'continuous', 'sources', source('source-1', 0));
rightGroup = struct('frequency_group_id', 'group-1', ...
    'delivery_mode', 'continuous', 'sources', source('source-1', 4));
program = struct('program_id', 1, 'condition_role', 'reference_only', ...
    'stimulation_state', 'active', 'clinical_observations', struct([]), ...
    'electrode_programs', [ ...
        struct('electrode_id', 'lead-L', 'frequency_groups', leftGroup), ...
        struct('electrode_id', 'lead-R', 'frequency_groups', rightGroup)]);
phase = struct('phase_id', 'T1', 'programs', program);
subject = struct( ...
    'subject_id', 'Test003', ...
    'subject_label', 'Test Subject', ...
    'subject_sources', struct( ...
        'leaddbs_subject_dir', subjectDir, ...
        'electrode_reconstruction', struct('path', fullfile(subjectDir, ...
            'reconstruction', 'sub-Test003_desc-reconstruction.mat'))), ...
    'contact_numbering', struct( ...
        'convention', 'bilateral_contiguous_zero_based', ...
        'electrode_order', {{'lead-L', 'lead-R'}}), ...
    'electrodes', [ ...
        struct('electrode_id', 'lead-L', 'hemisphere', 'L', ...
            'electrode_model', 'Medtronic 3387', 'contact_count', 4, ...
            'reconstruction_lead_id', 2), ...
        struct('electrode_id', 'lead-R', 'hemisphere', 'R', ...
            'electrode_model', 'Medtronic 3387', 'contact_count', 4, ...
            'reconstruction_lead_id', 1)], ...
    'phases', phase);
payload = struct('schema_version', 'dual_frequency_study_v1', ...
    'study', struct('study_id', 'fixture', 'data_version', '1', ...
        'subjects', subject));
write_text(path, jsonencode(payload, PrettyPrint=true));
end

function write_vta_stubs(stubDir)
write_text(fullfile(stubDir, 'ea_genvat_horn.m'), ...
    "function ea_genvat_horn(varargin)" + newline + ...
    "if strcmp(varargin{5},'forced-error'), " + ...
    "error('test:ForcedHornFailure','forced'); end" + newline + ...
    "assignin('base','MH_TEST_HORN_RANDOM',rand());" + newline + ...
    "end" + newline);

write_text(fullfile(stubDir, 'mh_fiber_default_config.m'), ...
    "function cfg = mh_fiber_default_config(subjectDir, stimLabel)" + newline + ...
    "[~, patientName] = fileparts(subjectDir);" + newline + ...
    "cfg = struct('subjectDir', subjectDir, 'patientName', patientName, " + ...
    "'subjectId', erase(patientName, 'sub-'), 'stimLabel', stimLabel);" + newline + ...
    "cfg.outputRoot = fullfile(subjectDir, 'connectomics', 'fiber_vis');" + newline + ...
    "cfg.outputDir = fullfile(cfg.outputRoot, stimLabel);" + newline + ...
    "cfg.maxSourcesPerSide = 4; cfg.forceRecomputeVTA = true;" + newline + ...
    "cfg.vta = struct('modelKey', 'simbio', 'model', 'stub', " + ...
    "'space', 'MNI152NLin2009bAsym', 'gmAtlas', '');" + newline + ...
    "cfg.paths = struct();" + newline + ...
    "cfg.paths.reconstruction = fullfile(subjectDir, 'reconstruction', " + ...
    "[patientName, '_desc-reconstruction.mat']);" + newline + ...
    "cfg.paths.anchorToMniTransform = fullfile(subjectDir, 'normalization', " + ...
    "'transformations', [patientName, " + ...
    "'_from-anchorNative_to-MNI152NLin2009bAsym_desc-ants.nii.gz']);" + newline + ...
    "end" + newline);

write_text(fullfile(stubDir, 'mh_vta_run_stim_spec_tasks.m'), ...
    "function [results, tasks, cfg, S, options, folders] = " + ...
    "mh_vta_run_stim_spec_tasks(cfg, stimSpec, sides, varargin)" + newline + ...
    "backend = char(stimSpec.model); side = char(sides{1});" + newline + ...
    "if strcmp(backend,'simbio_onesolve'), error('test:LegacyOneSolveCalled'," + ...
    "'legacy one-solve backend must not be called'); end" + newline + ...
    "p=inputParser; p.KeepUnmatched=true; addParameter(p,'RngSeedBase',[]); " + ...
    "parse(p,varargin{:}); seed=double(p.Results.RngSeedBase);" + newline + ...
    "headmodelDir = fullfile(cfg.subjectDir, 'headmodel', 'native');" + newline + ...
    "if ~isfolder(headmodelDir), mkdir(headmodelDir); end" + newline + ...
    "sideIndex = 1 + strcmp(side, 'L');" + newline + ...
    "headmodel = fullfile(headmodelDir, sprintf('%s_desc-headmodel%d.mat', " + ...
    "cfg.patientName, sideIndex));" + newline + ...
    "if ~isfile(headmodel), fid=fopen(headmodel,'w'); fprintf(fid,'shared'); fclose(fid); end" + newline + ...
    "out = fullfile(cfg.subjectDir, 'stub_outputs', backend, cfg.stimLabel);" + newline + ...
    "if ~isfolder(out), mkdir(out); end" + newline + ...
    "data = single(reshape(160:223, [4 4 4]) + (side == 'R'));" + newline + ...
    "native = fullfile(out, 'native_efield.nii');" + newline + ...
    "mni = fullfile(out, 'mni_efield.nii');" + newline + ...
    "niftiwrite(data, native, 'Compressed', false);" + newline + ...
    "niftiwrite(data, mni, 'Compressed', false);" + newline + ...
    "diagnostics=struct('seed_used',seed,'attempt_count',1," + ...
    "'attempt_seeds',seed);" + newline + ...
    "results = struct('side', side, 'efield_native', native, " + ...
    "'efield_mni', mni, 'status', 'complete', " + ...
    "'rng_diagnostics',diagnostics);" + newline + ...
    "tasks = struct('side', side); S=struct(); options=struct(); folders=struct();" + newline + ...
    "end" + newline);

write_text(fullfile(stubDir, 'mh_vta_validate_canonical_task.m'), ...
    "function task = mh_vta_validate_canonical_task(task)" + newline + ...
    "end" + newline);

write_text(fullfile(stubDir, 'mh_vta_backend_simbio_onesolve_canonical.m'), ...
    "function status = mh_vta_backend_simbio_onesolve_canonical(task,varargin)" + newline + ...
    "nativeLeaf=task.output_leaves.native; mniLeaf=task.output_leaves.MNI152NLin2009bAsym;" + newline + ...
    "if ~isfolder(nativeLeaf), mkdir(nativeLeaf); end; if ~isfolder(mniLeaf), mkdir(mniLeaf); end" + newline + ...
    "data=single(reshape(160:223,[4 4 4])+(strcmp(task.hemisphere,'R')));" + newline + ...
    "native=fullfile(nativeLeaf,'efield.nii.gz'); mni=fullfile(mniLeaf,'efield.nii.gz');" + newline + ...
    "niftiwrite(data,erase(native,'.gz'),'Compressed',true); niftiwrite(data,erase(mni,'.gz'),'Compressed',true);" + newline + ...
    "thresholds=[180 200 220]; for i=1:numel(thresholds), token=strrep(sprintf('%.2f',thresholds(i)/1000),'.','p'); " + ...
    "path=fullfile(mniLeaf,['vta_threshold-',token,'Vpermm.nii.gz']); niftiwrite(uint8(data>=thresholds(i)),erase(path,'.gz'),'Compressed',true); end" + newline + ...
    "status=struct('native_efield',native,'mni_efield',mni,'headmodel_state','reused');" + newline + ...
    "end" + newline);
end

function write_text(path, text)
parent = fileparts(path);
if ~isempty(parent) && ~isfolder(parent)
    mkdir(parent);
end
fid = fopen(path, 'w');
assert(fid > 0, 'Could not create test file: %s', path);
cleanupObj = onCleanup(@() fclose(fid));
fprintf(fid, '%s', text);
end

function cleanup_test(testRoot, stubDir)
rmpath(stubDir);
clear mh_fiber_default_config mh_vta_run_stim_spec_tasks;
clear mh_vta_validate_canonical_task mh_vta_backend_simbio_onesolve_canonical;
clear ea_genvat_horn;
evalin('base', 'clear MH_TEST_HORN_RANDOM');
if isfolder(testRoot)
    rmdir(testRoot, 's');
end
end
