function gradient = mh_vta_fem_calc_gradient(vol, potential)
% Compute tetrahedral field gradients from FEM potentials.

normal = cross(vol.pos(vol.tet(:,4),:) - vol.pos(vol.tet(:,3),:), ...
    vol.pos(vol.tet(:,3),:) - vol.pos(vol.tet(:,2),:));
gradient = repmat(potential(vol.tet(:,1)) ./ sum(normal .* ...
    (vol.pos(vol.tet(:,1),:) - (vol.pos(vol.tet(:,2),:) + vol.pos(vol.tet(:,3),:) + vol.pos(vol.tet(:,4),:)) / 3), 2), 1, 3) .* normal;

normal = cross(vol.pos(vol.tet(:,1),:) - vol.pos(vol.tet(:,4),:), ...
    vol.pos(vol.tet(:,4),:) - vol.pos(vol.tet(:,3),:));
gradient = gradient + repmat(potential(vol.tet(:,2)) ./ sum(normal .* ...
    (vol.pos(vol.tet(:,2),:) - (vol.pos(vol.tet(:,3),:) + vol.pos(vol.tet(:,4),:) + vol.pos(vol.tet(:,1),:)) / 3), 2), 1, 3) .* normal;

normal = cross(vol.pos(vol.tet(:,2),:) - vol.pos(vol.tet(:,1),:), ...
    vol.pos(vol.tet(:,1),:) - vol.pos(vol.tet(:,4),:));
gradient = gradient + repmat(potential(vol.tet(:,3)) ./ sum(normal .* ...
    (vol.pos(vol.tet(:,3),:) - (vol.pos(vol.tet(:,4),:) + vol.pos(vol.tet(:,1),:) + vol.pos(vol.tet(:,2),:)) / 3), 2), 1, 3) .* normal;

normal = cross(vol.pos(vol.tet(:,3),:) - vol.pos(vol.tet(:,2),:), ...
    vol.pos(vol.tet(:,2),:) - vol.pos(vol.tet(:,1),:));
gradient = gradient + repmat(potential(vol.tet(:,4)) ./ sum(normal .* ...
    (vol.pos(vol.tet(:,4),:) - (vol.pos(vol.tet(:,1),:) + vol.pos(vol.tet(:,2),:) + vol.pos(vol.tet(:,3),:)) / 3), 2), 1, 3) .* normal;
end
