function tests = test_vta_event_protocol
% Protocol tests for canonical VTA MATLAB stdout events.

tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repoDir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(genpath(fullfile(repoDir, 'my_helper', 'fiber')));
addpath(repoDir);
testCase.TestData.repoDir = repoDir;
end

function testEmitterProducesContiguousDecodableEvents(testCase)
emit = mh_vta_make_event_emitter('run-001', 'SNr003'); %#ok<NASGU>
output = evalc("emit('subject_ready', struct()); " + ...
    "emit('task_started', struct('task_id','task-001'));");

events = parse_events(output);
verifyEqual(testCase, cellfun(@(event) event.sequence, events), [1, 2]);
verifyEqual(testCase, string(cellfun(@(event) event.schema_version, ...
    events, 'UniformOutput', false)), ...
    ["vta_event_v1", "vta_event_v1"]);
verifyEqual(testCase, string(cellfun(@(event) event.event_type, ...
    events, 'UniformOutput', false)), ...
    ["subject_ready", "task_started"]);
verifyEqual(testCase, string(cellfun(@(event) event.run_id, ...
    events, 'UniformOutput', false)), ["run-001", "run-001"]);
verifyEqual(testCase, string(cellfun(@(event) event.subject_id, ...
    events, 'UniformOutput', false)), ["SNr003", "SNr003"]);
end

function testEmitterRejectsInvalidIdentityAndEventType(testCase)
verifyError(testCase, @() mh_vta_make_event_emitter( ...
    ["run-1", "run-2"], 'SNr003'), 'mh_vta:InvalidEventIdentity');
verifyError(testCase, @() mh_vta_make_event_emitter(1, 'SNr003'), ...
    'mh_vta:InvalidEventIdentity');
emit = mh_vta_make_event_emitter('run-001', 'SNr003');
verifyError(testCase, @() emit('unknown', struct()), ...
    'mh_vta:UnsupportedEventType');
verifyError(testCase, @() emit('subject_ready', ...
    struct('sequence', 99)), 'mh_vta:ReservedEventField');
end

function testStageTimingValidatesScopeAndStatus(testCase)
emit = mh_vta_make_event_emitter('run-001', 'SNr003');
output = evalc("mh_vta_emit_stage_timing(emit, 'subject', '', " + ...
    "'manifest_decode_validation', 'executed', 0.25, 'miss');");
events = parse_events(output);

event = events{1};
verifyEqual(testCase, string(event.scope), "subject");
verifyEqual(testCase, string(event.stage), ...
    "manifest_decode_validation");
verifyEqual(testCase, event.duration_seconds, 0.25);
verifyEqual(testCase, string(event.cache_status), "miss");
verifyFalse(testCase, isfield(event, 'task_id'));
verifyError(testCase, @() mh_vta_emit_stage_timing(emit, ...
    'task', '', 'fem_pcg_solve', 'executed', 0.1, ''), ...
    'mh_vta:InvalidTimingField');
verifyError(testCase, @() mh_vta_emit_stage_timing(emit, ...
    'subject', '', 'manifest_decode_validation', ...
    'not_applicable', 0.1, ''), ...
    'mh_vta:InvalidNotApplicableTiming');
end

function testSuccessfulRunnerEmitsCompleteOneTaskProtocol(testCase)
taskPath = write_task_fixture(fixture_task());
cleanup = onCleanup(@() delete_if_present(taskPath));

output = evalc("status = mh_vta_run_canonical_task(taskPath, " + ...
    "'SolveFunction', @successful_solve);");
events = parse_events(output);

verifyEqual(testCase, cellfun(@(event) event.sequence, events), 1:5);
verifyEqual(testCase, string(cellfun(@(event) event.event_type, ...
    events, 'UniformOutput', false)), [ ...
    "stage_timing", "subject_ready", "task_started", ...
    "task_outcome", "subject_summary"]);
verifyEqual(testCase, string(events{1}.stage), ...
    "manifest_decode_validation");
verifyEqual(testCase, string(events{4}.status), "generated");
verifyEqual(testCase, events{4}.generated_artifact_count, 8);
verifyEqual(testCase, events{5}.generated, 1);
verifyTrue(testCase, events{5}.process_success);
end

function testFailingRunnerEmitsFailureBeforeRethrow(testCase)
taskPath = write_task_fixture(fixture_task());
cleanup = onCleanup(@() delete_if_present(taskPath));

caughtError = [];
output = evalc("try, mh_vta_run_canonical_task(taskPath, " + ...
    "'SolveFunction', @failing_solve); " + ...
    "catch caughtError, end");
events = parse_events(output);

verifyEqual(testCase, string(caughtError.identifier), ...
    "test_vta:ExpectedSolveFailure");
verifyEqual(testCase, string(cellfun(@(event) event.event_type, ...
    events, 'UniformOutput', false)), [ ...
    "stage_timing", "subject_ready", "task_started", ...
    "task_outcome", "subject_summary"]);
verifyEqual(testCase, string(events{4}.status), "failed");
verifyEqual(testCase, string(events{4}.error_identifier), ...
    "test_vta:ExpectedSolveFailure");
verifyEqual(testCase, events{5}.failed, 1);
verifyFalse(testCase, events{5}.process_success);
end

function testFailureWithoutIdentifierOmitsEmptyOptionalField(testCase)
taskPath = write_task_fixture(fixture_task());
cleanup = onCleanup(@() delete_if_present(taskPath));

caughtError = [];
output = evalc("try, mh_vta_run_canonical_task(taskPath, " + ...
    "'SolveFunction', @failing_solve_without_identifier); " + ...
    "catch caughtError, end");
events = parse_events(output);

verifyEmpty(testCase, caughtError.identifier);
verifyFalse(testCase, isfield(events{4}, 'error_identifier'));
verifyEqual(testCase, string(events{4}.error_message), ...
    "Expected failure without explicit identifier.");
end

function testInvalidJsonEmitsNoProtocolEvents(testCase)
taskPath = [tempname, '.json'];
cleanup = onCleanup(@() delete_if_present(taskPath));
write_text(taskPath, '{invalid json');

caughtError = [];
output = evalc("try, mh_vta_run_canonical_task(taskPath); " + ...
    "catch caughtError, end");

verifyEqual(testCase, string(caughtError.identifier), ...
    "mh_vta:InvalidCanonicalTaskJson");
verifyEmpty(testCase, parse_events(output));
end

function testCompleteStageSequencePrecedesTaskOutcome(testCase)
emit = mh_vta_make_event_emitter('run-001', 'SNr003'); %#ok<NASGU>
stages = [ ...
    "task_runtime_resolution", ...
    "subject_reconstruction_context", ...
    "headmodel_build_or_load", ...
    "active_contact_boundary", ...
    "fem_matrix_preparation", ...
    "fem_preconditioner", ...
    "fem_pcg_solve", ...
    "gradient_calculation", ...
    "electrode_removal_geometry", ...
    "native_grid_interpolation", ...
    "group_peak_composition", ...
    "threshold_generation", ...
    "native_to_mni_transform", ...
    "artifact_publication"];
output = evalc("emit('subject_ready',struct());" + ...
    "emit('task_started',struct('task_id','task-001'));" + ...
    "emit_all_stages(emit,stages);" + ...
    "emit('task_outcome',struct('task_id','task-001'," + ...
    "'status','generated','copied_artifact_count',0," + ...
    "'generated_artifact_count',1));" + ...
    "emit('subject_summary',success_summary());");
events = parse_events(output);
types = string(cellfun(@(event) event.event_type, ...
    events, 'UniformOutput', false));
outcomeIndex = find(types == "task_outcome", 1);
timingIndices = find(types == "stage_timing");

verifyEqual(testCase, numel(timingIndices), numel(stages));
verifyTrue(testCase, all(timingIndices < outcomeIndex));
verifyEqual(testCase, string(cellfun( ...
    @(event) event.stage, events(timingIndices), ...
    'UniformOutput', false)), stages);
verifyEqual(testCase, types(end), "subject_summary");
end

function emit_all_stages(emit, stages)
for stage = stages
    mh_vta_emit_stage_timing(emit, 'task', 'task-001', ...
        stage, 'executed', 0, '');
end
end

function fields = success_summary()
fields = struct( ...
    'generated', 1, ...
    'copied', 0, ...
    'skipped_existing', 0, ...
    'recovered_complete', 0, ...
    'failed', 0, ...
    'skipped_dependency', 0, ...
    'process_success', true);
end

function events = parse_events(output)
prefix = 'MH_VTA_EVENT ';
lines = splitlines(string(output));
lines = lines(startsWith(lines, prefix));
events = cell(1, numel(lines));
for lineIndex = 1:numel(lines)
    payload = extractAfter(lines(lineIndex), strlength(prefix));
    events{lineIndex} = jsondecode(payload);
end
end

function task = fixture_task()
task = struct( ...
    'task_id', 'task-001', ...
    'kind', 'continuous_joint', ...
    'subject_id', 'SNr003', ...
    'subject_dir', '/tmp/sub-SNr003', ...
    'reconstruction_path', '/tmp/sub-SNr003/reconstruction.mat', ...
    'phase_id', 'T1', ...
    'program_id', 1, ...
    'electrode_id', 'lead-R', ...
    'hemisphere', 'R', ...
    'electrode_model', 'Medtronic 3387', ...
    'reconstruction_lead_id', 1, ...
    'frequency_group_id', 'group-1', ...
    'delivery_mode', 'continuous', ...
    'sources', fixture_source(), ...
    'dependencies', {{}}, ...
    'model', fixture_model(), ...
    'run_id', 'run-001', ...
    'missing_artifacts', struct( ...
        'native', {{'efield.nii.gz', ...
            'vta_threshold-0p18Vpermm.nii.gz', ...
            'vta_threshold-0p20Vpermm.nii.gz', ...
            'vta_threshold-0p22Vpermm.nii.gz'}}, ...
        'MNI152NLin2009bAsym', {{'efield.nii.gz', ...
            'vta_threshold-0p18Vpermm.nii.gz', ...
            'vta_threshold-0p20Vpermm.nii.gz', ...
            'vta_threshold-0p22Vpermm.nii.gz'}}));
task.output_leaves = struct( ...
    'native', mh_vta_canonical_leaf_path(task, 'native'), ...
    'MNI152NLin2009bAsym', ...
        mh_vta_canonical_leaf_path(task, 'MNI152NLin2009bAsym'));
end

function source = fixture_source()
source = struct( ...
    'source_id', 'source-1', ...
    'frequency_hz', 130, ...
    'control_mode', 'voltage', ...
    'amplitude', 2.0, ...
    'pulse_width_us', 60, ...
    'contacts', [ ...
        struct('contact', 1, 'polarity', 'cathode', 'fraction', 1.0), ...
        struct('contact', 'case', 'polarity', 'anode', 'fraction', 1.0)]);
end

function model = fixture_model()
model = struct( ...
    'gray_matter_s_per_m', 0.33, ...
    'white_matter_s_per_m', 0.14, ...
    'atlas_set', 'Custom_Ewert_Zhang_Middlebrooks', ...
    'spaces', {{'native', 'MNI152NLin2009bAsym'}}, ...
    'thresholds_v_per_m', [180, 200, 220]);
end

function path = write_task_fixture(task)
path = [tempname, '.json'];
write_text(path, jsonencode(task));
end

function write_text(path, content)
fid = fopen(path, 'w');
assert(fid >= 0, 'Could not create event protocol fixture.');
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, content, 'char');
end

function status = successful_solve(task)
status = struct('execution', 'solve', 'task_id', task.task_id);
end

function status = failing_solve(~) %#ok<STOUT>
error('test_vta:ExpectedSolveFailure', 'Expected solve failure.');
end

function status = failing_solve_without_identifier(~) %#ok<STOUT>
error('Expected failure without explicit identifier.');
end

function delete_if_present(path)
if isfile(path)
    delete(path);
end
end
