function tests = test_vta_canonical_task_contract
% Contract tests for canonical Python-to-MATLAB VTA task payloads.

tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repoDir = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(genpath(fullfile(repoDir, 'my_helper', 'fiber')));
addpath(repoDir);
testCase.TestData.repoDir = repoDir;
end

function testContinuousSourcesRemainJoint(testCase)
task = fixture_task('continuous_joint', 'continuous', ...
    [fixture_source('source-1', 'voltage'), ...
     fixture_source('source-2', 'voltage')]);

resolved = mh_vta_validate_canonical_task(task);

verifyEqual(testCase, numel(resolved.solve_units), 1);
verifyEqual(testCase, ...
    string({resolved.solve_units{1}.source_id}), ...
    ["source-1", "source-2"]);
end

function testAlternatingSourceRemainsIndependent(testCase)
task = fixture_task('alternating_source', 'alternating', ...
    fixture_source('source-1', 'current'));

resolved = mh_vta_validate_canonical_task(task);

verifyEqual(testCase, numel(resolved.solve_units), 1);
verifyEqual(testCase, string(resolved.solve_units{1}.source_id), "source-1");
end

function testAlternatingGroupPeakIsDerivedWithoutSolveUnits(testCase)
task = fixture_task('alternating_group_peak', 'alternating', ...
    [fixture_source('source-1', 'voltage'), ...
     fixture_source('source-2', 'voltage')]);

resolved = mh_vta_validate_canonical_task(task);

verifyEmpty(testCase, resolved.solve_units);
end

function testMixedControlModesAreRejected(testCase)
task = fixture_task('continuous_joint', 'continuous', ...
    [fixture_source('source-1', 'voltage'), ...
     fixture_source('source-2', 'current')]);

verifyError(testCase, @() mh_vta_validate_canonical_task(task), ...
    'mh_vta:MixedControlMode');
end

function testTaskKindMustMatchDeliveryMode(testCase)
task = fixture_task('continuous_joint', 'alternating', ...
    fixture_source('source-1', 'voltage'));

verifyError(testCase, @() mh_vta_validate_canonical_task(task), ...
    'mh_vta:TaskKindDeliveryMismatch');
end

function testRuntimeContextFieldsAreRequired(testCase)
task = fixture_task('continuous_joint', 'continuous', ...
    fixture_source('source-1', 'voltage'));
task = rmfield(task, 'run_id');

verifyError(testCase, @() mh_vta_validate_canonical_task(task), ...
    'mh_vta:InvalidCanonicalTask');
end

function testRunnerReadsCanonicalJson(testCase)
task = fixture_task('continuous_joint', 'continuous', ...
    fixture_source('source-1', 'voltage'));
taskPath = [tempname '.json'];
cleanup = onCleanup(@() delete_if_present(taskPath));
fid = fopen(taskPath, 'w');
assert(fid >= 0, 'Could not create canonical task fixture.');
fileCleanup = onCleanup(@() fclose(fid));
fwrite(fid, jsonencode(task), 'char');
clear fileCleanup;

resolved = mh_vta_run_canonical_task(taskPath);

verifyEqual(testCase, string(resolved.task_id), "task-001");
verifyEqual(testCase, string(resolved.kind), "continuous_joint");
verifyEqual(testCase, numel(resolved.solve_units), 1);
end

function task = fixture_task(kind, deliveryMode, sources)
task = struct( ...
    'task_id', 'task-001', ...
    'kind', kind, ...
    'subject_id', 'SNr003', ...
    'subject_dir', '/tmp/sub-SNr003', ...
    'reconstruction_path', '/tmp/sub-SNr003/reconstruction.mat', ...
    'phase_id', 'T1', ...
    'program_id', 1, ...
    'electrode_id', 'lead-R', ...
    'hemisphere', 'R', ...
    'electrode_model', 'Medtronic 3387', ...
    'reconstruction_lead_id', 1, ...
    'frequency_group_id', 'group-1', ...
    'delivery_mode', deliveryMode, ...
    'sources', sources, ...
    'dependencies', {{}}, ...
    'model', fixture_model(), ...
    'run_id', '20260713T120000Z', ...
    'input_hash', 'input-hash', ...
    'study_base_sha256', 'study-hash', ...
    'vta_model_sha256', 'model-hash', ...
    'code_commit', '', ...
    'resume', false, ...
    'force', false, ...
    'output_leaves', struct( ...
        'native', '/tmp/native-leaf', ...
        'MNI152NLin2009bAsym', '/tmp/mni-leaf'));
end

function source = fixture_source(sourceId, controlMode)
source = struct( ...
    'source_id', sourceId, ...
    'frequency_hz', 130, ...
    'control_mode', controlMode, ...
    'amplitude', 2.0, ...
    'pulse_width_us', 60, ...
    'contacts', [ ...
        struct('contact', 1, 'polarity', 'cathode', 'fraction', 1.0), ...
        struct('contact', 'case', 'polarity', 'anode', 'fraction', 1.0)]);
end

function model = fixture_model()
model = struct( ...
    'gray_matter_s_per_m', 0.33, ...
    'white_matter_s_per_m', 0.14, ...
    'atlas_set', 'Custom_Ewert_Zhang_Middlebrooks', ...
    'spaces', {{'native', 'MNI152NLin2009bAsym'}}, ...
    'thresholds_v_per_m', [180, 200, 220]);
end

function delete_if_present(path)
if isfile(path)
    delete(path);
end
end
