function tests = test_vta_boundary_contract
% Validate voltage and current one-solve boundary assembly without FEM.

tests = functiontests(localfunctions);
end

function testVoltageCaseReturnUsesSignedVolts(testCase)
source = fixture_source('source-a', 2.5, 'V', 'voltage', [ ...
    fixture_contact(1, 'cathode', 1.0), ...
    fixture_contact('case', 'anode', 1.0)]);

boundary = mh_vta_assemble_boundary( ...
    source, fixture_activeidx(4), 'voltage');

verifyTrue(testCase, boundary.constvol);
verifyTrue(testCase, boundary.unipolar);
verifyEqual(testCase, boundary.node_indices, [11; 12]);
verifyEqual(testCase, boundary.values_and_groups, [-2.5, 1; -2.5, 1], ...
    'AbsTol', 1e-12);
verifyEqual(testCase, boundary.source_groups(1).source_id, 'source-a');
verifyEqual(testCase, boundary.source_groups(1).contact, 1);
end

function testCurrentIsConvertedFromMilliampereToAmpere(testCase)
source = fixture_source('source-a', 2.5, 'mA', 'current', [ ...
    fixture_contact(1, 'cathode', 1.0), ...
    fixture_contact('case', 'anode', 1.0)]);

boundary = mh_vta_assemble_boundary( ...
    source, fixture_activeidx(4), 'current');

verifyFalse(testCase, boundary.constvol);
verifyTrue(testCase, boundary.unipolar);
verifyEqual(testCase, unique(boundary.values_and_groups(:, 1)), -2.5e-3, ...
    'AbsTol', 1e-12);
end

function testCanonicalSourceDoesNotRequireRedundantUnitField(testCase)
source = fixture_source('source-a', 2.5, 'mA', 'current', [ ...
    fixture_contact(1, 'cathode', 1.0), ...
    fixture_contact('case', 'anode', 1.0)]);
source = rmfield(source, 'unit');

boundary = mh_vta_assemble_boundary( ...
    source, fixture_activeidx(4), 'current');

verifyFalse(testCase, boundary.constvol);
verifyEqual(testCase, unique(boundary.values_and_groups(:, 1)), -2.5e-3, ...
    'AbsTol', 1e-12);
end

function testMultipolarCurrentKeepsSignedFractions(testCase)
source = fixture_source('source-a', 4.0, 'mA', 'current', [ ...
    fixture_contact(1, 'cathode', 0.25), ...
    fixture_contact(2, 'cathode', 0.75), ...
    fixture_contact(3, 'anode', 0.40), ...
    fixture_contact(4, 'anode', 0.60)]);

boundary = mh_vta_assemble_boundary( ...
    source, fixture_activeidx(4), 'current');

verifyFalse(testCase, boundary.unipolar);
verifyEqual(testCase, boundary.values_and_groups(:, 1), [ ...
    -1e-3; -1e-3; -3e-3; -3e-3; 1.6e-3; 1.6e-3; 2.4e-3; 2.4e-3], ...
    'AbsTol', 1e-12);
verifyEqual(testCase, boundary.values_and_groups(:, 2), ...
    [1; 1; 2; 2; 3; 3; 4; 4]);
end

function testGroupingIsDeterministicAcrossSourceAndContactOrder(testCase)
sourceB = fixture_source('source-b', 2.0, 'V', 'voltage', [ ...
    fixture_contact(4, 'anode', 1.0), ...
    fixture_contact(3, 'cathode', 1.0)]);
sourceA = fixture_source('source-a', 1.0, 'V', 'voltage', [ ...
    fixture_contact(2, 'anode', 1.0), ...
    fixture_contact(1, 'cathode', 1.0)]);

forward = mh_vta_assemble_boundary( ...
    [sourceA, sourceB], fixture_activeidx(8), 'voltage');
reverse = mh_vta_assemble_boundary( ...
    [sourceB, sourceA], fixture_activeidx(8), 'voltage');

verifyEqual(testCase, reverse.node_indices, forward.node_indices);
verifyEqual(testCase, reverse.values_and_groups, forward.values_and_groups, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, {reverse.source_groups.source_id}, ...
    {'source-a', 'source-a', 'source-b', 'source-b'});
verifyEqual(testCase, [reverse.source_groups.contact], [1, 2, 3, 4]);
end

function testMoreThanFourSourcesAreSupported(testCase)
sources = repmat(fixture_source('', 1.0, 'V', 'voltage', ...
    [fixture_contact(1, 'cathode', 1.0), ...
     fixture_contact('case', 'anode', 1.0)]), 1, 5);
for index = 1:5
    sources(index).source_id = sprintf('source-%02d', index);
    sources(index).contacts(1).contact = index;
end

boundary = mh_vta_assemble_boundary( ...
    sources, fixture_activeidx(5), 'voltage');

verifyEqual(testCase, numel(boundary.source_groups), 5);
verifyEqual(testCase, unique(boundary.values_and_groups(:, 2))', 1:5);
end

function testDuplicateContinuousContactIsRejected(testCase)
sourceA = fixture_source('source-a', 1.0, 'V', 'voltage', [ ...
    fixture_contact(1, 'cathode', 1.0), ...
    fixture_contact('case', 'anode', 1.0)]);
sourceB = fixture_source('source-b', 2.0, 'V', 'voltage', [ ...
    fixture_contact(1, 'cathode', 1.0), ...
    fixture_contact('case', 'anode', 1.0)]);

verifyError(testCase, @() mh_vta_assemble_boundary( ...
    [sourceA, sourceB], fixture_activeidx(4), 'voltage'), ...
    'mh_vta_assemble_boundary:DuplicateContact');
end

function testMixedControlModesAreRejected(testCase)
voltage = fixture_source('source-a', 1.0, 'V', 'voltage', [ ...
    fixture_contact(1, 'cathode', 1.0), ...
    fixture_contact('case', 'anode', 1.0)]);
current = fixture_source('source-b', 2.0, 'mA', 'current', [ ...
    fixture_contact(2, 'cathode', 1.0), ...
    fixture_contact('case', 'anode', 1.0)]);

verifyError(testCase, @() mh_vta_assemble_boundary( ...
    [voltage, current], fixture_activeidx(4), 'voltage'), ...
    'mh_vta_assemble_boundary:MixedControlMode');
end

function testFractionsMustNormalizeWithinEachSign(testCase)
source = fixture_source('source-a', 3.0, 'mA', 'current', [ ...
    fixture_contact(1, 'cathode', 0.6), ...
    fixture_contact(2, 'cathode', 0.3), ...
    fixture_contact('case', 'anode', 1.0)]);

verifyError(testCase, @() mh_vta_assemble_boundary( ...
    source, fixture_activeidx(4), 'current'), ...
    'mh_vta_assemble_boundary:InvalidContactFraction');
end

function source = fixture_source(sourceId, amplitude, unit, controlMode, contacts)
source = struct( ...
    'source_id', sourceId, ...
    'amplitude', amplitude, ...
    'unit', unit, ...
    'control_mode', controlMode, ...
    'contacts', contacts);
end

function contact = fixture_contact(identifier, polarity, fraction)
contact = struct( ...
    'contact', identifier, ...
    'polarity', polarity, ...
    'fraction', fraction);
end

function activeidx = fixture_activeidx(numContacts)
activeidx = struct('con', repmat(struct('ix', []), 1, numContacts));
for contact = 1:numContacts
    activeidx.con(contact).ix = [contact * 10 + 1; contact * 10 + 2];
end
end
